import React, { useCallback, useEffect, useMemo, useState } from 'react';
import { ArrowUpRight, Clock3, Newspaper } from 'lucide-react';
import { fetchBusinessNews } from '../../services/learningApi';
import type { NormalizedNewsItem } from '../../types';

type Props = { onOpenFeed: () => void };
function formatDate(value: string | null) { if (!value) return 'Publication time unavailable'; const date = new Date(value); if (Number.isNaN(date.getTime())) return value; return new Intl.DateTimeFormat('en-IN', { day: '2-digit', month: 'short', hour: '2-digit', minute: '2-digit' }).format(date); }
function dedupeAndFilter(items: NormalizedNewsItem[]) { const seen = new Set<string>(); const relevance = /(business|market|company|companies|earnings|economy|economic|rbi|central bank|rate|rates|inflation|technology|energy|commodity|commodities|financial|finance|policy|stocks|investment)/i; return items.filter((item) => { const key = `${item.id}|${item.sourceUrl}|${item.title.trim().toLowerCase()}`; if (seen.has(key)) return false; seen.add(key); return true; }).sort((a, b) => Number(relevance.test(b.category) || relevance.test(b.title)) - Number(relevance.test(a.category) || relevance.test(a.title))).slice(0, 5); }
function sameStory(a: NormalizedNewsItem | undefined, b: NormalizedNewsItem) { return Boolean(a && (a.id === b.id || a.sourceUrl === b.sourceUrl || a.title.trim().toLowerCase() === b.title.trim().toLowerCase())); }
export const BusinessNewsSection: React.FC<Props> = ({ onOpenFeed }) => {
  const [items, setItems] = useState<NormalizedNewsItem[]>([]); const [activeKey, setActiveKey] = useState<string | null>(null); const [loading, setLoading] = useState(true); const [failed, setFailed] = useState(false); const [updatedAt, setUpdatedAt] = useState<string | null>(null);
  const load = useCallback(async (initial = false) => { if (initial) setLoading(true); setFailed(false); try { const next = dedupeAndFilter(await fetchBusinessNews('business')); setItems((previous) => { const current = previous.find((item) => item.id === activeKey || item.sourceUrl === activeKey); const preserved = current ? next.find((item) => sameStory(current, item)) : undefined; const first = next.find((item) => item.imageUrl) ?? next[0]; setActiveKey((key) => preserved?.id ?? (key && next.some((item) => item.id === key) ? key : first?.id ?? null)); return next; }); setUpdatedAt(next[0]?.retrievedAt ?? new Date().toISOString()); if (!next.length) setFailed(true); } catch { setFailed(true); } finally { if (initial) setLoading(false); } }, [activeKey]);
  useEffect(() => { void load(true); let last = Date.now(); const handleVisibility = () => { if (document.visibilityState !== 'visible' || Date.now() - last < 120000) return; last = Date.now(); void load(false); }; document.addEventListener('visibilitychange', handleVisibility); return () => document.removeEventListener('visibilitychange', handleVisibility); }, [load]);
  const featured = useMemo(() => items.find((item) => item.id === activeKey) ?? items.find((item) => item.imageUrl) ?? items[0], [activeKey, items]);
  const secondary = useMemo(() => items.filter((item) => item.id !== featured?.id).slice(0, 4), [featured?.id, items]);
  return <section className="border-y border-slate-200 bg-white" aria-labelledby="landing-business-brief"><div className="mx-auto max-w-7xl px-4 py-20 sm:px-6 lg:px-8">
    <div className="mb-8 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><div className="flex items-center gap-2 text-[10px] font-black uppercase tracking-[.15em] text-teal-700"><Newspaper className="h-3.5 w-3.5" aria-hidden="true"/>Connected business news</div><h2 id="landing-business-brief" className="mt-2 text-3xl font-black text-[#172033] sm:text-4xl">Business Brief</h2><p className="mt-2 max-w-2xl text-sm leading-7 text-slate-600">Provider-backed business and market headlines, clearly sourced and time-stamped.</p></div><div className="flex items-center gap-3"><span className="text-[9px] font-semibold text-slate-400">Updated {updatedAt ? formatDate(updatedAt) : '—'}</span><button type="button" onClick={onOpenFeed} className="inline-flex items-center gap-2 self-start rounded-xl border border-slate-200 bg-white px-4 py-2.5 text-xs font-black text-slate-700 shadow-sm transition hover:border-teal-300 hover:text-teal-700 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-teal-700">View all headlines <ArrowUpRight className="h-3.5 w-3.5" aria-hidden="true"/></button></div></div>
    {loading ? <div className="grid gap-4 lg:grid-cols-[1.25fr_.75fr]" aria-label="Loading business headlines"><div className="min-h-[340px] animate-pulse rounded-3xl bg-slate-100"/><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-1"><div className="h-36 animate-pulse rounded-2xl bg-slate-100"/><div className="h-36 animate-pulse rounded-2xl bg-slate-100"/></div></div> : failed ? <div className="rounded-3xl border border-slate-200 bg-slate-50 p-10 text-center"><p className="text-sm font-bold text-slate-700">Business headlines are temporarily unavailable.</p><p className="mt-2 text-xs text-slate-500">The connected news provider did not return usable relevant articles. No synthetic headlines are shown.</p></div> : <div className="grid gap-4 lg:grid-cols-[1.25fr_.75fr]">
      {featured && <article className="group overflow-hidden rounded-3xl border border-slate-200 bg-slate-950 shadow-sm"><div className="relative min-h-[340px] overflow-hidden" aria-live="polite">{featured.imageUrl ? <img src={featured.imageUrl} alt={`News image for ${featured.title} from ${featured.sourceName}`} loading="eager" className="absolute inset-0 h-full w-full object-cover transition-opacity duration-300" referrerPolicy="no-referrer" onError={(event) => { event.currentTarget.style.display = 'none'; }}/> : <div className="absolute inset-0 flex items-center justify-center bg-[radial-gradient(circle_at_35%_20%,rgba(20,184,166,.2),transparent_35%),linear-gradient(135deg,#172033,#0f172a)]"><div className="text-center"><Newspaper className="mx-auto h-10 w-10 text-teal-300/70" aria-hidden="true"/><p className="mt-3 text-[10px] font-black uppercase tracking-[.16em] text-slate-400">ArthaMind editorial fallback</p><p className="mt-1 text-xs text-slate-500">No provider image supplied</p></div></div>}<div className="absolute inset-0 bg-gradient-to-t from-slate-950 via-slate-950/55 to-transparent"/><div className="absolute inset-x-0 bottom-0 p-6 sm:p-8"><div className="mb-3 flex flex-wrap items-center gap-2 text-[10px] font-bold uppercase tracking-[.12em] text-teal-200"><span>{featured.sourceName}</span><span className="text-slate-400">·</span><span>{featured.category || 'Business'}</span></div><h3 className="max-w-3xl text-2xl font-black leading-tight text-white sm:text-3xl">{featured.title}</h3>{featured.summary && <p className="mt-3 max-w-2xl line-clamp-2 text-xs leading-5 text-slate-300">{featured.summary}</p>}<div className="mt-4 flex flex-wrap items-center gap-4 text-[11px] text-slate-300"><span className="inline-flex items-center gap-2"><Clock3 className="h-3.5 w-3.5" aria-hidden="true"/>{formatDate(featured.publishedAt)}</span><a href={featured.sourceUrl} target="_blank" rel="noopener noreferrer" className="inline-flex items-center gap-1 font-black text-teal-200 underline-offset-4 hover:underline focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-teal-300">Read original <ArrowUpRight className="h-3.5 w-3.5"/></a></div></div></div></article>}
      <div role="listbox" aria-label="Business headlines" className="grid gap-3 sm:grid-cols-2 lg:grid-cols-1">{secondary.map((item) => <button key={item.id} type="button" role="option" aria-selected={item.id === activeKey} onClick={() => setActiveKey(item.id)} onKeyDown={(event) => { if (event.key === 'Enter' || event.key === ' ') { event.preventDefault(); setActiveKey(item.id); } }} className={`group grid min-h-[142px] grid-cols-[120px_1fr] overflow-hidden rounded-2xl border bg-white text-left shadow-sm transition hover:-translate-y-0.5 hover:shadow-md focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-teal-700 ${item.id === activeKey ? 'border-teal-400 ring-1 ring-teal-200' : 'border-slate-200'}`}><div className="relative overflow-hidden bg-slate-100">{item.imageUrl ? <img src={item.imageUrl} alt={`News image for ${item.title}`} loading="lazy" className="h-full w-full object-cover transition duration-500 group-hover:scale-[1.03]" referrerPolicy="no-referrer" onError={(event) => { event.currentTarget.style.display = 'none'; }}/> : <div className="flex h-full min-h-[142px] items-center justify-center text-slate-400"><Newspaper className="h-7 w-7" aria-hidden="true"/></div>}</div><div className="p-4"><div className="text-[9px] font-black uppercase tracking-[.12em] text-teal-700">{item.sourceName}</div><h3 className="mt-2 line-clamp-3 text-sm font-black leading-5 text-[#172033]">{item.title}</h3><p className="mt-3 text-[10px] text-slate-500">{formatDate(item.publishedAt)}</p></div></button>)}</div>
    </div>}
    <p className="mt-5 text-[10px] leading-5 text-slate-500">Provider/freshness follows the connected workspace news service. Headlines are informational; they are not verified investment signals.</p>
  </div></section>;
};
