import React, { useEffect, useMemo, useState } from 'react';
import { ArrowUpRight, Clock3, Newspaper } from 'lucide-react';
import { fetchBusinessNews } from '../../services/learningApi';
import type { NormalizedNewsItem } from '../../types';

type Props = { onOpenFeed: () => void };
function formatDate(value: string | null) { if (!value) return 'Publication time unavailable'; const date = new Date(value); if (Number.isNaN(date.getTime())) return value; return new Intl.DateTimeFormat('en-IN', { day: '2-digit', month: 'short', hour: '2-digit', minute: '2-digit' }).format(date); }
function dedupe(items: NormalizedNewsItem[]) { const seen = new Set<string>(); return items.filter((item) => { const key = `${item.sourceUrl}|${item.title.trim().toLowerCase()}`; if (seen.has(key)) return false; seen.add(key); return true; }).slice(0, 5); }
export const BusinessNewsSection: React.FC<Props> = ({ onOpenFeed }) => {
  const [items, setItems] = useState<NormalizedNewsItem[]>([]); const [loading, setLoading] = useState(true); const [failed, setFailed] = useState(false);
  useEffect(() => { let active = true; setLoading(true); setFailed(false); fetchBusinessNews('business').then((next) => { if (!active) return; const unique = dedupe(next); setItems(unique); setFailed(unique.length === 0); }).catch(() => { if (active) setFailed(true); }).finally(() => { if (active) setLoading(false); }); return () => { active = false; }; }, []);
  const featured = items[0]; const secondary = useMemo(() => items.slice(1, 5), [items]);
  return <section className="border-y border-slate-200 bg-white" aria-labelledby="landing-business-brief"><div className="mx-auto max-w-7xl px-4 py-20 sm:px-6 lg:px-8">
    <div className="mb-8 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><div className="flex items-center gap-2 text-[10px] font-black uppercase tracking-[.15em] text-teal-700"><Newspaper className="h-3.5 w-3.5" aria-hidden="true"/>Connected business news</div><h2 id="landing-business-brief" className="mt-2 text-3xl font-black text-[#172033] sm:text-4xl">Business Brief</h2><p className="mt-2 max-w-2xl text-sm leading-7 text-slate-600">Current business, market and economy headlines from the same connected news service used by the workspace.</p></div><button type="button" onClick={onOpenFeed} className="inline-flex items-center gap-2 self-start rounded-xl border border-slate-200 bg-white px-4 py-2.5 text-xs font-black text-slate-700 shadow-sm transition hover:border-teal-300 hover:text-teal-700 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-teal-700">View all headlines <ArrowUpRight className="h-3.5 w-3.5" aria-hidden="true"/></button></div>
    {loading ? <div className="grid gap-4 lg:grid-cols-[1.25fr_.75fr]" aria-label="Loading business headlines"><div className="min-h-[300px] animate-pulse rounded-3xl bg-slate-100"/><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-1"><div className="h-36 animate-pulse rounded-2xl bg-slate-100"/><div className="h-36 animate-pulse rounded-2xl bg-slate-100"/></div></div> : failed ? <div className="rounded-3xl border border-slate-200 bg-slate-50 p-10 text-center"><p className="text-sm font-bold text-slate-700">Headlines are temporarily unavailable</p><p className="mt-2 text-xs text-slate-500">The connected news provider did not return usable articles. No synthetic headlines are shown.</p></div> : <div className="grid gap-4 lg:grid-cols-[1.25fr_.75fr]">
      {featured && <article className="group overflow-hidden rounded-3xl border border-slate-200 bg-slate-950 shadow-sm"><a href={featured.sourceUrl} target="_blank" rel="noopener noreferrer" className="block h-full focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-[-2px] focus-visible:outline-teal-300" aria-label={`Open ${featured.title} from ${featured.sourceName}`}><div className="relative min-h-[340px] overflow-hidden">{featured.imageUrl ? <img src={featured.imageUrl} alt={`News image for ${featured.title}`} loading="eager" className="absolute inset-0 h-full w-full object-cover transition duration-500 group-hover:scale-[1.02]" referrerPolicy="no-referrer" onError={(event) => { event.currentTarget.style.display = 'none'; }}/> : null}<div className="absolute inset-0 bg-gradient-to-t from-slate-950 via-slate-950/55 to-transparent"/><div className="absolute inset-x-0 bottom-0 p-6 sm:p-8"><div className="mb-3 flex flex-wrap items-center gap-2 text-[10px] font-bold uppercase tracking-[.12em] text-teal-200"><span>{featured.sourceName}</span><span className="text-slate-400">·</span><span>{featured.category || 'Business'}</span></div><h3 className="max-w-3xl text-2xl font-black leading-tight text-white sm:text-3xl">{featured.title}</h3><div className="mt-4 flex items-center gap-2 text-[11px] text-slate-300"><Clock3 className="h-3.5 w-3.5" aria-hidden="true"/>{formatDate(featured.publishedAt)}</div></div></div></a></article>}
      <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-1">{secondary.map((item) => <article key={item.id} className="group overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm transition hover:-translate-y-0.5 hover:shadow-md"><a href={item.sourceUrl} target="_blank" rel="noopener noreferrer" className="grid grid-cols-[120px_1fr] min-h-[140px] focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-[-2px] focus-visible:outline-teal-700" aria-label={`Open ${item.title} from ${item.sourceName}`}><div className="relative overflow-hidden bg-slate-100">{item.imageUrl ? <img src={item.imageUrl} alt={`News image for ${item.title}`} loading="lazy" className="h-full w-full object-cover transition duration-500 group-hover:scale-[1.03]" referrerPolicy="no-referrer" onError={(event) => { event.currentTarget.style.display = 'none'; }}/> : <div className="flex h-full min-h-[140px] items-center justify-center text-slate-400"><Newspaper className="h-7 w-7" aria-hidden="true"/></div>}</div><div className="p-4"><div className="text-[9px] font-black uppercase tracking-[.12em] text-teal-700">{item.sourceName}</div><h3 className="mt-2 line-clamp-3 text-sm font-black leading-5 text-[#172033]">{item.title}</h3><p className="mt-3 text-[10px] text-slate-500">{formatDate(item.publishedAt)}</p></div></a></article>)}</div>
    </div>}
    <p className="mt-5 text-[10px] leading-5 text-slate-500">Provider/freshness follows the connected workspace news service. Headlines are informational context only and are not verified investment signals.</p>
  </div></section>;
};
