import React,{useEffect,useRef,useState}from'react';
import{ArrowRight,ArrowUp,CheckCircle2,Menu,Sparkles,X}from'lucide-react';
import type{AppNavigationDestination}from'../../navigationTypes';
import type{NormalizedMarketQuote}from'../../types';
import{fetchBusinessNews}from'../../services/learningApi';
import{ArthaMindLogo}from'./ArthaMindLogo';
import{LiveMarketTicker}from'./LiveMarketTicker';
import{LazyCryptoMarketPreview as CryptoMarketPreview}from'./LazyCryptoMarketPreview';
import{BusinessBrief,normalizeBusinessNews}from'./BusinessBrief';
import{LanguageSelector}from'../LanguageSelector';
import'./connectedLanding.css';
import'./landingMotion.css';
import{useLandingMotion}from'./useLandingMotion';
import{LandingAiCfo}from'./LandingAiCfo';
import{LandingReviews}from'./LandingReviews';
import{LandingIntelligenceSection}from'./LandingIntelligenceSection';
import{LandingMarketDashboard}from'./LandingMarketDashboard';

type Props={signedIn:boolean;onEnter:(destination?:AppNavigationDestination)=>void;onSignIn:()=>void};
type MacroCard={label:string;value:string;delta:string;direction:'up'|'down'|'flat'|'none'};
const SAMPLE_CHECK_COUNT=6;
const NAV_LINKS=[['modules','Modules'],['market-data','Market data'],['how','How it works'],['lab','Reliability Lab'],['trust','Trust & privacy']] as const;
const HERO_WORDS=['Plans your taxes.','Tames your EMIs.','Funds your goals.','Guards your cash flow.'];
const CAPABILITIES=['Old vs new tax regime','80C · 80D · NPS room','EMI prepayment vs invest','6-month emergency runway','SIP for every goal','Retirement corpus','Term & health cover gap','Home-loan affordability','Business cash flow','Credit-card debt payoff','Hindi & Hinglish answers','Verified ₹ calculations'];
/** Cycles hero phrases with a slide-up transition; shows the first phrase only for reduced motion. */
const RotatingWords:React.FC<{words:readonly string[]}>=({words})=>{const[index,setIndex]=useState(0);useEffect(()=>{if(window.matchMedia('(prefers-reduced-motion: reduce)').matches)return;const id=window.setInterval(()=>setIndex(i=>(i+1)%words.length),2600);return()=>window.clearInterval(id)},[words.length]);return <em className="cl-rotator" aria-live="off"><span key={index} className="cl-rotator-word">{words[index]}</span><span className="cl-sr">{words.join(' ')}</span></em>};
/** Formats a provider quote for a macro card. A missing or non-finite change is shown as unavailable, never as +0.00%. */
export function macroCardFromQuote(label:string,quote:NormalizedMarketQuote|undefined):MacroCard{const price=quote?Number(quote.price):NaN;const change=quote&&quote.changePercent!=null?Number(quote.changePercent):NaN;const value=Number.isFinite(price)?price.toLocaleString('en-IN',{maximumFractionDigits:2}):'';if(!quote)return{label,value,delta:'Connect data source',direction:'none'};if(!Number.isFinite(change))return{label,value,delta:'Change unavailable',direction:'none'};const rounded=Math.round(change*100)/100;return{label,value,delta:(rounded>0?'+':rounded<0?'−':'')+Math.abs(rounded).toFixed(2)+'%',direction:rounded>0?'up':rounded<0?'down':'flat'};}
/** Share of the ring to leave unfilled for `passed` of `total` checks (0 = full ring). */
export function scoreRingOffset(passed:number,total:number):number{if(!(total>0))return 1;return 1-Math.min(Math.max(passed,0),total)/total;}
// Target is a workspace, or `ask:<question>` to hand the question to the AI CFO on this page.
const modules=[
 ['SD','Smart Dashboard','Income, expenses, savings rate and EMI burden in one live view.','Plan','dashboard'],
 ['GP','Goal Planner','The monthly SIP each goal needs, adjusted for inflation.','Plan','financial-twin'],
 ['HS','Financial Health Score','A 0 to 100 score with personal tips to improve it.','Plan','financial-health'],
 ['RP','Retirement Planner','The corpus you need, three scenarios and the gap to close.','Plan','ask:I am 32, earn ₹1.2 lakh a month take-home and spend ₹70,000. How big a retirement corpus do I need at 60 and what monthly SIP gets me there? Show three scenarios.'],
 ['EC','Education Cost Planner','Future education costs with inflation and the SIP to reach them.','Plan','ask:My child is 4. An engineering degree costs ₹20 lakh today. What will it cost in 14 years at 10% education inflation, and what monthly SIP do I need?'],
 ['CI','Career Income Projection','Ten-year salary and wealth paths: stay, switch or grow.','Plan','ask:I earn ₹18 lakh a year. Compare my 10-year income and wealth if I stay (8% raises), switch jobs now (30% hike, then 8%) or do an MBA costing ₹25 lakh.'],
 ['NW','Net Worth Tracker','Assets, liabilities and your wealth trajectory over time.','Plan','finance-reports'],
 ['PT','Portfolio Tracker','SIPs, funds, stocks, FDs, PPF and NPS with real returns.','Invest','market-watchlist'],
 ['MD','Market Data Dashboard','NIFTY 50, SENSEX, USD/INR and gold from available provider-backed market data.','Invest','markets'],
 ['TX','Tax Optimiser','Old versus new regime and unused 80C, 80D and NPS room.','Tax & Debt','income'],
 ['EM','EMI & Loan Manager','Amortisation, prepayment simulator and loan comparison.','Tax & Debt','emi-manager'],
 ['IN','Insurance Analyser','Human Life Value, cover gap and protection score.','Protect','ask:I am 35, earn ₹15 lakh a year, have a ₹45 lakh home loan and two kids. Estimate my Human Life Value, the term cover I need and my health cover gap.'],
 ['FA','Family Income Analyser','Dependency ratio and financial stress for each earner.','Protect','ask:Our family has two earners (₹90,000 and ₹45,000 a month take-home), three dependants and ₹38,000 in EMIs. Analyse our dependency ratio and financial stress per earner.'],
 ['RR','Financial Risk Radar','Five risk dimensions and three actions to reduce them.','Protect','quick-check'],
 ['AI','AI Financial Advisor','Ask in Hinglish or English and get numbers-backed answers.','AI','ask:'],
] as const;
const checks=[['Reasoning',true],['Numerical accuracy',true],['Grounding',true],['Risk awareness',true],['Explainability',true],['Evidence',false]] as const;
const LiveCryptoChart:React.FC=()=>{const [candles,setCandles]=useState<{open:number;high:number;low:number;close:number;volume:number}[]>([]);const [interval,setIntervalState]=useState<'1m'|'5m'|'15m'|'1h'|'4h'|'1d'>('1h');const [status,setStatus]=useState('Connecting to Binance…');useEffect(()=>{let alive=true;const load=async()=>{try{const r=await fetch(`/api/crypto/klines?symbol=BTCUSDT&interval=${interval}`);if(!r.ok)throw new Error('unavailable');const d=await r.json();if(!alive)return;setCandles((d.candles||[]).slice(-32));setStatus('Live · Binance Public Market Data')}catch{if(alive)setStatus('Unavailable · provider did not respond')}};void load();const t=window.setInterval(()=>void load(),5000);return()=>{alive=false;window.clearInterval(t)}},[interval]);const data=candles.length?candles:[];if(!data.length)return <div className="cl-chart-box"><div style={{padding:'36px',color:'#94a3b8',fontSize:12}}>{status}</div></div>;const min=Math.min(...data.map(b=>b.low)),max=Math.max(...data.map(b=>b.high)),y=(v:number)=>154-(v-min)/(max-min||1)*120,w=480/data.length;return <div className="cl-chart-box"><div style={{display:'flex',justifyContent:'space-between',alignItems:'center',gap:8,padding:'8px 10px',fontSize:10,color:'#94a3b8'}}><b style={{color:'#0f766e'}}>BTC/USDT</b><span>{status}</span></div><div className="cl-timeframes">{(['1m','5m','15m','1h','4h','1d'] as const).map(t=><button key={t} className={interval===t?'on':''} onClick={()=>setIntervalState(t)}>{t}</button>)}</div><svg viewBox="0 0 520 185" className="cl-chart" role="img" aria-label="Live BTC USDT Binance candlestick chart">{data.map((b,i)=>{const x=10+i*w;const up=b.close>=b.open;return <g key={i} className="cl-candle cl-candle-animate" style={{'--i':i} as React.CSSProperties}><line x1={x} x2={x} y1={y(b.high)} y2={y(b.low)} className={up?'cl-up':'cl-down'}/><rect x={x-w*.28} y={Math.min(y(b.open),y(b.close))} width={Math.max(3,w*.56)} height={Math.max(2,Math.abs(y(b.open)-y(b.close)))} className={up?'cl-up-fill':'cl-down-fill'}/></g>})}</svg></div>};
const SampleChart=()=>{const bars=Array.from({length:30},(_,i)=>{const base=96+Math.sin(i*.55)*8+Math.sin(i*.16)*12;const close=base+Math.sin(i*1.7)*3;const open=base+Math.cos(i*1.2)*3;const high=Math.max(open,close)+2+(i%4);const low=Math.min(open,close)-2-(i%3);return{open,close,high,low}});const min=Math.min(...bars.map(b=>b.low))-3,max=Math.max(...bars.map(b=>b.high))+3;const y=(v:number)=>154-(v-min)/(max-min)*120;const ma=bars.map((b,i)=>{const start=Math.max(0,i-4);const avg=bars.slice(start,i+1).reduce((s,x)=>(s+x.close),0)/(i-start+1);return [8+i*17.2,y(avg)] as const});const maPath=ma.map(([x,yy],i)=>`${i?'L':'M'} ${x} ${yy}`).join(' ');return <svg viewBox="0 0 520 185" className="cl-chart" role="img" aria-label="Illustrative market candlestick chart">{[0,1,2,3].map(i=><line key={i} x1="0" x2="520" y1={18+i*40} y2={18+i*40} className="cl-grid"/>) }<path d={maPath} pathLength="1" className="cl-ma" fill="none" />{bars.map((b,i)=>{const x=8+i*17.2;const up=b.close>=b.open;return <g key={i} className="cl-candle" style={{'--i':i,animationDelay:(i*18+250)+'ms'} as React.CSSProperties}><line x1={x} x2={x} y1={y(b.high)} y2={y(b.low)} className={up?'cl-up':'cl-down'}/><rect x={x-3.8} y={Math.min(y(b.open),y(b.close))} width="7.6" height={Math.max(2,Math.abs(y(b.open)-y(b.close)))} className={up?'cl-up-fill':'cl-down-fill'}/></g>})}</svg>};
export const ConnectedLandingPage:React.FC<Props>=({signedIn,onEnter,onSignIn})=>{
 const[scrolled,setScrolled]=useState(false),[active,setActive]=useState('workspace'),[tab,setTab]=useState('All'),[lab,setLab]=useState(false),[passedChecks,setPassedChecks]=useState(0),[reviewed,setReviewed]=useState(0),[answer,setAnswer]=useState(''),[scan,setScan]=useState(false),[evidenceOpen,setEvidenceOpen]=useState(false),[news,setNews]=useState<ReturnType<typeof normalizeBusinessNews>>([]);
 const rootRef=useRef<HTMLDivElement>(null);const[menuOpen,setMenuOpen]=useState(false);useEffect(()=>{if(!menuOpen)return;const onKey=(e:KeyboardEvent)=>{if(e.key==='Escape')setMenuOpen(false)};window.addEventListener('keydown',onKey);return()=>window.removeEventListener('keydown',onKey)},[menuOpen]);const[cfoPrompt,setCfoPrompt]=useState<{id:number;text:string}|null>(null);const[showTop,setShowTop]=useState(false);useLandingMotion(rootRef);
 useEffect(()=>{const f=()=>{setScrolled(window.scrollY>8);setShowTop(window.scrollY>900)};f();addEventListener('scroll',f,{passive:true});return()=>removeEventListener('scroll',f)},[]);
 useEffect(()=>{const full="Context suggests a mix of broad sentiment and sector movement. The answer stays inspectable rather than presenting confidence as correctness.";let cancelled=false;let timers:number[]=[];const later=(fn:()=>void,ms:number)=>{const id=window.setTimeout(fn,ms);timers.push(id)};const cycle=(first:boolean)=>{if(cancelled)return;setReviewed(0);setAnswer('');setScan(false);setEvidenceOpen(false);const d=first?2100:200;later(()=>{if(window.matchMedia('(prefers-reduced-motion: reduce)').matches){setAnswer(full);return}let n=0;const id=window.setInterval(()=>{n++;setAnswer(full.slice(0,n));if(n>=full.length)window.clearInterval(id)},16)},d);const end=d+full.length*16+300;later(()=>{const box=document.querySelector('.cl-answer-box') as HTMLElement|null;if(box)void box.offsetWidth;setScan(true)},end);later(()=>{let n=0;const id=window.setInterval(()=>{n++;setReviewed(n);if(n>=3)window.clearInterval(id)},260)},end+500);later(()=>setReviewed(3),end+1280);later(()=>setEvidenceOpen(true),end+1900);later(()=>cycle(false),end+11000)};cycle(true);return()=>{cancelled=true;timers.forEach(window.clearTimeout)}},[]);
 useEffect(()=>{if(!lab)return;setPassedChecks(0);const timers:number[]=[];[0,1,2,3,4,5].forEach(i=>timers.push(window.setTimeout(()=>setPassedChecks(i+1),window.matchMedia('(prefers-reduced-motion: reduce)').matches?0:i*450+400)));return()=>timers.forEach(window.clearTimeout)},[lab]);
 useEffect(()=>{if(!scan)return;const box=document.querySelector('.cl-answer-box') as HTMLElement|null;if(box){void box.offsetWidth}},[scan]);
 useEffect(()=>{const grid=document.querySelector('.cl-module-grid') as HTMLElement|null;if(!grid)return;grid.classList.remove('sh');void grid.offsetWidth;grid.classList.add('sh')},[tab]);
 useEffect(()=>{const move=(e:MouseEvent)=>{const card=(e.target as HTMLElement)?.closest?.('.cl-card') as HTMLElement|null;if(!card)return;const r=card.getBoundingClientRect();card.style.setProperty('--mx',e.clientX-r.left+'px');card.style.setProperty('--my',e.clientY-r.top+'px')};document.addEventListener('mousemove',move);return()=>document.removeEventListener('mousemove',move)},[]);
 useEffect(()=>{const ids=['top','ai-cfo','modules','market-data','how','lab','trust'];const els=ids.map(id=>document.getElementById(id)).filter(Boolean)as HTMLElement[];if(!els.length)return;const ob=new IntersectionObserver(es=>{const v=es.filter(e=>e.isIntersecting).sort((a,b)=>b.intersectionRatio-a.intersectionRatio)[0];if(v)setActive((v.target as HTMLElement).id==='top'?'workspace':(v.target as HTMLElement).id)},{rootMargin:'-20% 0px -60% 0px',threshold:[.15,.35,.6]});els.forEach(e=>ob.observe(e));const reveal=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)(e.target as HTMLElement).classList.add('in')}),{rootMargin:'0px 0px -8% 0px',threshold:.12});document.querySelectorAll('.cl-reveal,.cl-reveal-section').forEach(e=>reveal.observe(e));return()=>{ob.disconnect();reveal.disconnect()}},[]);
 useEffect(()=>{let alive=true;const load=async()=>{try{const [business,general]=await Promise.all([fetchBusinessNews(undefined,'business'),fetchBusinessNews(undefined,'all')]);if(alive){const items=[...normalizeBusinessNews(business),...normalizeBusinessNews(general)];const seen=new Set<string>();setNews(items.filter(x=>{const k=(x.url||x.title).toLowerCase();if(seen.has(k))return false;seen.add(k);return true}).slice(0,12))}}catch{if(alive)setNews([])}};void load();const t=window.setInterval(()=>void load(),45000);return()=>{alive=false;window.clearInterval(t)}},[]);

 const cats=['All',...Array.from(new Set(modules.map(m=>m[3])))],visible=modules.filter(m=>tab==='All'||m[3]===tab),open=(d:AppNavigationDestination)=>onEnter(d);
 const scrollToCfo=()=>document.getElementById('ai-cfo')?.scrollIntoView({behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth',block:'start'});
 const askCfo=(text:string)=>{scrollToCfo();if(text.trim())setCfoPrompt({id:Date.now(),text});};
 return <div ref={rootRef} className="connected-landing">
 <div className="cl-progress" aria-hidden="true"/>
 <header className={'cl-header '+(scrolled?'is-scrolled':'')}><div className="cl-wrap cl-nav">
  <a href="#top" className="cl-brand" aria-label="ArthaMind AI, back to top"><ArthaMindLogo className="cl-logo" compact/><span><b>ARTHAMIND AI</b><small>FINANCIAL INTELLIGENCE</small></span></a>
  <nav className="cl-links" aria-label="Page sections">{NAV_LINKS.map(([id,label])=><a key={id} className={active===id?'on':''} href={'#'+id} aria-current={active===id?'true':undefined}>{label}</a>)}</nav>
  <div className="cl-right"><LanguageSelector compact/>{!signedIn&&<button type="button" className="cl-signin" onClick={onSignIn}>Sign in</button>}<button type="button" className="cl-menu-button" aria-label={menuOpen?'Close menu':'Open menu'} aria-expanded={menuOpen} aria-controls="cl-mobile-menu" onClick={()=>setMenuOpen(v=>!v)}>{menuOpen?<X size={20}/>:<Menu size={20}/>}</button></div>
 </div>
 <div id="cl-mobile-menu" className={'cl-mobile-menu '+(menuOpen?'open':'')} hidden={!menuOpen}><nav aria-label="Page sections">{NAV_LINKS.map(([id,label])=><a key={id} href={'#'+id} onClick={()=>setMenuOpen(false)}>{label}</a>)}</nav></div>
 </header>
 <main id="top">
 <section className="cl-hero"><div className="cl-aurora" aria-hidden="true"><i/><i/><i/></div><div className="cl-wrap cl-hero-grid"><div className="cl-hero-copy"><span className="cl-pill"><i className="cl-pill-dot" aria-hidden="true"/>INDIA'S FIRST AI CFO FOR YOUR MONEY</span><h1 className="cl-hero-title"><span>Meet your</span><span className="cl-grad-text">AI CFO.</span><span className="accent"><RotatingWords words={HERO_WORDS}/></span><span>In plain rupees.</span></h1><p>ArthaMind reads your income, expenses, EMIs and goals, runs verified calculations and answers like a finance chief: tax regime, loans, emergency runway and investments, in English, Hindi or Hinglish.</p><div className="cl-actions"><button className="cl-primary cl-glow" onClick={scrollToCfo}><Sparkles size={16}/>Ask your AI CFO <ArrowRight size={16}/></button><button className="cl-secondary" onClick={()=>open('overview')}>Open Artha Bench Pro <ArrowRight size={16}/></button></div><div className="cl-trust-line"><span>✓ Free health check, no sign-in</span><span>✓ Personal data stays opt-in</span><span>✓ Verified ₹ calculations</span></div></div>
 <div className="cl-workspace-preview"><div className="cl-orbit" aria-hidden="true">{["MARKETS","NEWS","ECONOMICS","FINANCE","AI","EVIDENCE","CALCULATIONS"].map((t,i)=><i key={t} style={{"--i":i,"--x":`${Math.round(Math.cos(i/7*6.283+.4)*(360+(i%2)*80))}px`,"--y":`${Math.round(Math.sin(i/7*6.283+.4)*(360+(i%2)*80)*.6)}px`} as React.CSSProperties}>{t}</i>)}</div><div className="cl-float cl-float-a">● {reviewed||3} sources reviewed</div><div className="cl-float cl-float-b">✓ Verification required</div><div className="cl-window cl-reveal"><div className="cl-window-bar"><span><i/><i/><i/></span><b>Research workspace</b></div><div className="cl-cols"><aside><label>WATCHLIST · SAMPLE</label>{[['NIFTY 50','Index','+0.64%',true],['SENSEX','Market context','+0.42%',true],['S&P 500','Market context','-0.18%',false],['GOLD','Market context','+0.27%',true],['BTC','Crypto','+1.14%',true]].map((x,i)=><button key={x[0]} className={'cl-watch cl-watch-animate '+(i===0?'active':'')} onClick={()=>open(x[0]==='BTC'?'crypto':'markets')}><span><b>{x[0]}</b><small>{x[1]}</small></span><strong className={x[3]?'up':'down'}>{x[3]?'↑':'↓'} {x[2]}</strong></button>)}</aside><section className="cl-market"><label>MARKET RESEARCH</label><h3>BTC/USDT <span>· Binance candles</span></h3><LiveCryptoChart/><small>BTC/USDT candles are loaded from the existing ArthaBench Pro Binance provider path. The chart refreshes every 5 seconds and keeps the source state visible.</small></section><aside className="cl-answer cl-answer-animate"><label>ARTHAMIND RESPONSE</label><div className={`cl-answer-box ${scan?'scan':''}`}><b>What may be driving today's NIFTY movement?</b><p id="ty" className={answer?'cl-ty':''}>{answer}</p></div><div className={`cl-kv ${reviewed<3?'off':''}`}><span>Sources</span><b>{reviewed||3} reviewed</b></div><div className={`cl-kv warn ${reviewed<3?'off':''}`}><span>Verification</span><b>{reviewed>=3?'Required':'Checking'}</b></div><div className={`cl-kv ${reviewed<3?'off':''}`}><span>Personal context</span><b>Off</b></div><div className={`cl-evidence-reveal ${evidenceOpen?'open':''}`}><div>Market data</div><div>Business news</div><div>Structured knowledge</div><div>Calculation</div></div><button className={`cl-inspect ${evidenceOpen?'pulse':''}`} onClick={()=>setEvidenceOpen(v=>!v)}><span>{evidenceOpen?'Hide evidence':'Inspect evidence'}</span><ArrowRight size={13}/></button></aside></div><div className="cl-window-foot"><span><b>Public market context</b> active</span><span><b>Personal context</b> off by default</span><span>● Evidence-first preview</span></div></div></div></div></section>
 <div className="cl-stat-strip"><div className="cl-wrap cl-stats" data-stagger><div><b data-n="15">15</b><span>planning and research modules</span></div><div><b data-n="3">3</b><span>languages for CFO answers: English, Hindi and Hinglish</span></div><div><b>India</b><span>80C, 80D, NPS, PPF and SGB aware</span></div><div><b>Evidence</b><span>first: every answer shows what supports it</span></div></div></div>
 <div className="cl-marquee" aria-label="What the AI CFO covers"><div className="cl-marquee-track">{[...CAPABILITIES,...CAPABILITIES].map((c,i)=><span key={i} aria-hidden={i>=CAPABILITIES.length?true:undefined}><i/>{c}</span>)}</div></div>
 <LandingIntelligenceSection/>
 <LandingAiCfo onEnter={open} externalPrompt={cfoPrompt}/>
 <section className="cl-section cl-reveal-section"><div className="cl-wrap"><div className="cl-eyebrow">One platform</div><h2>Two products. One financial intelligence.</h2><p className="cl-sub">Planning tells you what to do. Research tells you why you can trust it.</p><div className="cl-two" data-stagger><button className="cl-card cl-card-button" onClick={()=>open('overview')}><span className="cl-eyebrow">ArthaMind AI</span><h3>Your personal finance intelligence</h3><p>Built for Indian households and investors. It connects income, loans, investments and goals, then explains what to consider next.</p><ul><li>Goals, tax, loans, retirement and insurance in one view</li><li>Answers in English or Hinglish, backed by numbers</li><li>Real returns after inflation, not just headline gains</li></ul><b>Explore ArthaMind AI <ArrowRight size={14}/></b></button><button className="cl-card cl-card-button" onClick={()=>open('overview')}><span className="cl-eyebrow">Artha Bench Pro</span><h3>The research and reliability workspace</h3><p>Where you learn finance, follow markets, test financial AI answers and see which evidence was used.</p><ul><li>Live markets, business news and economic data</li><li>AI Reliability Lab with transparent checks</li><li>Evidence, sources and calculations you can inspect</li></ul><b>Open Artha Bench Pro <ArrowRight size={14}/></b></button></div></div></section>
 <section id="modules" className="cl-section cl-soft cl-reveal-section"><div className="cl-wrap"><div className="cl-eyebrow">Modules</div><h2>Everything your money needs, in one workspace.</h2><p className="cl-sub">Fifteen modules designed around how Indian households plan, invest, borrow, protect and learn.</p><div className="cl-tabs">{cats.map(c=><button key={c} className={tab===c?'on':''} onClick={()=>setTab(c)}>{c}</button>)}</div><div className="cl-module-grid">{visible.map(m=>{const target:string=m[4];const asks=target.startsWith('ask:');return <button key={m[1]} className={'cl-card cl-module'+(asks?' is-ask':'')} onClick={()=>asks?askCfo(target.slice(4)):open(target as AppNavigationDestination)}><span className="cl-module-icon">{m[0]}</span><h4>{m[1]}</h4><p>{m[2]}</p><b>{asks?'Ask the AI CFO':'Open module'} <ArrowRight size={13}/></b></button>})}</div></div></section>
 <LiveMarketTicker/><CryptoMarketPreview/><BusinessBrief articles={news} tickerArticles={news}/>
 <section id="how" className="cl-section cl-reveal-section"><div className="cl-wrap"><div className="cl-eyebrow">How it works</div><h2>From your numbers to a decision you can inspect.</h2><div className="cl-steps cl-step-animate">{[['1','Bring your details','Enter income, loans, investments and goals. You choose what to share.'],['2','Analyse','Everything is organised in one view using India-specific tax and product rules.'],['3','Inspect','See the sources, evidence and calculations behind every answer.'],['4','Decide','Get plans and next steps in English or Hinglish, then act on your own terms.']].map(s=><div key={s[0]}><span>{s[0]}</span><h4>{s[1]}</h4><p>{s[2]}</p></div>)}</div></div></section>
 <section id="lab" className="cl-section cl-soft cl-reveal-section"><div className="cl-wrap"><div className="cl-eyebrow">AI Reliability Lab</div><h2>Answer. Evaluate. Evidence. Reliability.</h2><p className="cl-sub">Financial AI should be checked, not just believed. The workspace makes visible checks part of the answer.</p><div className="cl-lab"><div className="cl-card cl-question"><small>USER QUESTION</small><h3>What happens to my investment if inflation rises?</h3>{checks.map((c,i)=><div key={c[0]} className={"cl-check "+(i<passedChecks?"on":"")}><span>{c[0]}</span><b>{i<passedChecks&&c[1]?"✓ Pass":i===5&&passedChecks===6?"Needs evidence":"Checking"}</b></div>)}<div className="cl-score"><div className={'cl-score-ring '+(lab?'is-complete':'')}><svg className="cl-score-arc" viewBox="0 0 44 44" aria-hidden="true"><circle cx="22" cy="22" r="19.8" className="cl-score-track"/><circle id="arc" cx="22" cy="22" r="19.8" className="cl-score-progress" pathLength="1" style={{strokeDashoffset:String(scoreRingOffset(Math.min(passedChecks,checks.filter(c=>c[1]).length),SAMPLE_CHECK_COUNT))}}/></svg><span className="cl-score-value">{Math.min(passedChecks,checks.filter(c=>c[1]).length)}<small>of {SAMPLE_CHECK_COUNT}</small></span></div><div><b>checks passed</b><span>sample evaluation</span></div></div><button className="cl-primary cl-small" onClick={()=>setLab(true)}>{lab?'Evaluation complete':'Run sample evaluation'}</button></div><div className="cl-evidence cl-reveal">{[['Market data','Current financial information'],['Economic data','Rates, inflation and macro indicators'],['Structured knowledge','Verified financial concepts'],['Calculation','Deterministic financial computation']].map(x=><div className="cl-card" key={x[0]}><span className="cl-dot"/><div><b>{x[0]}</b><p>{x[1]}</p></div><CheckCircle2 size={17}/></div>)}</div></div></div></section>
 <LandingMarketDashboard/>
 <LandingReviews/>
 <section id="trust" className="cl-section cl-trust cl-reveal-section"><div className="cl-wrap"><div className="cl-eyebrow">Trust & privacy</div><h2>Independent by design.</h2><p className="cl-sub">ArthaMind AI is not a brokerage and does not execute trades. It exists to help you understand, inspect and decide.</p><div className="cl-trust-grid" data-stagger>{[['01','Public tools first','Explore markets, learning and the Reliability Lab before you sign in.'],['02','Personal context is opt-in','Your personal data is off by default and only used when you turn it on.'],['03','Evidence, not opinion','Every answer shows what supports it, so you can verify it yourself.'],['04','Educational scope','Built for education and research. It is not investment advice.']].map(x=><div className="cl-card" key={x[0]}><span className="cl-module-icon">{x[0]}</span><h4>{x[1]}</h4><p>{x[2]}</p></div>)}</div><div className="cl-final"><h2>Your AI CFO is ready.</h2><p>Run a free health check, ask about taxes, EMIs or goals, then take the plan into your private workspace.</p><div className="cl-actions"><button className="cl-primary cl-glow" onClick={scrollToCfo}><Sparkles size={16}/>Ask your AI CFO</button><button className="cl-secondary" onClick={()=>open('overview')}>Open Artha Bench Pro <ArrowRight size={16}/></button><button className="cl-secondary" onClick={()=>open('evaluation-lab')}>Test an AI answer</button></div></div></div></section>
 </main><button type="button" className={'cl-top '+(showTop?'show':'')} aria-label="Back to top" onClick={()=>window.scrollTo({top:0,behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'})}><ArrowUp size={17}/></button><footer className="cl-footer"><div className="cl-wrap"><b>ArthaMind AI × Artha Bench Pro</b><span>India-focused financial intelligence, education and AI reliability. Educational/research use only—not investment, tax, legal or lending advice.</span></div></footer>
 </div>
};