import React,{useEffect,useState}from'react';
import{ArrowRight,CheckCircle2,FlaskConical}from'lucide-react';
import{NavigationDestination}from'../../types';
import{fetchBusinessNews,fetchMarketOverview}from'../../services/learningApi';
import{ArthaMindLogo}from'./ArthaMindLogo';
import{LiveMarketTicker}from'./LiveMarketTicker';
import{CryptoMarketPreview}from'./CryptoMarketPreview';
import{BusinessBrief,normalizeBusinessNews}from'./BusinessBrief';
import{LanguageSelector}from'../LanguageSelector';
import'./connectedLanding.css';

type Props={signedIn:boolean;onEnter:(destination?:NavigationDestination)=>void;onSignIn:()=>void};
const modules=[
 ['SD','Smart Dashboard','Income, expenses, savings rate and EMI burden in one live view.','Plan','dashboard'],
 ['GP','Goal Planner','The monthly SIP each goal needs, adjusted for inflation.','Plan','overview'],
 ['HS','Financial Health Score','A 0 to 100 score with personal tips to improve it.','Plan','financial-health'],
 ['RP','Retirement Planner','The corpus you need, three scenarios and the gap to close.','Plan','overview'],
 ['EC','Education Cost Planner','Future education costs with inflation and the SIP to reach them.','Plan','overview'],
 ['CI','Career Income Projection','Ten-year salary and wealth paths: stay, switch or grow.','Plan','overview'],
 ['NW','Net Worth Tracker','Assets, liabilities and your wealth trajectory over time.','Plan','overview'],
 ['PT','Portfolio Tracker','SIPs, funds, stocks, FDs, PPF and NPS with real returns.','Invest','markets'],
 ['MD','Market Data Dashboard','NIFTY 50, SENSEX, USD/INR and gold from available provider-backed market data.','Invest','markets'],
 ['TX','Tax Optimiser','Old versus new regime and unused 80C, 80D and NPS room.','Tax & Debt','overview'],
 ['EM','EMI & Loan Manager','Amortisation, prepayment simulator and loan comparison.','Tax & Debt','emi-manager'],
 ['IN','Insurance Analyser','Human Life Value, cover gap and protection score.','Protect','overview'],
 ['FA','Family Income Analyser','Dependency ratio and financial stress for each earner.','Protect','overview'],
 ['RR','Financial Risk Radar','Five risk dimensions and three actions to reduce them.','Protect','quick-check'],
 ['AI','AI Financial Advisor','Ask in Hinglish or English and get numbers-backed answers.','AI','evaluation-lab'],
] as const;
const checks=[['Reasoning',true],['Numerical accuracy',true],['Grounding',true],['Risk awareness',true],['Explainability',true],['Evidence',false]] as const;
const LiveCryptoChart:React.FC=()=>{const [candles,setCandles]=useState<{open:number;high:number;low:number;close:number;volume:number}[]>([]);const [interval,setIntervalState]=useState<'1m'|'5m'|'15m'|'1h'|'4h'|'1d'>('1h');const [status,setStatus]=useState('Connecting to Binance…');useEffect(()=>{let alive=true;const load=async()=>{try{const r=await fetch(`/api/crypto/klines?symbol=BTCUSDT&interval=${interval}`);if(!r.ok)throw new Error('unavailable');const d=await r.json();if(!alive)return;setCandles((d.candles||[]).slice(-32));setStatus('Live · Binance Public Market Data')}catch{if(alive)setStatus('Unavailable · provider did not respond')}};void load();const t=window.setInterval(()=>void load(),5000);return()=>{alive=false;window.clearInterval(t)}},[interval]);const data=candles.length?candles:[];if(!data.length)return <div className="cl-chart-box"><div style={{padding:'36px',color:'#94a3b8',fontSize:12}}>{status}</div></div>;const min=Math.min(...data.map(b=>b.low)),max=Math.max(...data.map(b=>b.high)),y=(v:number)=>154-(v-min)/(max-min||1)*120,w=480/data.length;return <div className="cl-chart-box"><div style={{display:'flex',justifyContent:'space-between',alignItems:'center',gap:8,padding:'8px 10px',fontSize:10,color:'#94a3b8'}}><b style={{color:'#0f766e'}}>BTC/USDT</b><span>{status}</span></div><div className="cl-timeframes">{(['1m','5m','15m','1h','4h','1d'] as const).map(t=><button key={t} className={interval===t?'on':''} onClick={()=>setIntervalState(t)}>{t}</button>)}</div><svg viewBox="0 0 520 185" className="cl-chart" role="img" aria-label="Live BTC USDT Binance candlestick chart">{data.map((b,i)=>{const x=10+i*w;const up=b.close>=b.open;return <g key={i} className="cl-candle cl-candle-animate" style={{'--i':i} as React.CSSProperties}><line x1={x} x2={x} y1={y(b.high)} y2={y(b.low)} className={up?'cl-up':'cl-down'}/><rect x={x-w*.28} y={Math.min(y(b.open),y(b.close))} width={Math.max(3,w*.56)} height={Math.max(2,Math.abs(y(b.open)-y(b.close)))} className={up?'cl-up-fill':'cl-down-fill'}/></g>})}</svg></div>};
const SampleChart=()=>{const bars=Array.from({length:30},(_,i)=>{const base=96+Math.sin(i*.55)*8+Math.sin(i*.16)*12;const close=base+Math.sin(i*1.7)*3;const open=base+Math.cos(i*1.2)*3;const high=Math.max(open,close)+2+(i%4);const low=Math.min(open,close)-2-(i%3);return{open,close,high,low}});const min=Math.min(...bars.map(b=>b.low))-3,max=Math.max(...bars.map(b=>b.high))+3;const y=(v:number)=>154-(v-min)/(max-min)*120;const ma=bars.map((b,i)=>{const start=Math.max(0,i-4);const avg=bars.slice(start,i+1).reduce((s,x)=>(s+x.close),0)/(i-start+1);return [8+i*17.2,y(avg)] as const});const maPath=ma.map(([x,yy],i)=>`${i?'L':'M'} ${x} ${yy}`).join(' ');return <svg viewBox="0 0 520 185" className="cl-chart" role="img" aria-label="Illustrative market candlestick chart">{[0,1,2,3].map(i=><line key={i} x1="0" x2="520" y1={18+i*40} y2={18+i*40} className="cl-grid"/>) }<path d={maPath} pathLength="1" className="cl-ma" fill="none" />{bars.map((b,i)=>{const x=8+i*17.2;const up=b.close>=b.open;return <g key={i} className="cl-candle" style={{'--i':i,animationDelay:(i*18+250)+'ms'} as React.CSSProperties}><line x1={x} x2={x} y1={y(b.high)} y2={y(b.low)} className={up?'cl-up':'cl-down'}/><rect x={x-3.8} y={Math.min(y(b.open),y(b.close))} width="7.6" height={Math.max(2,Math.abs(y(b.open)-y(b.close)))} className={up?'cl-up-fill':'cl-down-fill'}/></g>})}</svg>};
export const ConnectedLandingPage:React.FC<Props>=({signedIn,onEnter,onSignIn})=>{
 const[scrolled,setScrolled]=useState(false),[active,setActive]=useState('workspace'),[tab,setTab]=useState('All'),[lab,setLab]=useState(false),[passedChecks,setPassedChecks]=useState(0),[reviewed,setReviewed]=useState(0),[answer,setAnswer]=useState(''),[scan,setScan]=useState(false),[evidenceOpen,setEvidenceOpen]=useState(false),[eco,setEco]=useState<{label:string;value:string;delta:string}[]>([]),[news,setNews]=useState<ReturnType<typeof normalizeBusinessNews>>([]);
 useEffect(()=>{const f=()=>setScrolled(window.scrollY>8);f();addEventListener('scroll',f,{passive:true});return()=>removeEventListener('scroll',f)},[]);
 useEffect(()=>{const full="Context suggests a mix of broad sentiment and sector movement. The answer stays inspectable rather than presenting confidence as correctness.";let cancelled=false;let timers:number[]=[];const later=(fn:()=>void,ms:number)=>{const id=window.setTimeout(fn,ms);timers.push(id)};const cycle=(first:boolean)=>{if(cancelled)return;setReviewed(0);setAnswer('');setScan(false);setEvidenceOpen(false);const d=first?2100:200;later(()=>{if(window.matchMedia('(prefers-reduced-motion: reduce)').matches){setAnswer(full);return}let n=0;const id=window.setInterval(()=>{n++;setAnswer(full.slice(0,n));if(n>=full.length)window.clearInterval(id)},16)},d);const end=d+full.length*16+300;later(()=>{const box=document.querySelector('.cl-answer-box') as HTMLElement|null;if(box)void box.offsetWidth;setScan(true)},end);later(()=>{let n=0;const id=window.setInterval(()=>{n++;setReviewed(n);if(n>=3)window.clearInterval(id)},260)},end+500);later(()=>setReviewed(3),end+1280);later(()=>setEvidenceOpen(true),end+1900);later(()=>cycle(false),end+11000)};cycle(true);return()=>{cancelled=true;timers.forEach(window.clearTimeout)}},[]);
 useEffect(()=>{if(!lab)return;setPassedChecks(0);const timers:number[]=[];[0,1,2,3,4,5].forEach(i=>timers.push(window.setTimeout(()=>setPassedChecks(i+1),window.matchMedia('(prefers-reduced-motion: reduce)').matches?0:i*450+400)));return()=>timers.forEach(window.clearTimeout)},[lab]);
 useEffect(()=>{const reduce=window.matchMedia('(prefers-reduced-motion: reduce)').matches;if(reduce)return;const nodes=Array.from(document.querySelectorAll<HTMLElement>('[data-n]'));const timers=nodes.map(node=>{const target=Number(node.dataset.n||0);let value=0;const start=performance.now();const tick=(now:number)=>{value=Math.min(target,Math.round(target*((now-start)/900)));node.textContent=String(value);if(value<target)requestAnimationFrame(tick)};return requestAnimationFrame(tick)});return()=>timers.forEach(cancelAnimationFrame)},[]);
 useEffect(()=>{if(!scan)return;const box=document.querySelector('.cl-answer-box') as HTMLElement|null;if(box){void box.offsetWidth}},[scan]);
 useEffect(()=>{const grid=document.querySelector('.cl-module-grid') as HTMLElement|null;if(!grid)return;grid.classList.remove('sh');void grid.offsetWidth;grid.classList.add('sh')},[tab]);
 useEffect(()=>{const move=(e:MouseEvent)=>{const card=(e.target as HTMLElement)?.closest?.('.cl-card') as HTMLElement|null;if(!card)return;const r=card.getBoundingClientRect();card.style.setProperty('--mx',e.clientX-r.left+'px');card.style.setProperty('--my',e.clientY-r.top+'px')};document.addEventListener('mousemove',move);return()=>document.removeEventListener('mousemove',move)},[]);
 useEffect(()=>{const ids=['top','modules','how','lab','trust'];const els=ids.map(id=>document.getElementById(id)).filter(Boolean)as HTMLElement[];if(!els.length)return;const ob=new IntersectionObserver(es=>{const v=es.filter(e=>e.isIntersecting).sort((a,b)=>b.intersectionRatio-a.intersectionRatio)[0];if(v)setActive((v.target as HTMLElement).id==='top'?'workspace':(v.target as HTMLElement).id)},{rootMargin:'-20% 0px -60% 0px',threshold:[.15,.35,.6]});els.forEach(e=>ob.observe(e));const reveal=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)(e.target as HTMLElement).classList.add('in')}),{rootMargin:'0px 0px -8% 0px',threshold:.12});document.querySelectorAll('.cl-reveal,.cl-reveal-section').forEach(e=>reveal.observe(e));return()=>{ob.disconnect();reveal.disconnect()}},[]);
 useEffect(()=>{let alive=true;const load=async()=>{try{const [business,general]=await Promise.all([fetchBusinessNews(undefined,'business'),fetchBusinessNews(undefined,'all')]);if(alive){const items=[...normalizeBusinessNews(business),...normalizeBusinessNews(general)];const seen=new Set<string>();setNews(items.filter(x=>{const k=(x.url||x.title).toLowerCase();if(seen.has(k))return false;seen.add(k);return true}).slice(0,12))}}catch{if(alive)setNews([])}};void load();const t=window.setInterval(()=>void load(),45000);return()=>{alive=false;window.clearInterval(t)}},[]);
 useEffect(()=>{let alive=true;fetchMarketOverview(['^NSEI','^BSESN','INR=X','GC=F']).then(q=>{if(!alive)return;const pick=(s:string)=>q.find(x=>x.symbol===s);setEco([['NIFTY 50',pick('^NSEI')],['SENSEX',pick('^BSESN')],['USD / INR',pick('INR=X')],['Gold',pick('GC=F')]].map(([label,x])=>({label:String(label),value:x&&Number.isFinite(Number(x.price))?Number(x.price).toLocaleString('en-IN',{maximumFractionDigits:2}):'',delta:x?((Number(x.changePercent||0)>=0?'+':'')+Number(x.changePercent||0).toFixed(2)+'%'):'Connect data source'})))}).catch(()=>setEco([]));return()=>{alive=false}},[]);
 const cats=['All',...Array.from(new Set(modules.map(m=>m[3])))],visible=modules.filter(m=>tab==='All'||m[3]===tab),open=(d:NavigationDestination)=>onEnter(d);
 return <div className="connected-landing">
 <header className={'cl-header '+(scrolled?'is-scrolled':'')}><div className="cl-wrap cl-nav">
  <a href="#top" className="cl-brand"><ArthaMindLogo className="cl-logo" compact/><span><b>ARTHAMIND AI</b><small>FINANCIAL INTELLIGENCE</small></span></a>
  <nav className="cl-links"><a className={active==='workspace'?'on':''} href="#top">Workspace</a><a className={active==='modules'?'on':''} href="#modules">Modules</a><a className={active==='how'?'on':''} href="#how">How it works</a><a className={active==='lab'?'on':''} href="#lab">Reliability Lab</a><a className={active==='trust'?'on':''} href="#trust">Trust & privacy</a></nav>
  <div className="cl-right"><LanguageSelector compact/>{!signedIn&&<button className="cl-link-button" onClick={onSignIn}>Sign in</button>}<button className="cl-primary cl-small" onClick={()=>open('overview')}>Open Artha Bench Pro <ArrowRight size={14}/></button></div>
 </div></header>
 <main id="top">
 <section className="cl-hero"><div className="cl-wrap cl-hero-grid"><div className="cl-hero-copy"><span className="cl-pill">FINANCIAL INTELLIGENCE YOU CAN INSPECT</span><h1 className="cl-hero-title"><span>Understand</span><span>finance.</span><span className="accent"><em>Test the AI answer.</em></span><span>See what it used.</span></h1><p>ArthaMind AI is the financial intelligence layer. Artha Bench Pro is the workspace where you learn, research markets, inspect evidence and test financial AI.</p><div className="cl-actions"><button className="cl-primary" onClick={()=>open('overview')}>Explore Artha Bench Pro <ArrowRight size={16}/></button><button className="cl-secondary" onClick={()=>open('evaluation-lab')}><FlaskConical size={16}/>Open AI Reliability Lab</button></div><div className="cl-trust-line"><span>✓ Public tools before sign-in</span><span>✓ Personal context stays opt-in</span><span>✓ Educational & research scope</span></div></div>
 <div className="cl-workspace-preview"><div className="cl-orbit" aria-hidden="true">{["MARKETS","NEWS","ECONOMICS","FINANCE","AI","EVIDENCE","CALCULATIONS"].map((t,i)=><i key={t} style={{"--i":i,"--x":`${Math.round(Math.cos(i/7*6.283+.4)*(360+(i%2)*80))}px`,"--y":`${Math.round(Math.sin(i/7*6.283+.4)*(360+(i%2)*80)*.6)}px`} as React.CSSProperties}>{t}</i>)}</div><div className="cl-float cl-float-a">● {reviewed||3} sources reviewed</div><div className="cl-float cl-float-b">✓ Verification required</div><div className="cl-window cl-reveal"><div className="cl-window-bar"><span><i/><i/><i/></span><b>Research workspace</b></div><div className="cl-cols"><aside><label>WATCHLIST</label>{[['NIFTY 50','Index','+0.64%',true],['SENSEX','Market context','+0.42%',true],['S&P 500','Market context','-0.18%',false],['GOLD','Market context','+0.27%',true],['BTC','Crypto','+1.14%',true]].map((x,i)=><button key={x[0]} className={'cl-watch cl-watch-animate '+(i===0?'active':'')} onClick={()=>open(x[0]==='BTC'?'crypto':'markets')}><span><b>{x[0]}</b><small>{x[1]}</small></span><strong className={x[3]?'up':'down'}>{x[3]?'↑':'↓'} {x[2]}</strong></button>)}</aside><section className="cl-market"><label>MARKET RESEARCH</label><h3>NIFTY 50 <span>· sample view</span></h3><div className="cl-timeframes"><button className="on">1D</button><button>1W</button><button>1M</button><button>1Y</button></div><LiveCryptoChart/><small>BTC/USDT candles are loaded from the existing ArthaBench Pro Binance provider path. The chart refreshes every 5 seconds and keeps the source state visible.</small></section><aside className="cl-answer cl-answer-animate"><label>ARTHAMIND RESPONSE</label><div className={`cl-answer-box ${scan?'scan':''}`}><b>What may be driving today's NIFTY movement?</b><p id="ty" className={answer?'cl-ty':''}>{answer}</p></div><div className={`cl-kv ${reviewed<3?'off':''}`}><span>Sources</span><b>{reviewed||3} reviewed</b></div><div className={`cl-kv warn ${reviewed<3?'off':''}`}><span>Verification</span><b>{reviewed>=3?'Required':'Checking'}</b></div><div className={`cl-kv ${reviewed<3?'off':''}`}><span>Personal context</span><b>Off</b></div><div className={`cl-evidence-reveal ${evidenceOpen?'open':''}`}><div>Market data</div><div>Business news</div><div>Structured knowledge</div><div>Calculation</div></div><button className={`cl-inspect ${evidenceOpen?'pulse':''}`} onClick={()=>setEvidenceOpen(v=>!v)}><span>{evidenceOpen?'Hide evidence':'Inspect evidence'}</span><ArrowRight size={13}/></button></aside></div><div className="cl-window-foot"><span><b>Public market context</b> active</span><span><b>Personal context</b> off by default</span><span>● Evidence-first preview</span></div></div></div></div></section>
 <div className="cl-stat-strip"><div className="cl-wrap cl-stats"><div><b data-n="15">0</b><span>planning and research modules</span></div><div><b data-n="3">0</b><span>language options: English, Hindi and Hinglish</span></div><div><b>India</b><span>80C, 80D, NPS, PPF and SGB aware</span></div><div><b>Evidence</b><span>first: every answer shows what supports it</span></div></div></div>
 <section className="cl-section cl-reveal-section"><div className="cl-wrap"><div className="cl-eyebrow">One platform</div><h2>Two products. One financial intelligence.</h2><p className="cl-sub">Planning tells you what to do. Research tells you why you can trust it.</p><div className="cl-two"><button className="cl-card cl-card-button" onClick={()=>open('overview')}><span className="cl-eyebrow">ArthaMind AI</span><h3>Your personal finance intelligence</h3><p>Built for Indian households and investors. It connects income, loans, investments and goals, then explains what to consider next.</p><ul><li>Goals, tax, loans, retirement and insurance in one view</li><li>Answers in English or Hinglish, backed by numbers</li><li>Real returns after inflation, not just headline gains</li></ul><b>Explore ArthaMind AI <ArrowRight size={14}/></b></button><button className="cl-card cl-card-button" onClick={()=>open('overview')}><span className="cl-eyebrow">Artha Bench Pro</span><h3>The research and reliability workspace</h3><p>Where you learn finance, follow markets, test financial AI answers and see which evidence was used.</p><ul><li>Live markets, business news and economic data</li><li>AI Reliability Lab with transparent checks</li><li>Evidence, sources and calculations you can inspect</li></ul><b>Open Artha Bench Pro <ArrowRight size={14}/></b></button></div></div></section>
 <section id="modules" className="cl-section cl-soft cl-reveal-section"><div className="cl-wrap"><div className="cl-eyebrow">Modules</div><h2>Everything your money needs, in one workspace.</h2><p className="cl-sub">Fifteen modules designed around how Indian households plan, invest, borrow, protect and learn.</p><div className="cl-tabs">{cats.map(c=><button key={c} className={tab===c?'on':''} onClick={()=>setTab(c)}>{c}</button>)}</div><div className="cl-module-grid">{visible.map(m=><button key={m[1]} className="cl-card cl-module" onClick={()=>open(m[4])}><span className="cl-module-icon">{m[0]}</span><h4>{m[1]}</h4><p>{m[2]}</p><b>Open module <ArrowRight size={13}/></b></button>)}</div></div></section>
 <LiveMarketTicker/><CryptoMarketPreview/><BusinessBrief articles={news} tickerArticles={news}/>
 <section id="how" className="cl-section cl-reveal-section"><div className="cl-wrap"><div className="cl-eyebrow">How it works</div><h2>From your numbers to a decision you can inspect.</h2><div className="cl-steps cl-step-animate">{[['1','Bring your details','Enter income, loans, investments and goals. You choose what to share.'],['2','Analyse','Everything is organised in one view using India-specific tax and product rules.'],['3','Inspect','See the sources, evidence and calculations behind every answer.'],['4','Decide','Get plans and next steps in English or Hinglish, then act on your own terms.']].map(s=><div key={s[0]}><span>{s[0]}</span><h4>{s[1]}</h4><p>{s[2]}</p></div>)}</div></div></section>
 <section id="lab" className="cl-section cl-soft cl-reveal-section"><div className="cl-wrap"><div className="cl-eyebrow">AI Reliability Lab</div><h2>Answer. Evaluate. Evidence. Reliability.</h2><p className="cl-sub">Financial AI should be checked, not just believed. The workspace makes visible checks part of the answer.</p><div className="cl-lab"><div className="cl-card cl-question"><small>USER QUESTION</small><h3>What happens to my investment if inflation rises?</h3>{checks.map((c,i)=><div key={c[0]} className={"cl-check "+(i<passedChecks?"on":"")}><span>{c[0]}</span><b>{i<passedChecks&&c[1]?"✓ Pass":i===5&&passedChecks===6?"Needs evidence":"Checking"}</b></div>)}<div className="cl-score"><div className={'cl-score-ring '+(lab?'is-complete':'')}><svg className="cl-score-arc" viewBox="0 0 44 44" aria-hidden="true"><circle cx="22" cy="22" r="18" className="cl-score-track"/><circle id="arc" cx="22" cy="22" r="18" className="cl-score-progress" pathLength="1" style={{strokeDashoffset:lab?'0':'1'}}/></svg><span className="cl-score-value">{Math.min(passedChecks,5)}<small>of 6</small></span></div><div><b>checks passed</b><span>sample evaluation</span></div></div><button className="cl-primary cl-small" onClick={()=>setLab(true)}>{lab?'Evaluation complete':'Run sample evaluation'}</button></div><div className="cl-evidence cl-reveal">{[['Market data','Current financial information'],['Economic data','Rates, inflation and macro indicators'],['Structured knowledge','Verified financial concepts'],['Calculation','Deterministic financial computation']].map(x=><div className="cl-card" key={x[0]}><span className="cl-dot"/><div><b>{x[0]}</b><p>{x[1]}</p></div><CheckCircle2 size={17}/></div>)}</div></div></div></section>
 <section className="cl-section cl-reveal-section"><div className="cl-wrap"><div className="cl-eyebrow">Market data dashboard</div><h2>The macro context behind every decision.</h2><p className="cl-sub">Rates, inflation, currency and gold, alongside provider-backed market context.</p><div className="cl-macro">{(eco.length?eco:[{label:'NIFTY 50',value:'',delta:'Connect data source'},{label:'SENSEX',value:'',delta:'Connect data source'},{label:'USD / INR',value:'',delta:'Connect data source'},{label:'Gold',value:'',delta:'Connect data source'}]).map(e=><div className="cl-card" key={e.label}><small>{e.label}</small><strong>{e.value||<span className="cl-skeleton"/>}</strong><span>{e.delta}</span></div>)}</div></div></section>
 <section id="trust" className="cl-section cl-trust cl-reveal-section"><div className="cl-wrap"><div className="cl-eyebrow">Trust & privacy</div><h2>Independent by design.</h2><p className="cl-sub">ArthaMind AI is not a brokerage and does not execute trades. It exists to help you understand, inspect and decide.</p><div className="cl-trust-grid">{[['01','Public tools first','Explore markets, learning and the Reliability Lab before you sign in.'],['02','Personal context is opt-in','Your personal data is off by default and only used when you turn it on.'],['03','Evidence, not opinion','Every answer shows what supports it, so you can verify it yourself.'],['04','Educational scope','Built for education and research. It is not investment advice.']].map(x=><div className="cl-card" key={x[0]}><span className="cl-module-icon">{x[0]}</span><h4>{x[1]}</h4><p>{x[2]}</p></div>)}</div><div className="cl-final"><h2>Open the workspace and inspect it.</h2><p>See financial intelligence with live market context, business news, crypto research and visible reliability checks.</p><div className="cl-actions"><button className="cl-primary" onClick={()=>open('overview')}>Open Artha Bench Pro <ArrowRight size={16}/></button><button className="cl-secondary" onClick={()=>open('evaluation-lab')}>Test an AI answer</button></div></div></div></section>
 </main><footer className="cl-footer"><div className="cl-wrap"><b>ArthaMind AI × Artha Bench Pro</b><span>India-focused financial intelligence, education and AI reliability. Educational/research use only—not investment, tax, legal or lending advice.</span></div></footer>
 </div>
};