import React, { useEffect, useMemo, useState } from 'react';
import { Activity, Clock3 } from 'lucide-react';
import { getCryptoKlines, getCryptoMarkets } from '../../services/cryptoApi';
import type { CryptoCandle, CryptoInterval, CryptoKlinesResponse, CryptoQuote } from '../crypto/cryptoTypes';

type Props = { onOpenCrypto: () => void };
const TIMEFRAMES: Array<{ label: string; interval: CryptoInterval }> = [{ label: '1H', interval: '1h' }, { label: '4H', interval: '4h' }, { label: '1D', interval: '1d' }];
function price(value: number) { return `$${value.toLocaleString('en-US', { maximumFractionDigits: 2 })}`; }
function formatTime(value: string) { const date = new Date(value); return Number.isNaN(date.getTime()) ? 'Time unavailable' : new Intl.DateTimeFormat('en-IN', { day: '2-digit', month: 'short', hour: '2-digit', minute: '2-digit' }).format(date); }
function geometry(candles: CryptoCandle[], width = 760, height = 300) { const left = 8, right = 58, top = 12, bottom = 28; const values = candles.flatMap((c) => [c.high, c.low]); const min = Math.min(...values); const max = Math.max(...values); const pad = Math.max((max - min) * 0.08, 1); const lo = min - pad; const hi = max + pad; const x = (i: number) => left + (i / Math.max(candles.length - 1, 1)) * (width - left - right); const y = (v: number) => top + ((hi - v) / (hi - lo)) * (height - top - bottom); return { left, right, top, bottom, x, y, lo, hi }; }
export const LandingBitcoinCard: React.FC<Props> = ({ onOpenCrypto }) => {
  const [interval, setInterval] = useState<CryptoInterval>('1h'); const [candles, setCandles] = useState<CryptoCandle[]>([]); const [quote, setQuote] = useState<CryptoQuote | null>(null); const [retrievedAt, setRetrievedAt] = useState<string | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState(false); const [hovered, setHovered] = useState<number | null>(null);
  useEffect(() => { let active = true; const controller = new AbortController(); setLoading(true); setError(false); Promise.all([getCryptoKlines('BTCUSDT', interval, controller.signal), getCryptoMarkets(controller.signal)]).then(([history, markets]) => { if (!active) return; const candleResponse = history as CryptoKlinesResponse; const btc = markets.markets.find((item) => item.symbol === 'BTCUSDT') || null; setCandles(candleResponse.candles.slice(-48)); setQuote(btc); setRetrievedAt(candleResponse.retrievedAt || markets.retrievedAt); }).catch(() => { if (active) { setError(true); setCandles([]); } }).finally(() => { if (active) setLoading(false); }); return () => { active = false; controller.abort(); }; }, [interval]);
  const geo = useMemo(() => candles.length ? geometry(candles) : null, [candles]); const latest = candles[candles.length - 1]; const changePositive = (quote?.changePercent ?? 0) >= 0;
  return <section className="mt-5 rounded-2xl border border-white/10 bg-slate-950/80 p-3 shadow-inner" aria-labelledby="landing-btc-title"><div className="flex flex-wrap items-center justify-between gap-3"><div><div className="flex items-center gap-2 text-[8px] font-black uppercase tracking-[.16em] text-teal-300"><Activity className="h-3 w-3" aria-hidden="true"/>Provider-backed crypto context</div><div id="landing-btc-title" className="mt-1 text-sm font-black text-white">BTC/USDT <span className="font-normal text-slate-500">· Binance Public Market Data</span></div></div><div className="flex items-center gap-1 rounded-lg border border-white/10 bg-white/[.04] p-1" role="group" aria-label="Bitcoin timeframe">{TIMEFRAMES.map((item) => <button key={item.interval} type="button" onClick={() => setInterval(item.interval)} className={`rounded-md px-2 py-1 text-[8px] font-bold ${interval === item.interval ? 'bg-teal-400 text-slate-950' : 'text-slate-300 hover:bg-white/[.06]'}`}>{item.label}</button>)}</div></div>
    <div className="mt-3 flex flex-wrap items-end justify-between gap-3"><div><div className="text-lg font-black tabular-nums text-white">{quote ? price(quote.price) : latest ? price(latest.close) : '—'}</div><div className={`mt-1 text-[9px] font-bold ${changePositive ? 'text-emerald-300' : 'text-rose-300'}`}>{quote ? `${changePositive ? '+' : ''}${quote.change.toFixed(2)} · ${changePositive ? '+' : ''}${quote.changePercent.toFixed(2)}%` : 'Provider change unavailable'}</div></div><div className="text-right text-[8px] leading-4 text-slate-400"><div className="inline-flex items-center gap-1"><span className="h-1.5 w-1.5 rounded-full bg-sky-300"/>Provider-backed snapshot</div><div>{retrievedAt ? formatTime(retrievedAt) : 'Timestamp unavailable'}</div></div></div>
    <div className="mt-3 overflow-hidden rounded-xl border border-white/10 bg-[#0b1220]">{loading ? <div className="flex h-44 items-center justify-center text-[10px] text-slate-400">Loading provider OHLC data…</div> : error || !geo ? <div className="flex h-44 flex-col items-center justify-center px-6 text-center text-[10px] text-slate-400"><span className="font-bold text-slate-200">BTC chart unavailable from current provider</span><span className="mt-1">No synthetic candles are shown.</span></div> : <div className="relative h-44 w-full" onMouseLeave={() => setHovered(null)} onMouseMove={(event) => { if (!geo || !candles.length) return; const rect = event.currentTarget.getBoundingClientRect(); const ratio = Math.max(0, Math.min(1, (event.clientX - rect.left) / rect.width)); setHovered(Math.round(ratio * (candles.length - 1))); }}><svg viewBox="0 0 760 300" preserveAspectRatio="none" className="h-full w-full" role="img" aria-label="Provider-backed Bitcoin candlestick chart"><g>{[0,1,2,3].map((i) => <line key={i} x1="8" x2="702" y1={45 + i * 65} y2={45 + i * 65} stroke="rgba(148,163,184,.12)"/>)}</g>{candles.map((c, i) => { const x = geo.x(i); const up = c.close >= c.open; const bodyTop = geo.y(Math.max(c.open, c.close)); const bodyBottom = geo.y(Math.min(c.open, c.close)); const bodyHeight = Math.max(2, bodyBottom - bodyTop); return <g key={c.openTime}><line x1={x} x2={x} y1={geo.y(c.high)} y2={geo.y(c.low)} stroke={up ? '#34d399' : '#fb7185'} strokeWidth="2"/><rect x={x - 4} y={bodyTop} width="8" height={bodyHeight} rx="1" fill={up ? '#34d399' : '#fb7185'}/></g>; })}{hovered !== null && <><line x1={geo.x(hovered)} x2={geo.x(hovered)} y1="12" y2="272" stroke="rgba(125,211,252,.55)" strokeDasharray="4 4"/><circle cx={geo.x(hovered)} cy={geo.y(candles[hovered].close)} r="3.5" fill="#7dd3fc"/></>}<text x="710" y="42" fill="#94a3b8" fontSize="11">{price(geo.hi)}</text><text x="710" y="268" fill="#94a3b8" fontSize="11">{price(geo.lo)}</text></svg>{hovered !== null && candles[hovered] && <div className="absolute left-2 top-2 rounded-lg border border-white/10 bg-slate-950/95 px-2.5 py-2 text-[8px] text-slate-300 shadow-xl"><div className="font-bold text-white">{new Date(candles[hovered].openTime).toLocaleString('en-IN')}</div><div className="mt-1 grid grid-cols-2 gap-x-3 gap-y-0.5"><span>O {price(candles[hovered].open)}</span><span>H {price(candles[hovered].high)}</span><span>L {price(candles[hovered].low)}</span><span>C {price(candles[hovered].close)}</span></div></div>}</div>}</div>
    <div className="mt-2 flex flex-wrap items-center justify-between gap-2 text-[8px] text-slate-500"><span>Educational / market context only · not investment advice</span><span className="inline-flex items-center gap-1"><Clock3 className="h-3 w-3" aria-hidden="true"/>{retrievedAt ? `Updated ${formatTime(retrievedAt)}` : 'Update time unavailable'}</span></div>
    <button type="button" onClick={onOpenCrypto} className="mt-3 w-full rounded-lg border border-teal-400/20 bg-teal-400/[.06] px-3 py-2 text-[9px] font-bold text-teal-200 transition hover:bg-teal-400/[.1] focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-teal-300">Open full Crypto workspace</button>
  </section>;
};
