import React, { useEffect, useMemo, useState } from 'react';
import { ArrowDown, ArrowUp, Clock3 } from 'lucide-react';
import { fetchMarketOverview } from '../../services/learningApi';
import type { NormalizedMarketQuote } from '../../types';

type Instrument = { symbol: string; label: string };
const instruments: Instrument[] = [
  { symbol: 'NIFTY:NSE', label: 'NIFTY 50' },
  { symbol: 'BANKNIFTY:NSE', label: 'BANK NIFTY' },
  { symbol: 'SENSEX:BSE', label: 'SENSEX' },
  { symbol: 'SPY', label: 'S&P 500 ETF' },
  { symbol: 'QQQ', label: 'Nasdaq-100 ETF' },
];
function freshnessLabel(freshness: NormalizedMarketQuote['freshness']) { if (freshness === 'real_time') return 'Live'; if (freshness === 'delayed') return 'Delayed'; if (freshness === 'stale') return 'Stale'; if (freshness === 'end_of_day') return 'End of day'; return 'Unavailable'; }
function formatPrice(quote: NormalizedMarketQuote) { try { return new Intl.NumberFormat(quote.currency === 'INR' ? 'en-IN' : 'en-US', { style: 'currency', currency: quote.currency, maximumFractionDigits: 2 }).format(quote.price); } catch { return `${quote.currency} ${quote.price.toLocaleString(undefined, { maximumFractionDigits: 2 })}`; } }
function formatTime(value: string | null | undefined) { if (!value) return 'Timestamp unavailable'; const date = new Date(value); return Number.isNaN(date.getTime()) ? 'Timestamp unavailable' : new Intl.DateTimeFormat('en-IN', { hour: '2-digit', minute: '2-digit', day: '2-digit', month: 'short' }).format(date); }
export const MarketTicker: React.FC = () => {
  const [quotes, setQuotes] = useState<NormalizedMarketQuote[]>([]); const [loading, setLoading] = useState(true); const [failed, setFailed] = useState(false);
  useEffect(() => { let active = true; setLoading(true); setFailed(false); fetchMarketOverview(instruments.map((item) => item.symbol)).then((next) => { if (!active) return; setQuotes(next.filter((quote) => quote.freshness !== 'demo')); setFailed(next.length === 0); }).catch(() => { if (active) setFailed(true); }).finally(() => { if (active) setLoading(false); }); return () => { active = false; }; }, []);
  const quoteBySymbol = useMemo(() => new Map(quotes.map((quote) => [quote.symbol.toUpperCase(), quote])), [quotes]);
  return <section className="mt-6 overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-[0_10px_30px_rgba(15,23,42,.04)]" aria-label="Provider-backed market context">
    <div className="flex flex-col gap-2 border-b border-slate-100 px-4 py-3 sm:flex-row sm:items-center sm:justify-between"><div><div className="text-[9px] font-black uppercase tracking-[.14em] text-slate-500">Live market context, clearly labelled</div><p className="mt-1 text-[10px] text-slate-500">Provider-backed market movement, source status and freshness—without hiding data limits.</p></div><span className="text-[8px] font-bold uppercase tracking-[.12em] text-slate-400">No synthetic prices</span></div>
    {loading ? <div className="grid min-w-[760px] grid-cols-5 divide-x divide-slate-100" aria-label="Loading market data">{instruments.map((item) => <div key={item.symbol} className="min-h-28 px-4 py-4"><div className="h-3 w-20 animate-pulse rounded bg-slate-100"/><div className="mt-3 h-5 w-24 animate-pulse rounded bg-slate-100"/><div className="mt-3 h-3 w-16 animate-pulse rounded bg-slate-100"/></div>)}</div> : failed ? <div className="px-5 py-8 text-center text-xs text-slate-500">Market quotes are temporarily unavailable. No fallback prices are shown.</div> : <div className="overflow-x-auto"><div className="grid min-w-[760px] grid-cols-5 divide-x divide-slate-100">{instruments.map((item) => { const quote = quoteBySymbol.get(item.symbol.toUpperCase()); if (!quote) return <div key={item.symbol} className="min-h-28 px-4 py-4"><p className="text-xs font-bold text-slate-700">{item.label}</p><p className="mt-2 text-[10px] text-slate-500">Quote temporarily unavailable</p></div>; const change = quote.change ?? 0; const percent = quote.changePercent; const positive = (percent ?? change) >= 0; const status = freshnessLabel(quote.freshness); return <article key={item.symbol} className="min-h-28 px-4 py-3.5"><div className="flex items-start justify-between gap-2"><div><p className="text-xs font-bold text-slate-800">{item.label}</p><p className="mt-0.5 text-[9px] text-slate-400">{quote.symbol}</p></div><span className="rounded-full border border-slate-200 bg-slate-50 px-1.5 py-0.5 text-[8px] font-bold text-slate-500">{status}</span></div><div className="mt-3 flex items-end justify-between gap-2"><p className="text-sm font-black tabular-nums text-slate-900">{formatPrice(quote)}</p><span className={`inline-flex items-center gap-0.5 text-[10px] font-bold tabular-nums ${positive ? 'text-emerald-700' : 'text-rose-700'}`}>{positive ? <ArrowUp className="h-3 w-3" aria-hidden="true"/> : <ArrowDown className="h-3 w-3" aria-hidden="true"/>}{percent === null || percent === undefined ? `${positive ? '+' : ''}${change.toFixed(2)}` : `${positive ? '+' : ''}${percent.toFixed(2)}%`}</span></div><div className="mt-2 flex items-center gap-1 text-[8px] text-slate-400"><Clock3 className="h-3 w-3" aria-hidden="true"/>{quote.providerName || 'Provider'} · {formatTime(quote.providerTimestamp || quote.retrievedAt)}</div></article>; })}</div></div>}
    <div className="border-t border-slate-100 px-4 py-2 text-[8px] leading-4 text-slate-400">Provider freshness is preserved from the existing market-data path. “Live” is shown only when the provider marks the quote real-time; delayed, end-of-day and stale states remain explicit.</div>
  </section>;
};
