import React, { useEffect, useMemo, useState } from 'react';
import { ArrowDown, ArrowUp, Clock3, Newspaper } from 'lucide-react';
import { fetchMarketOverview, fetchBusinessNews } from '../../services/learningApi';
import type { NormalizedMarketQuote, NormalizedNewsItem, NavigationDestination } from '../../types';

type Instrument = { symbol: string; label: string; destination: NavigationDestination };
type Props = { onOpen: (destination: NavigationDestination) => void };
const instruments: Instrument[] = [
  { symbol: 'NIFTY:NSE', label: 'NIFTY 50', destination: 'markets' },
  { symbol: 'BANKNIFTY:NSE', label: 'BANK NIFTY', destination: 'markets' },
  { symbol: 'SENSEX:BSE', label: 'SENSEX', destination: 'markets' },
  { symbol: 'SPY', label: 'S&P 500 ETF', destination: 'markets' },
  { symbol: 'QQQ', label: 'Nasdaq-100 ETF', destination: 'markets' },
];
function freshnessLabel(freshness: NormalizedMarketQuote['freshness']) { if (freshness === 'real_time') return 'Live'; if (freshness === 'delayed') return 'Delayed'; if (freshness === 'stale') return 'Stale'; if (freshness === 'end_of_day') return 'End of day'; return 'Unavailable'; }
function formatPrice(quote: NormalizedMarketQuote) { try { return new Intl.NumberFormat(quote.currency === 'INR' ? 'en-IN' : 'en-US', { style: 'currency', currency: quote.currency, maximumFractionDigits: 2 }).format(quote.price); } catch { return `${quote.currency} ${quote.price.toLocaleString(undefined, { maximumFractionDigits: 2 })}`; } }
function formatTime(value: string | null | undefined) { if (!value) return 'Timestamp unavailable'; const date = new Date(value); return Number.isNaN(date.getTime()) ? 'Timestamp unavailable' : new Intl.DateTimeFormat('en-IN', { hour: '2-digit', minute: '2-digit', day: '2-digit', month: 'short' }).format(date); }
function uniqueNews(items: NormalizedNewsItem[]) { const seenIds = new Set<string>(); const seenUrls = new Set<string>(); const seenTitles = new Set<string>(); return items.filter((item) => { const id = item.id.trim().toLowerCase(); const url = item.sourceUrl.trim().toLowerCase().replace(/#.*$/, ''); const title = item.title.trim().toLowerCase().replace(/[^a-z0-9\s]/g, ' ').replace(/\s+/g, ' '); if (id && seenIds.has(id) || url && seenUrls.has(url) || title && seenTitles.has(title)) return false; if (id) seenIds.add(id); if (url) seenUrls.add(url); if (title) seenTitles.add(title); return true; }).slice(0, 5); }
export const MarketTicker: React.FC<Props> = ({ onOpen }) => {
  const [quotes, setQuotes] = useState<NormalizedMarketQuote[]>([]); const [news, setNews] = useState<NormalizedNewsItem[]>([]); const [loading, setLoading] = useState(true); const [failed, setFailed] = useState(false); const [paused, setPaused] = useState(false); const [reducedMotion, setReducedMotion] = useState(false);
  useEffect(() => { const media = window.matchMedia('(prefers-reduced-motion: reduce)'); const sync = () => setReducedMotion(media.matches); sync(); media.addEventListener?.('change', sync); return () => media.removeEventListener?.('change', sync); }, []);
  useEffect(() => { let active = true; setLoading(true); Promise.allSettled([fetchMarketOverview(instruments.map((item) => item.symbol)), fetchBusinessNews('business')]).then(([marketResult, newsResult]) => { if (!active) return; if (marketResult.status === 'fulfilled') setQuotes(marketResult.value.filter((quote) => quote.freshness !== 'demo')); if (newsResult.status === 'fulfilled') setNews(uniqueNews(newsResult.value)); setFailed(marketResult.status === 'rejected' && newsResult.status === 'rejected'); }).finally(() => { if (active) setLoading(false); }); return () => { active = false; }; }, []);
  const quoteBySymbol = useMemo(() => new Map(quotes.map((quote) => [quote.symbol.toUpperCase(), quote])), [quotes]);
  const trackItems = useMemo(() => instruments.map((item) => ({ item, quote: quoteBySymbol.get(item.symbol.toUpperCase()) })).filter((entry) => entry.quote), [quoteBySymbol]);
  const headline = news[0];
  const movementStyle = reducedMotion || paused ? { animationPlayState: 'paused' as const } : undefined;
  return <section className="mt-6 overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-[0_10px_30px_rgba(15,23,42,.04)]" aria-label="Provider-backed market and business information ticker">
    <style>{`@keyframes arthaLandingTicker{from{transform:translate3d(0,0,0)}to{transform:translate3d(-50%,0,0)}}`}</style>
    <div className="flex items-center justify-between gap-3 border-b border-slate-100 px-4 py-2.5"><div className="flex min-w-0 items-center gap-2"><span className="h-1.5 w-1.5 shrink-0 rounded-full bg-teal-600" aria-hidden="true"/><span className="truncate text-[9px] font-black uppercase tracking-[.14em] text-slate-500">Provider-backed market desk</span></div><span className="hidden text-[8px] font-bold uppercase tracking-[.1em] text-slate-400 sm:inline">Pause on hover / focus</span></div>
    {loading ? <div className="h-14 animate-pulse bg-slate-50" aria-label="Loading market and business data"/> : failed ? <div className="px-5 py-5 text-center text-xs text-slate-500">Provider information is temporarily unavailable. No synthetic prices or headlines are shown.</div> : <div className="overflow-hidden" onMouseEnter={() => setPaused(true)} onMouseLeave={() => setPaused(false)} onTouchStart={() => setPaused(true)} onTouchEnd={() => setPaused(false)} onFocus={() => setPaused(true)} onBlur={() => setPaused(false)}>
      <div className="flex w-max min-w-full" style={{ animation: 'arthaLandingTicker 48s linear infinite', ...movementStyle }}>
        {[0, 1].map((copy) => <div key={copy} className="flex shrink-0 items-center" aria-hidden={copy === 1}>
          {trackItems.map(({ item, quote }) => { if (!quote) return null; const percent = quote.changePercent; const change = quote.change; const hasChange = percent != null || change != null; const positive = (percent ?? change ?? 0) >= 0; const status = freshnessLabel(quote.freshness); const valueLabel = percent != null ? `${positive ? '+' : ''}${percent.toFixed(2)} percent` : change != null ? `${positive ? '+' : ''}${change.toFixed(2)}` : 'Change unavailable'; return <button key={`${copy}-${item.symbol}`} type="button" onClick={() => onOpen(item.destination)} className="group flex min-h-14 items-center gap-3 border-r border-slate-100 px-5 text-left transition hover:bg-slate-50 focus-visible:z-10 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-[-2px] focus-visible:outline-teal-700" aria-label={`${item.label}, ${formatPrice(quote)}, ${valueLabel}, ${status}, ${quote.providerName}`}><span><span className="block text-[10px] font-black text-slate-800">{item.label}</span><span className="mt-0.5 block font-mono text-xs font-black tabular-nums text-slate-900">{formatPrice(quote)}</span></span>{hasChange ? <span className={`inline-flex items-center gap-0.5 font-mono text-[10px] font-bold tabular-nums ${positive ? 'text-emerald-700' : 'text-rose-700'}`}>{positive ? <ArrowUp className="h-3 w-3" aria-hidden="true"/> : <ArrowDown className="h-3 w-3" aria-hidden="true"/>}{percent != null ? `${positive ? '+' : ''}${percent.toFixed(2)}%` : `${positive ? '+' : ''}${change!.toFixed(2)}`}</span> : <span className="text-[9px] font-bold text-slate-400">Unavailable</span>}<span className="hidden rounded-full border border-slate-200 bg-slate-50 px-1.5 py-0.5 text-[8px] font-bold text-slate-500 sm:inline">{status}</span><span className="hidden items-center gap-1 text-[8px] text-slate-400 lg:inline-flex"><Clock3 className="h-3 w-3" aria-hidden="true"/>{quote.providerName} · {formatTime(quote.providerTimestamp || quote.retrievedAt)}</span></button>; })}
          {headline && <button type="button" onClick={() => onOpen('news')} className="group flex min-h-14 max-w-[430px] items-center gap-3 border-r border-slate-100 px-5 text-left transition hover:bg-slate-50 focus-visible:z-10 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-[-2px] focus-visible:outline-teal-700" aria-label={`Business headline: ${headline.title}, ${headline.sourceName}, ${formatTime(headline.publishedAt)}`}><Newspaper className="h-4 w-4 shrink-0 text-teal-700" aria-hidden="true"/><span className="min-w-0"><span className="block truncate text-[9px] font-black uppercase tracking-[.08em] text-teal-700">Business Brief · {headline.sourceName}</span><span className="mt-0.5 block truncate text-xs font-bold text-slate-800">{headline.title}</span><span className="mt-0.5 block text-[8px] text-slate-400">{formatTime(headline.publishedAt)} · provider-backed</span></span></button>}
        </div>)}
      </div>
    </div>}
    <div className="sr-only" aria-label="Static accessible market and news list">{trackItems.map(({ item, quote }) => quote && <a key={item.symbol} href="#markets" onClick={(event) => { event.preventDefault(); onOpen(item.destination); }}>{item.label}: {formatPrice(quote)}, {freshnessLabel(quote.freshness)}, {quote.providerName}, {formatTime(quote.providerTimestamp || quote.retrievedAt)}</a>)}{headline && <button type="button" onClick={() => onOpen('news')}>{headline.title}, {headline.sourceName}, {formatTime(headline.publishedAt)}</button>}</div>
    <div className="border-t border-slate-100 px-4 py-1.5 text-[8px] leading-4 text-slate-400">Freshness and source labels come directly from the existing provider-backed market path. Currency pairs are omitted because no existing FX provider path is exposed for the landing page.</div>
  </section>;
};
