import { loadAiDataContext, type AiDataContextPreferences, updateAiDataContext } from './aiDataContext';

export type SafetyStatus='ready'|'review'|'critical'|'unknown';
export type FreshnessStatus='Live'|'Delayed'|'End-of-day'|'Cached'|'Unavailable'|'Illustrative';
export interface ShieldCheck { id:string; area:'privacy'|'readiness'|'aiTrust'|'dataQuality'; title:string; status:SafetyStatus; explanation:string; inputs:string[]; action?:string; }
export interface SafetyReview { generatedAt:string; checks:ShieldCheck[]; topRisks:string[]; score:number|null; scoreInputs:string[]; limitations:string[]; }
export interface EmergencyMoneyPlan { essentialExpenses:number|null; targetCashBuffer:number|null; savingsGoal:number|null; importantCommitments:string[]; nextActions:string[]; }
export interface FreshnessRecord { source:string; status:FreshnessStatus; updatedAt:string|null; marketStatus?:string; limitation?:string; }
export interface ProviderHealthRecord { provider:string; status:'connected'|'degraded'|'unavailable'|'unknown'; checkedAt:string|null; model?:string; }

const SHIELD_PLAN_KEY='arthabench_artha_shield_emergency_plan_v1';
const SHIELD_PRIVATE_SESSION_KEY='arthabench_artha_shield_private_session_v1';
const SHIELD_VERIFY_CALCS_KEY='arthabench_verify_tutor_calculations_v1';
const SHIELD_PROVIDER_LOG_KEY='arthabench_provider_sharing_log_v1';

export function loadShieldPreferences(){ if(typeof window==='undefined') return {verifyTutorCalculations:false,privateSession:false}; return {verifyTutorCalculations:localStorage.getItem(SHIELD_VERIFY_CALCS_KEY)==='true',privateSession:sessionStorage.getItem(SHIELD_PRIVATE_SESSION_KEY)==='true'}; }
export function setVerifyTutorCalculations(enabled:boolean){ if(typeof window!=='undefined') localStorage.setItem(SHIELD_VERIFY_CALCS_KEY,String(enabled)); }
export function setPrivateSession(enabled:boolean){ if(typeof window==='undefined') return; if(enabled) sessionStorage.setItem(SHIELD_PRIVATE_SESSION_KEY,'true'); else sessionStorage.removeItem(SHIELD_PRIVATE_SESSION_KEY); }
export function clearShieldLocalChat(){ if(typeof window==='undefined') return; for(const key of Object.keys(localStorage)) if(/chat|conversation|ai.*history|history.*ai/i.test(key)) localStorage.removeItem(key); }
export function deleteSavedAiNotes(){ if(typeof window==='undefined') return; for(const key of Object.keys(localStorage)) if(/saved.*ai|ai.*notes|notes.*ai/i.test(key)) localStorage.removeItem(key); }
export function revokeAllAiContext(){ updateAiDataContext({income:false,expenses:false,budgets:false,emis:false,goals:false,paperPortfolio:false,learningProgress:false,personalFinance:false,budgetsAndGoals:false}); }
export function redactSecrets(input:string){ let text=input; const findings:string[]=[]; const rules:[string,RegExp][]=[['OTP',/\b(?:otp|one[- ]time password)\s*[:=\-]?\s*\d{4,8}\b/gi],['API key',/\b(?:api[_ -]?key|access[_ -]?token)\s*[:=]\s*[A-Za-z0-9_\-\.]{12,}\b/gi],['private key',/-----BEGIN [A-Z ]*PRIVATE KEY-----[\s\S]*?-----END [A-Z ]*PRIVATE KEY-----/g],['card number',/\b(?:\d[ -]*?){13,19}\b/g],['password',/\b(?:password|passwd|pwd)\s*[:=]\s*\S+/gi],['bank credential',/\b(?:netbanking|bank login|user id|customer id)\s*[:=]\s*\S+/gi]]; for(const [name,pattern] of rules){if(pattern.test(text)){findings.push(name);text=text.replace(pattern,'[REDACTED SENSITIVE DATA]');}} return {safe:findings.length===0,text,findings}; }
export function recordProviderSharing(provider:string,dataCategory:string,purpose:string,retention:string){ if(typeof window==='undefined') return; const entry={provider,dataCategory,purpose,retention,timestamp:new Date().toISOString()}; const current=JSON.parse(localStorage.getItem(SHIELD_PROVIDER_LOG_KEY)||'[]'); localStorage.setItem(SHIELD_PROVIDER_LOG_KEY,JSON.stringify([entry,...(Array.isArray(current)?current:[])].slice(0,100))); }
export function loadProviderSharingLog(){if(typeof window==='undefined')return[];try{const rows=JSON.parse(localStorage.getItem(SHIELD_PROVIDER_LOG_KEY)||'[]');return Array.isArray(rows)?rows:[];}catch{return[];}}
export function loadEmergencyMoneyPlan():EmergencyMoneyPlan{if(typeof window==='undefined')return {essentialExpenses:null,targetCashBuffer:null,savingsGoal:null,importantCommitments:[],nextActions:[]};try{return JSON.parse(localStorage.getItem(SHIELD_PLAN_KEY)||'{}');}catch{return {essentialExpenses:null,targetCashBuffer:null,savingsGoal:null,importantCommitments:[],nextActions:[]};}}
export function saveEmergencyMoneyPlan(plan:EmergencyMoneyPlan){if(typeof window!=='undefined')localStorage.setItem(SHIELD_PLAN_KEY,JSON.stringify(plan));}

function boolLabel(value:boolean){return value?'Enabled':'Disabled';}
export function runSafetyReview(args:{providerHealth:ProviderHealthRecord[];freshness:FreshnessRecord[];evaluationCompleted:boolean;recordedExpenses:number|null;recurringCommitments:number|null;emiRecords:number|null;budgetCategories:number;emergencyTarget:number|null;goalCoverage:number|null;}) :SafetyReview {
 const permissions=loadAiDataContext(); const checks:ShieldCheck[]=[];
 checks.push({id:'privacy-context',area:'privacy',title:'AI personal-data context',status:Object.values(permissions).some(Boolean)?'ready':'review',explanation:`AI context categories are explicitly ${Object.values(permissions).some(Boolean)?'enabled selectively':'not enabled'}.`,inputs:Object.entries(permissions).filter(([,v])=>v).map(([k])=>k),action:'Review AI data context'});
 checks.push({id:'privacy-retention',area:'privacy',title:'Conversation retention',status:permissions.saveConversation?'review':'ready',explanation:permissions.saveConversation?'Conversation saving is enabled. Review or revoke retention if you do not need it.':'Conversation saving is disabled.',inputs:[`saveConversation=${permissions.saveConversation}`],action:permissions.saveConversation?'Disable conversation saving':undefined});
 const readinessMissing:string[]=[]; if(args.recordedExpenses===null)readinessMissing.push('expense tracking'); if(args.recurringCommitments===null)readinessMissing.push('recurring commitments'); if(args.emiRecords===null)readinessMissing.push('EMI/debt records'); if(args.budgetCategories<1)readinessMissing.push('budget categories'); if(args.emergencyTarget===null)readinessMissing.push('emergency-fund target'); if(args.goalCoverage===null)readinessMissing.push('goal coverage');
 checks.push({id:'readiness',area:'readiness',title:'Financial readiness data',status:readinessMissing.length?'review':'ready',explanation:readinessMissing.length?`Data needed: ${readinessMissing.join(', ')}.`:'Required readiness inputs are present.',inputs:readinessMissing.length?readinessMissing:['recorded financial inputs'],action:readinessMissing.length?'Complete missing readiness data':undefined});
 const providerBad=args.providerHealth.filter(p=>p.status==='unavailable'||p.status==='degraded'); checks.push({id:'ai-provider',area:'aiTrust',title:'AI provider health',status:providerBad.length?'review':'ready',explanation:providerBad.length?'One or more provider checks are degraded or unavailable.':'Available provider health checks are healthy.',inputs:providerBad.map(p=>`${p.provider}:${p.status}`),action:providerBad.length?'Retry provider health check':undefined});
 checks.push({id:'ai-evaluation',area:'aiTrust',title:'Completed evaluation evidence',status:args.evaluationCompleted?'ready':'review',explanation:args.evaluationCompleted?'A completed evaluation result is available.':'No completed verification result was found; answers must not be called verified.',inputs:[`evaluationCompleted=${args.evaluationCompleted}`],action:args.evaluationCompleted?undefined:'Run Evaluation Lab'});
 const stale=args.freshness.filter(f=>f.status==='Unavailable'||f.status==='Cached'||f.status==='Illustrative'||f.status==='Delayed'); checks.push({id:'data-freshness',area:'dataQuality',title:'Market/data freshness',status:stale.length?'review':'ready',explanation:stale.length?'Some displayed data is delayed, cached, illustrative, or unavailable.':'Available freshness records do not report limitations.',inputs:stale.map(f=>`${f.source}:${f.status}`),action:stale.length?'Review source timestamps':undefined});
 const scoreable=checks.length; const score=scoreable?Math.round((checks.filter(c=>c.status==='ready').length/checks.length)*100):null; const topRisks=checks.filter(c=>c.status!=='ready').sort((a,b)=>a.area.localeCompare(b.area)).slice(0,3).map(c=>c.title); return {generatedAt:new Date().toISOString(),checks,topRisks,score,scoreInputs:checks.map(c=>`${c.id}:${c.status}`),limitations:[...readinessMissing.map(item=>`Missing ${item}`),...(args.freshness.filter(f=>f.status==='Unavailable').map(f=>`${f.source} unavailable`))]};
}
export function calculateEmergencyReadiness(essentialExpenses:number|null,targetCashBuffer:number|null){if(essentialExpenses===null||essentialExpenses<=0||targetCashBuffer===null||targetCashBuffer<0)return null;return targetCashBuffer/essentialExpenses;}
