import { callGroqStructuredFinancialAnswer, getGroqModels } from './groqService';
import { callNvidiaNemotron, DEFAULT_NVIDIA_MODEL } from './nvidiaService';
import { StructuredFinancialAnswer } from '../src/types';
import { structuredFinancialAnswerSchema, createFallbackStructuredFinancialAnswer } from './aiResponseStandard';
export type AiTask='education'|'calculation'|'live_data'|'quiz'|'scenario'|'evaluation'|'report'|'general';
export type AiModel='artha'|'nemotron';
export interface AiContext { country?:'India'|'US'|'Global'; currency?:'INR'|'USD'|'EUR'|'GBP'; language?:'english'|'hindi'|'hinglish'; level?:'beginner'|'intermediate'|'advanced'; mode?:'explain'|'quiz'|'calc'; detail?:'short'|'detailed'; useOfficialSources?:boolean; highContrast?:boolean; reducedMotion?:boolean; learningGoal?:string; learningStyle?:'visual'|'practical'|'reading'|'socratic'; activityType?:'lesson'|'quiz'|'calculation'|'scenario'|'flashcards'|'revision'|'mock-test'; quizType?:'mcq'|'mixed'; quizLength?:5|10|20|50; adaptiveDifficulty?:boolean; sessionLength?:15|30|45|60; learnerProfile?:string; }
export interface AiGatewayRequest { prompt:string; requestedModel?:AiModel; task?:AiTask; history?:Array<{role:'user'|'assistant';content:string}>; context?:AiContext; }
const requestId=()=>`ai-${Date.now()}-${Math.random().toString(36).slice(2,9)}`;
function inferTask(prompt:string,ctx:AiContext):AiTask{if(ctx.mode==='quiz'||/quiz|mcq|test me/i.test(prompt))return'quiz';if(ctx.mode==='calc'||/calculate|emi|cagr|ratio|compound interest|budget/i.test(prompt))return'calculation';if(/current|today|latest|price|bitcoin|rbi|news|inflation rate/i.test(prompt))return'live_data';if(/scenario|what if|compare/i.test(prompt))return'scenario';if(/evaluate|benchmark|reliability|citation quality/i.test(prompt))return'evaluation';if(/report/i.test(prompt))return'report';return'education';}
function systemPrompt(task:AiTask,c:AiContext){const language=c.language==='hinglish'?'natural Roman Hindi mixed with simple English':c.language||'english';return `You are ArthaBench, a professional financial educator. Task=${task}. Learner: country=${c.country||'Global'}, currency=${c.currency||'USD'}, language=${language}, level=${c.level||'beginner'}, detail=${c.detail||'detailed'}, goal=${c.learningGoal||'financial literacy'}, style=${c.learningStyle||'practical'}, activity=${c.activityType||'lesson'}, adaptiveDifficulty=${c.adaptiveDifficulty??true}. Never output JSON, raw LaTeX, code or developer/template labels. Never invent current data, sources, dates, regulations or calculations. Use verified data and deterministic calculations as authoritative. Explain results clearly. In quiz mode ask one question at a time. In guided calculation, collect missing inputs before calculating. Avoid personalized buy/sell/hold instructions and guaranteed returns.`;}
function sanitizeText(text:string){return text.replace(/```(?:json|markdown|text)?/gi,'').replace(/```/g,'').replace(/^\s*(JSON|Answer):\s*/i,'').replace(/\\text\{([^}]*)\}/g,'$1').replace(/\\times/g,'×').replace(/\\cdot/g,'·').replace(/\\%/g,'%').replace(/\\#/g,'#').replace(/\\frac\{([^}]*)\}\{([^}]*)\}/g,'($1) / ($2)').replace(/\\\[|\\\]/g,'').trim();}
function presentationFromText(text:string,task:AiTask):StructuredFinancialAnswer{return{title:task==='calculation'?'Verified financial calculation':task==='quiz'?'Financial learning check':'ArthaBench financial explanation',directAnswer:sanitizeText(text),steps:[],formula:{expression:'Shown when relevant.',variables:[],whenToUse:'Use a formula when the question requires a calculation.'},example:{title:'Context applied',dataStatus:'not_applicable',dataAsOf:new Date().toISOString(),inputs:[],calculation:[],result:sanitizeText(text)},interpretation:[],risks:['AI-generated explanations should be verified for consequential decisions.'],keyTakeaways:[],sources:[]};}
export async function runAiGateway(request:AiGatewayRequest){const id=requestId(),started=Date.now(),context=request.context||{},task=request.task||inferTask(request.prompt,context),preferred=request.requestedModel||'artha';const candidates:AiModel[]=preferred==='nemotron'?['nemotron','artha']:['artha','nemotron'];let lastError='No configured AI provider responded.';for(const model of candidates){try{if(model==='nemotron'){if(!process.env.NVIDIA_API_KEY?.trim())throw new Error('NVIDIA is not configured.');const r=await callNvidiaNemotron(request.prompt,request.history,systemPrompt(task,context),DEFAULT_NVIDIA_MODEL);const structured=presentationFromText(r.text,task);return{ok:true,requestId:id,answer:sanitizeText(r.text),structuredAnswer:structured,provider:'NVIDIA NIM',model:r.model,fallbackUsed:model!==preferred,latencyMs:Date.now()-started};}const models=getGroqModels();const raw=await callGroqStructuredFinancialAnswer(systemPrompt(task,context),request.prompt,{modelName:models.tutorModel,history:request.history,fallbackQuestion:request.prompt});const parsed=structuredFinancialAnswerSchema.safeParse(raw);if(!parsed.success)throw new Error('AI structured response failed validation.');return{ok:true,requestId:id,answer:sanitizeText(parsed.data.directAnswer||parsed.data.example?.result||''),structuredAnswer:parsed.data,provider:'Groq',model:models.tutorModel,fallbackUsed:model!==preferred,latencyMs:Date.now()-started};}catch(error){lastError=error instanceof Error?error.message:'Provider request failed.';}}
const fallback=createFallbackStructuredFinancialAnswer(request.prompt,'The live AI providers are temporarily unavailable. A safe educational fallback is being shown instead.');return{ok:false,requestId:id,answer:fallback.directAnswer,structuredAnswer:fallback,provider:'Local fallback',model:'ArthaBench',fallbackUsed:true,latencyMs:Date.now()-started,error:'AI providers temporarily unavailable',sanitizedProviderError:lastError.replace(/Bearer\s+\S+/gi,'Bearer [redacted]')};}
