import { callGroqStructuredFinancialAnswer, getGroqModels } from './groqService';
import { callNvidiaNemotron, DEFAULT_NVIDIA_MODEL } from './nvidiaService';
import { StructuredFinancialAnswer } from '../src/types';
import { structuredFinancialAnswerSchema, createFallbackStructuredFinancialAnswer } from './aiResponseStandard';
import { offlineSnapshot } from './offlineSnapshot';
import { currentGroundingSources, gatherLiveContext, currentWebSearchMode } from './liveGrounding';
export type AiTask='education'|'calculation'|'live_data'|'quiz'|'scenario'|'evaluation'|'report'|'general'|'cfo';
export type AiModel='artha'|'nemotron';
export interface AiContext { country?:'India'|'US'|'Global'; currency?:'INR'|'USD'|'EUR'|'GBP'; language?:'english'|'hindi'|'hinglish'; level?:'beginner'|'intermediate'|'advanced'; mode?:'explain'|'quiz'|'calc'; detail?:'short'|'standard'|'detailed'; useOfficialSources?:boolean; highContrast?:boolean; reducedMotion?:boolean; learningGoal?:string; learningStyle?:'visual'|'practical'|'reading'|'socratic'|'example-first'|'step-by-step'|'challenge-based'|'deep-dive'; activityType?:'lesson'|'quiz'|'calculation'|'scenario'|'flashcards'|'revision'|'mock-test'; quizType?:'mcq'|'mixed'|'true-false'|'fill-blank'|'short-answer'|'scenario'|'calculation'; quizLength?:5|10|20|50; adaptiveDifficulty?:boolean; sessionLength?:2|5|10|15|20|30|45|60; learnerProfile?:string; }
export interface AiGatewayRequest { prompt:string; requestedModel?:AiModel; task?:AiTask; history?:Array<{role:'user'|'assistant';content:string}>; context?:AiContext; }
const requestId=()=>`ai-${Date.now()}-${Math.random().toString(36).slice(2,9)}`;
function inferTask(prompt:string,ctx:AiContext):AiTask{if(ctx.mode==='quiz'||/quiz|mcq|test me/i.test(prompt))return'quiz';if(ctx.mode==='calc'||/calculate|emi|cagr|ratio|compound interest|budget/i.test(prompt))return'calculation';if(/current|today|latest|price|bitcoin|rbi|news|inflation rate/i.test(prompt))return'live_data';if(/scenario|what if|compare/i.test(prompt))return'scenario';if(/evaluate|benchmark|reliability|citation quality/i.test(prompt))return'evaluation';if(/report/i.test(prompt))return'report';return'education';}
/** ArthaMind AI CFO persona: a chief-financial-officer lens for Indian households, freelancers and small businesses. */
export function cfoSystemPrompt(c:AiContext){const language=c.language==='hinglish'?'natural Roman Hindi mixed with simple English':c.language==='hindi'?'simple Hindi (Devanagari)':'clear, warm, plain English';return `You are ArthaMind CFO, a calm, experienced personal finance adviser for Indian households, freelancers and small businesses. Respond in ${language}. Default currency is INR: write every amount in full as ₹ with Indian digit grouping (₹12,00,000, ₹1,20,200, ₹5,000); never abbreviate amounts as k, K, L, lakh, Cr or crore. Think like a CFO: cash flow first, then debt and EMIs, emergency runway and insurance, tax efficiency (old vs new regime, 80C/80D/NPS where relevant), then goals and investments.
Voice: talk to one person, the way a trusted adviser would across the table. Use "you" and short sentences. Explain any jargon in a few words the first time (for example "emergency runway, meaning how many months your savings would last"). Be specific and kind; acknowledge what is already going well before what needs work. Do not use filler or robotic phrases such as "As an AI", "Certainly!", "Great question", "I hope this helps", "delve" or "in today's fast-paced world". No emojis.
Structure every answer as a CFO brief using the JSON fields:
- title: "CFO brief: <topic>" (max 8 words after the colon). For a request containing "PERSONAL CFO PLAN" use exactly "Your personal CFO plan".
- directAnswer: the bottom line in 2-4 plain sentences with the single most important number. Address the person by name if given.
- steps: 3-5 analysis steps, each titled by the lens used (Cash flow, Debt & EMIs, Safety net, Tax, Goal & investing, Risk) with specific ₹ numbers from the user's inputs. For a PERSONAL CFO PLAN use exactly the five lenses Cash flow, Debt & EMIs, Safety net, Tax, Goal & investing, and in Goal & investing give a monthly amount and a simple asset mix suited to the timeline.
- formula: the main formula actually used (for example EMI, savings rate, runway months, SIP future value), or say it is not needed.
- example: a worked calculation with the user's own numbers; mark dataStatus "illustrative" when you assume values and list every assumption in inputs.
- interpretation: what the numbers mean in everyday terms, benchmarked against common Indian rules of thumb (EMI under 40% of take-home, 6 months emergency fund, 20%+ savings rate, term cover about 10-15x annual income when others depend on you, health cover for the family).
- risks: concrete downside risks and what would change the answer.
- keyTakeaways: a prioritised action plan of 3-5 actions, each starting with a verb and including a ₹ amount or % and a timeline. For a PERSONAL CFO PLAN prefix them "Next 30 days:", "Next 60 days:" and "Next 90 days:".
Rules: when numbers verified by the app are given, use them exactly and never recompute them differently. Ask for missing numbers only when an answer is impossible without them, otherwise state assumptions and proceed. Never invent live prices, rates, dates, laws or sources; say when a figure must be checked (current RBI repo rate, tax slabs for the year). Do not give buy/sell/hold instructions for specific securities or promise returns; talk in categories (index funds, debt funds, PPF, FDs). Recommend a SEBI-registered adviser or CA for binding tax, legal or investment decisions.`;}
function systemPrompt(task:AiTask,c:AiContext){if(task==='cfo')return cfoSystemPrompt(c);const language=c.language==='hinglish'?'natural Roman Hindi mixed with simple English':c.language||'english';return `You are ArthaBench, a professional financial educator. Task=${task}. Learner: country=${c.country||'Global'}, currency=${c.currency||'USD'}, language=${language}, level=${c.level||'beginner'}, detail=${c.detail||'detailed'}, goal=${c.learningGoal||'financial literacy'}, style=${c.learningStyle||'practical'}, activity=${c.activityType||'lesson'}, adaptiveDifficulty=${c.adaptiveDifficulty??true}. Never output JSON, raw LaTeX, code or developer/template labels. Never invent current data, sources, dates, regulations or calculations. Use verified data and deterministic calculations as authoritative. Explain results clearly. In quiz mode ask one question at a time. In guided calculation, collect missing inputs before calculating. Avoid personalized buy/sell/hold instructions and guaranteed returns.`;}
function sanitizeText(text:string){return text.replace(/```(?:json|markdown|text)?/gi,'').replace(/```/g,'').replace(/^\s*(JSON|Answer):\s*/i,'').replace(/\\text\{([^}]*)\}/g,'$1').replace(/\\times/g,'×').replace(/\\cdot/g,'·').replace(/\\%/g,'%').replace(/\\#/g,'#').replace(/\\frac\{([^}]*)\}\{([^}]*)\}/g,'($1) / ($2)').replace(/\\\[|\\\]/g,'').trim();}
function presentationFromText(text:string,task:AiTask):StructuredFinancialAnswer{return{title:task==='cfo'?'CFO brief':task==='calculation'?'Verified financial calculation':task==='quiz'?'Financial learning check':'ArthaBench financial explanation',directAnswer:sanitizeText(text),steps:[],formula:{expression:'Shown when relevant.',variables:[],whenToUse:'Use a formula when the question requires a calculation.'},example:{title:'Context applied',dataStatus:'not_applicable',dataAsOf:new Date().toISOString(),inputs:[],calculation:[],result:sanitizeText(text)},interpretation:[],risks:['AI-generated explanations should be verified for consequential decisions.'],keyTakeaways:[],sources:currentGroundingSources().map(({name,dataDate,freshness})=>({name,dataDate,freshness}))};}
export async function runAiGateway(request:AiGatewayRequest){const id=requestId(),started=Date.now(),context=request.context||{},task=request.task||inferTask(request.prompt,context),preferred=request.requestedModel||'artha';const candidates:AiModel[]=preferred==='nemotron'?['nemotron','artha']:['artha','nemotron'];let lastError='No configured AI provider responded.';for(const model of candidates){try{if(model==='nemotron'){if(!process.env.NVIDIA_API_KEY?.trim())throw new Error('NVIDIA is not configured.');const r=await callNvidiaNemotron(request.prompt,request.history,systemPrompt(task,context),DEFAULT_NVIDIA_MODEL);const structured=presentationFromText(r.text,task);return{ok:true,requestId:id,answer:sanitizeText(r.text),structuredAnswer:structured,provider:'NVIDIA NIM',model:r.model,fallbackUsed:model!==preferred,latencyMs:Date.now()-started};}if(!process.env.GROQ_API_KEY?.trim())throw new Error('Groq is not configured.');const models=getGroqModels();const raw=await callGroqStructuredFinancialAnswer(systemPrompt(task,context),request.prompt,{modelName:models.tutorModel,history:request.history,fallbackQuestion:request.prompt});const parsed=structuredFinancialAnswerSchema.safeParse(raw);if(!parsed.success)throw new Error('AI structured response failed validation.');return{ok:true,requestId:id,answer:sanitizeText(parsed.data.directAnswer||parsed.data.example?.result||''),structuredAnswer:parsed.data,provider:'Groq',model:models.tutorModel,fallbackUsed:model!==preferred,latencyMs:Date.now()-started};}catch(error){lastError=error instanceof Error?error.message:'Provider request failed.';}}
const live=await liveFallbackContext(request.prompt);const fallback=createFallbackStructuredFinancialAnswer(request.prompt,live.text?`The AI models are unavailable right now, so here is what the live sources show for your question. Read them directly; nothing below has been interpreted by AI.\n${live.text}`:'The live AI providers are temporarily unavailable. A safe educational fallback is being shown instead.');if(live.sources.length)fallback.sources=live.sources;applyOfflineDetail(fallback,request.prompt,live.text);return{ok:false,requestId:id,answer:fallback.directAnswer,structuredAnswer:fallback,provider:'Local fallback',model:'ArthaBench',fallbackUsed:true,latencyMs:Date.now()-started,error:'AI providers temporarily unavailable',sanitizedProviderError:lastError.replace(/Bearer\s+\S+/gi,'Bearer [redacted]')};}

/** Live facts for an offline answer: the same retrieval the models use, shown as plain lines with sources. */
async function liveFallbackContext(prompt:string){try{const{text,sources}=await gatherLiveContext(prompt,currentWebSearchMode());const lines=text.split('\n').slice(1).filter((l)=>l.trim()).slice(0,14).join('\n');return{text:lines,sources:sources.map(({name,dataDate,freshness})=>({name,dataDate,freshness}))};}catch{return{text:'',sources:[] as Array<{name:string;dataDate:string;freshness:string}>};}}

/** Offline answers keep the user's own arithmetic and every live line, not just the first sentence. */
function applyOfflineDetail(answer:StructuredFinancialAnswer,prompt:string,liveText:string){const snap=offlineSnapshot(prompt);const liveLines=liveText.split('\n').map((l)=>l.replace(/^-\s*/,'').trim()).filter(Boolean);const steps:StructuredFinancialAnswer['steps']=[];if(snap)steps.push({title:'Your numbers (calculated, not AI)',explanation:snap.lines.join(' ')});if(liveLines.length)steps.push({title:'What the live sources and formula book show',explanation:liveLines.join(' · ')});if(!steps.length)return;answer.title=snap?'Your numbers, worked out offline':answer.title;answer.directAnswer=snap?`The AI models are unavailable right now, so here is plain arithmetic on the numbers you gave. ${snap.lines[snap.lines.length>2?2:0]}`:'The AI models are unavailable right now, so here is what the live sources show for your question. Nothing below has been interpreted by AI.';answer.steps=snap?steps:[...steps,...answer.steps].slice(0,5);if(snap?.takeaways.length)answer.keyTakeaways=snap.takeaways;}
