import { Router,Request,Response } from 'express';
import { z } from 'zod';
import { runAiGateway } from './aiGateway';
import { createRateLimiter } from './rateLimiter';
// Public chat endpoints call paid model APIs; cap each IP to protect the provider quota.
const aiChatLimiter=createRateLimiter({windowMs:60_000,max:20,message:'You are sending questions quickly. Please wait a minute and try again.'});
import { calculateEMI,calculateEmergencyFund,calculateBudget503020,calculateSavingsTarget } from './financialCalculations';
export const aiRouter=Router();
// Every context field is optional and falls back to undefined when a client sends a value this server does not know,
// so a newer UI option can never turn a learner's question into a 400.
const context=z.object({country:z.enum(['India','US','Global']).optional().catch(undefined),currency:z.enum(['INR','USD','EUR','GBP']).optional().catch(undefined),language:z.enum(['english','hindi','hinglish']).optional().catch(undefined),replyLanguage:z.string().max(40).optional().catch(undefined),voice:z.boolean().optional().catch(undefined),level:z.enum(['beginner','intermediate','advanced']).optional().catch(undefined),mode:z.enum(['explain','quiz','calc']).optional().catch(undefined),detail:z.enum(['short','standard','detailed']).optional().catch(undefined),useOfficialSources:z.boolean().optional().catch(undefined),highContrast:z.boolean().optional().catch(undefined),reducedMotion:z.boolean().optional().catch(undefined),learningGoal:z.string().max(200).optional().catch(undefined),learningStyle:z.enum(['visual','practical','reading','socratic','example-first','step-by-step','challenge-based','deep-dive']).optional().catch(undefined),activityType:z.enum(['lesson','quiz','calculation','scenario','flashcards','revision','mock-test']).optional().catch(undefined),quizType:z.enum(['mcq','mixed','true-false','fill-blank','short-answer','scenario','calculation']).optional().catch(undefined),quizLength:z.union([z.literal(5),z.literal(10),z.literal(20),z.literal(50)]).optional().catch(undefined),adaptiveDifficulty:z.boolean().optional().catch(undefined),sessionLength:z.union([z.literal(2),z.literal(5),z.literal(10),z.literal(15),z.literal(20),z.literal(30),z.literal(45),z.literal(60)]).optional().catch(undefined),learnerProfile:z.string().max(500).optional().catch(undefined)});
export const requestSchema=z.object({prompt:z.preprocess((value)=>typeof value==='string'?value.trim().slice(0,4000):value,z.string().min(1).max(4000)),model:z.enum(['artha','nemotron']).optional(),task:z.enum(['education','calculation','live_data','quiz','scenario','evaluation','report','general','cfo']).optional(),history:z.preprocess((value)=>Array.isArray(value)?value.filter((turn)=>turn&&(turn.role==='user'||turn.role==='assistant')&&typeof turn.content==='string'&&turn.content.trim()).slice(-10).map((turn)=>({role:turn.role,content:turn.content.slice(0,4000)})):undefined,z.array(z.object({role:z.enum(['user','assistant']),content:z.string().min(1).max(4000)})).max(10).optional()),context:context.optional().catch(undefined)});
const calcSchema=z.object({kind:z.enum(['emi','emergency-fund','budget-503020','savings-target']),principal:z.coerce.number().finite().optional(),annualRatePercent:z.coerce.number().finite().optional(),years:z.coerce.number().finite().optional(),monthlyIncome:z.coerce.number().finite().optional(),monthlyExpenses:z.coerce.number().finite().optional(),targetAmount:z.coerce.number().finite().optional(),months:z.coerce.number().finite().optional()});
function logEvent(event:Record<string,unknown>){console.info(JSON.stringify({scope:'artha-ai',...event}));}
async function handleCentralChat(req:Request,res:Response){const parsed=requestSchema.safeParse({...req.body,prompt:req.body?.prompt||req.body?.userPrompt||req.body?.message||req.body?.query});if(!parsed.success)return res.status(400).json({error:'Please check the tutor request and try again.'});const result=await runAiGateway({prompt:parsed.data.prompt,requestedModel:parsed.data.model,task:parsed.data.task,history:parsed.data.history,context:parsed.data.context});logEvent({requestId:result.requestId,provider:result.provider,model:result.model,fallbackUsed:result.fallbackUsed,latencyMs:result.latencyMs,status:result.ok?'ok':'fallback'});return res.status(200).json({...result,error:result.ok?undefined:'The selected AI model is temporarily unavailable. A safe fallback is being shown.'});}
aiRouter.post('/ai/chat',aiChatLimiter,handleCentralChat);aiRouter.post('/ai/tutor',aiChatLimiter,handleCentralChat);aiRouter.post('/tutor',aiChatLimiter,handleCentralChat);
aiRouter.post('/ai/calculate',async(req:Request,res:Response)=>{const parsed=calcSchema.safeParse(req.body);if(!parsed.success)return res.status(400).json({error:'Please provide valid calculation inputs.'});try{const i=parsed.data;let calculation:unknown;switch(i.kind){case'emi':calculation=calculateEMI(i.principal!,i.annualRatePercent!,i.years!);break;case'emergency-fund':calculation=calculateEmergencyFund(i.monthlyExpenses!,i.months!);break;case'budget-503020':calculation=calculateBudget503020(i.monthlyIncome!);break;case'savings-target':calculation=calculateSavingsTarget(i.targetAmount!,i.months!);break;}return res.json({calculation,engine:'Decimal.js',verificationStatus:'verified',calculatedAt:new Date().toISOString()});}catch(error){return res.status(400).json({error:error instanceof Error?error.message:'Calculation could not be completed.'});}});
