import { Router,Request,Response } from 'express';
import { z } from 'zod';
import { runAiGateway } from './aiGateway';
import { calculateEMI,calculateEmergencyFund,calculateBudget503020,calculateSavingsTarget } from './financialCalculations';
export const aiRouter=Router();
const context=z.object({country:z.enum(['India','US','Global']).optional(),currency:z.enum(['INR','USD','EUR','GBP']).optional(),language:z.enum(['english','hindi','hinglish']).optional(),level:z.enum(['beginner','intermediate','advanced']).optional(),mode:z.enum(['explain','quiz','calc']).optional(),detail:z.enum(['short','detailed']).optional(),useOfficialSources:z.boolean().optional(),highContrast:z.boolean().optional(),reducedMotion:z.boolean().optional(),learningGoal:z.string().max(200).optional(),learningStyle:z.enum(['visual','practical','reading','socratic']).optional(),activityType:z.enum(['lesson','quiz','calculation','scenario','flashcards','revision','mock-test']).optional(),quizType:z.enum(['mcq','mixed']).optional(),quizLength:z.union([z.literal(5),z.literal(10),z.literal(20),z.literal(50)]).optional(),adaptiveDifficulty:z.boolean().optional(),sessionLength:z.union([z.literal(15),z.literal(30),z.literal(45),z.literal(60)]).optional(),learnerProfile:z.string().max(500).optional()});
const requestSchema=z.object({prompt:z.string().trim().min(1).max(4000),model:z.enum(['artha','nemotron']).optional(),task:z.enum(['education','calculation','live_data','quiz','scenario','evaluation','report','general']).optional(),history:z.array(z.object({role:z.enum(['user','assistant']),content:z.string().min(1).max(4000)})).max(10).optional(),context:context.optional()});
const calcSchema=z.object({kind:z.enum(['emi','emergency-fund','budget-503020','savings-target']),principal:z.coerce.number().finite().optional(),annualRatePercent:z.coerce.number().finite().optional(),years:z.coerce.number().finite().optional(),monthlyIncome:z.coerce.number().finite().optional(),monthlyExpenses:z.coerce.number().finite().optional(),targetAmount:z.coerce.number().finite().optional(),months:z.coerce.number().finite().optional()});
function logEvent(event:Record<string,unknown>){console.info(JSON.stringify({scope:'artha-ai',...event}));}
async function handleCentralChat(req:Request,res:Response){const parsed=requestSchema.safeParse({...req.body,prompt:req.body?.prompt||req.body?.userPrompt||req.body?.message||req.body?.query});if(!parsed.success)return res.status(400).json({error:'Please check the tutor request and try again.'});const result=await runAiGateway({prompt:parsed.data.prompt,requestedModel:parsed.data.model,task:parsed.data.task,history:parsed.data.history,context:parsed.data.context});logEvent({requestId:result.requestId,provider:result.provider,model:result.model,fallbackUsed:result.fallbackUsed,latencyMs:result.latencyMs,status:result.ok?'ok':'fallback'});return res.status(200).json({...result,error:result.ok?undefined:'The selected AI model is temporarily unavailable. A safe fallback is being shown.'});}
aiRouter.post('/ai/chat',handleCentralChat);aiRouter.post('/ai/tutor',handleCentralChat);aiRouter.post('/tutor',handleCentralChat);
aiRouter.post('/ai/calculate',async(req:Request,res:Response)=>{const parsed=calcSchema.safeParse(req.body);if(!parsed.success)return res.status(400).json({error:'Please provide valid calculation inputs.'});try{const i=parsed.data;let calculation:unknown;switch(i.kind){case'emi':calculation=calculateEMI(i.principal!,i.annualRatePercent!,i.years!);break;case'emergency-fund':calculation=calculateEmergencyFund(i.monthlyExpenses!,i.months!);break;case'budget-503020':calculation=calculateBudget503020(i.monthlyIncome!);break;case'savings-target':calculation=calculateSavingsTarget(i.targetAmount!,i.months!);break;}return res.json({calculation,engine:'Decimal.js',verificationStatus:'verified',calculatedAt:new Date().toISOString()});}catch(error){return res.status(400).json({error:error instanceof Error?error.message:'Calculation could not be completed.'});}});
