import React,{useState}from'react';
import{ArrowRight,Check,Crown,Database,LockKeyhole,ShieldCheck,Sparkles,X}from'lucide-react';
import{AppNavigationDestination}from'../../navigationTypes';

type Props={onNavigate:(destination:AppNavigationDestination)=>void};
type Status='Available now'|'Requires Pro access'|'Coming soon'|'Requires verified market-data provider'|'Requires a paid/authorised data entitlement';
type Feature={name:string;detail:string;status:Status;destination?:AppNavigationDestination};

const freeFeatures=[
 'Existing Finance Overview and personal-finance workspace',
 'Existing India and US market snapshots where provider data is available',
 'Delayed, end-of-day and reference data with source disclosures',
 'Existing educational AI interactions within configured limits',
 'Existing paper portfolio and learning tools',
 'Existing provider-health and source diagnostics',
];

const proFeatures:Feature[]=[
 {name:'Expanded India Market Explorer',detail:'Search the configured Indian-company registry and inspect provider-backed visible quotes.',status:'Available now',destination:'india-markets'},
 {name:'Intraday Market Lab',detail:'Educational intraday observations are enabled only when the active provider response proves supported intraday data.',status:'Requires verified market-data provider',destination:'intraday-markets'},
 {name:'Forex Intelligence',detail:'Search supported FX pairs, inspect timestamped references, charts and reference conversions.',status:'Available now',destination:'forex-markets'},
 {name:'US Market Explorer',detail:'Expanded US public-market references, professional range charts and source-aware explanations.',status:'Available now',destination:'us-markets'},
 {name:'Advanced Watchlists',detail:'Private saved market preferences using the existing user-state/storage architecture.',status:'Available now',destination:'market-watchlist'},
 {name:'Market Alerts',detail:'User-defined in-app informational conditions. External/background delivery needs real notification infrastructure.',status:'Requires Pro access',destination:'market-alerts'},
 {name:'ArthaMind Market Explainer',detail:'Evidence-linked educational explanations grounded in page-visible provider data and timestamps.',status:'Available now',destination:'markets-learn'},
 {name:'More intraday/streaming timeframes',detail:'Requires a licensed or otherwise authorised provider and eligible data entitlement.',status:'Requires a paid/authorised data entitlement',destination:'intraday-markets'},
 {name:'Exportable market research reports',detail:'Professional saved research exports are planned after entitlement and persistence workflows are finalized.',status:'Coming soon'},
];

const badgeClass=(status:Status)=>status==='Available now'?'border-success-fill/25 bg-success-soft text-success':status==='Coming soon'?'border-line bg-canvas text-secondary':status==='Requires Pro access'?'border-interactive/25 bg-interactive-soft text-interactive':'border-warning-fill/25 bg-warning-soft text-warning';

export const GoProView:React.FC<Props>=({onNavigate})=>{
 const[requestState,setRequestState]=useState<'idle'|'local-demo'>('idle');
 return <div className="mx-auto max-w-[1500px] space-y-6 px-4 py-8 sm:px-6">
  <section className="overflow-hidden rounded-3xl border border-interactive/25 bg-surface shadow-sm"><div className="grid gap-6 p-6 lg:grid-cols-[1.2fr_.8fr] lg:p-9"><div><div className="inline-flex items-center gap-2 rounded-full border border-interactive/25 bg-interactive-soft px-3 py-1 text-[10px] font-black uppercase tracking-[.14em] text-interactive"><Crown className="h-3.5 w-3.5"/>ArthaMind Pro</div><h1 className="mt-4 text-4xl font-black tracking-tight text-ink sm:text-5xl">Advanced market intelligence, without fake entitlements.</h1><p className="mt-4 max-w-3xl text-sm leading-7 text-secondary">ArthaMind Pro helps users inspect market data, understand charts, learn trading and investing concepts, simulate decisions, monitor user-defined alerts, and review evidence-linked market context.</p><div className="mt-6 flex flex-wrap gap-3"><button type="button" onClick={()=>setRequestState('local-demo')} className="inline-flex min-h-11 items-center gap-2 rounded-xl bg-brand px-5 py-3 text-sm font-black text-white focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-interactive"><Sparkles className="h-4 w-4"/>Request Pro Access</button><button type="button" onClick={()=>onNavigate('overview')} className="inline-flex min-h-11 items-center rounded-xl border border-line bg-canvas px-5 py-3 text-sm font-black text-ink focus-visible:outline focus-visible:outline-2 focus-visible:outline-interactive">Continue with Free</button></div></div><div className="rounded-3xl border border-line bg-canvas p-5"><div className="flex items-center gap-2 text-sm font-black text-ink"><LockKeyhole className="h-4 w-4 text-warning"/>Billing status</div><div className="mt-3 rounded-2xl border border-warning-fill/25 bg-warning-soft p-4 text-xs leading-6 text-warning"><strong>Payments are not enabled in this build.</strong><br/>No subscription is activated and no payment information is collected by this page.</div>{requestState==='local-demo'&&<div className="mt-3 rounded-2xl border border-interactive/25 bg-interactive-soft p-4 text-xs leading-6 text-secondary"><strong className="text-ink">Local demo only — your request has not been sent.</strong><br/>A real access-request backend is not configured, so nothing was submitted or stored.</div>}</div></div></section>
  <section className="grid gap-4 lg:grid-cols-2"><Plan title="Free" subtitle="Current access" features={freeFeatures}/><section className="rounded-3xl border border-interactive/25 bg-surface p-5 sm:p-6"><div className="flex items-start justify-between gap-3"><div><div className="text-[10px] font-black uppercase tracking-wider text-interactive">Pro capability map</div><h2 className="mt-1 text-2xl font-black text-ink">ArthaMind Pro</h2></div><Crown className="h-6 w-6 text-interactive"/></div><div className="mt-5 space-y-3">{proFeatures.map(feature=><button key={feature.name} type="button" disabled={!feature.destination} onClick={()=>feature.destination&&onNavigate(feature.destination)} className="w-full rounded-2xl border border-line bg-canvas p-4 text-left transition hover:border-interactive/30 disabled:cursor-default disabled:hover:border-line"><div className="flex flex-wrap items-start justify-between gap-2"><div className="font-black text-ink">{feature.name}</div><span className={`rounded-full border px-2.5 py-1 text-[8px] font-black uppercase tracking-wider ${badgeClass(feature.status)}`}>{feature.status}</span></div><p className="mt-2 text-[10px] leading-5 text-secondary">{feature.detail}</p>{feature.destination&&<div className="mt-2 inline-flex items-center gap-1 text-[9px] font-black text-interactive">Explore feature <ArrowRight className="h-3 w-3"/></div>}</button>)}</div></section></section>
  <section className="grid gap-4 md:grid-cols-3"><Boundary icon={<ShieldCheck className="h-5 w-5"/>} title="Not an advisory service" body="Artha Bench does not offer brokerage, lending, investment execution, or personalised financial advice."/><Boundary icon={<Database className="h-5 w-5"/>} title="Provider truthfulness" body="Premium market capability still depends on actual provider coverage, timestamps, freshness and any required data entitlement."/><Boundary icon={<Crown className="h-5 w-5"/>} title="No fake subscription" body="A Pro badge, preview or roadmap item never means billing or access was successfully activated unless a real backend confirms it."/></section>
  <section className="rounded-3xl border border-line bg-surface p-5 sm:p-6"><h2 className="text-xl font-black text-ink">FAQ & disclosures</h2><div className="mt-4 space-y-3 text-xs leading-6 text-secondary"><p><strong className="text-ink">Can I pay for Pro here?</strong> No. Payments are not enabled in this build.</p><p><strong className="text-ink">Does Pro mean real-time NSE/BSE data?</strong> No. Data state depends on the configured provider and entitlement. Delayed or end-of-day data remains labelled as such.</p><p><strong className="text-ink">Does ArthaMind give trade calls?</strong> No. It explains visible evidence, timestamps, limitations and educational concepts; it does not provide personalised buy/sell/hold calls, targets, stop-loss levels or profit guarantees.</p></div></section>
 </div>;
};

const Plan=({title,subtitle,features}:{title:string;subtitle:string;features:string[]})=><section className="rounded-3xl border border-line bg-surface p-5 sm:p-6"><div className="text-[10px] font-black uppercase tracking-wider text-secondary">{subtitle}</div><h2 className="mt-1 text-2xl font-black text-ink">{title}</h2><div className="mt-5 space-y-3">{features.map(item=><div key={item} className="flex items-start gap-2 text-xs leading-5 text-secondary"><Check className="mt-0.5 h-4 w-4 shrink-0 text-success"/><span>{item}</span></div>)}</div></section>;
const Boundary=({icon,title,body}:{icon:React.ReactNode;title:string;body:string})=><article className="rounded-2xl border border-line bg-canvas p-4"><div className="text-interactive">{icon}</div><h3 className="mt-3 text-sm font-black text-ink">{title}</h3><p className="mt-2 text-[10px] leading-5 text-secondary">{body}</p></article>;
