import React, { useEffect, useState } from 'react';
import { ArrowLeft, ArrowRight, BookOpen, CheckCircle2, ExternalLink, LifeBuoy, LockKeyhole, ShieldCheck } from 'lucide-react';
import { PublicPageId } from '../../appRoutes';
import { ArthaMindLogo } from '../landing/ArthaMindLogo';
import { PageFeedback } from '../common/PageFeedback';

type Props = { page: PublicPageId; onHome: () => void; onWorkspace: () => void };
type Diagnostic = { id: string; name: string; role: string; status: string; lastChecked: string; message?: string };

const card = 'rounded-2xl border border-line bg-surface p-5 shadow-sm';

export const PublicInfoPage: React.FC<Props> = ({ page, onHome, onWorkspace }) => {
  const [diagnostics, setDiagnostics] = useState<Diagnostic[]>([]);
  useEffect(() => { if (page !== 'trust') return; fetch('/api/diagnostics').then((res) => res.ok ? res.json() : Promise.reject()).then((data) => setDiagnostics(Array.isArray(data.diagnostics) ? data.diagnostics : [])).catch(() => setDiagnostics([])); }, [page]);

  return <div className="min-h-screen bg-canvas text-ink"><header className="sticky top-0 z-50 border-b border-line bg-surface/95 backdrop-blur"><div className="mx-auto flex h-16 max-w-6xl items-center justify-between px-4 sm:px-6"><button type="button" onClick={onHome} className="flex items-center gap-3 text-left"><ArthaMindLogo className="h-9 w-9" compact /><div><div className="text-xs font-black tracking-[0.14em]">ARTHAMIND AI</div><div className="text-[9px] text-secondary">Artha Bench Pro</div></div></button><div className="flex gap-2"><button type="button" onClick={onHome} className="rounded-xl border border-line px-3 py-2 text-xs font-bold text-secondary"><ArrowLeft className="mr-1 inline h-3.5 w-3.5" />Home</button><button type="button" onClick={onWorkspace} className="rounded-xl bg-brand px-3 py-2 text-xs font-black text-white">Open workspace <ArrowRight className="ml-1 inline h-3.5 w-3.5" /></button></div></div></header><main className="mx-auto max-w-6xl space-y-6 px-4 py-10 sm:px-6">{page === 'trust' ? <Trust diagnostics={diagnostics} /> : page === 'about' ? <About /> : page === 'methodology-public' ? <Methodology /> : page === 'roadmap' ? <Roadmap /> : page === 'support' ? <Support /> : page === 'changelog' ? <Changelog /> : <Access />}<PageFeedback module={`public-${page}`} /></main></div>;
};

const Heading: React.FC<{ eyebrow: string; title: string; text: string }> = ({ eyebrow, title, text }) => <section className="rounded-3xl border border-line bg-surface p-6 shadow-sm sm:p-8"><div className="text-[10px] font-black uppercase tracking-[0.16em] text-brand">{eyebrow}</div><h1 className="mt-2 text-3xl font-black tracking-tight sm:text-4xl">{title}</h1><p className="mt-3 max-w-3xl text-sm leading-7 text-secondary">{text}</p></section>;

const Trust: React.FC<{ diagnostics: Diagnostic[] }> = ({ diagnostics }) => <>
  <Heading eyebrow="Trust & transparency" title="Trust Centre" text="Plain-language information about what Artha Bench Pro does, what it does not do, how data status is shown, and how personal AI context remains under your control." />
  <div className="grid gap-4 md:grid-cols-2"><section className={card}><ShieldCheck className="h-5 w-5 text-brand" /><h2 className="mt-3 font-black">What Artha Bench does</h2><p className="mt-2 text-xs leading-6 text-secondary">It is an India-focused financial-intelligence, education and AI-reliability workspace for learning, research, personal finance organization and evidence inspection.</p></section><section className={card}><LockKeyhole className="h-5 w-5 text-brand" /><h2 className="mt-3 font-black">What it does not do</h2><p className="mt-2 text-xs leading-6 text-secondary">It is not a broker, lender, credit-score provider, tax/legal adviser or guarantee of financial outcomes. It does not execute trades or approve loans.</p></section></div>
  <section className={card}><h2 className="font-black">Data sources & current provider status</h2><p className="mt-2 text-xs leading-5 text-secondary">Status below comes from the deployment’s diagnostic endpoint. “Connected” is shown only when that provider check reports connected.</p><div className="mt-4 grid gap-2 sm:grid-cols-2">{diagnostics.length ? diagnostics.map((item) => <div key={item.id} className="rounded-xl border border-line bg-canvas p-3"><div className="flex items-start justify-between gap-2"><div className="text-xs font-black text-ink">{item.name}</div><span className="rounded-full border border-line px-2 py-0.5 text-[9px] font-bold text-secondary">{item.status.replaceAll('_',' ')}</span></div><div className="mt-1 text-[9px] text-secondary">{item.role} · checked {item.lastChecked ? new Date(item.lastChecked).toLocaleString() : 'time unavailable'}</div>{item.message && <div className="mt-1 text-[9px] text-secondary">{item.message}</div>}</div>) : <div className="rounded-xl border border-warning-fill/25 bg-warning-soft p-3 text-xs text-secondary">Provider diagnostics are unavailable right now. The product should not infer a “Live” state while this check is unavailable.</div>}</div></section>
  <section className={card}><h2 className="font-black">AI answer boundaries</h2><p className="mt-2 text-xs leading-6 text-secondary">AI answers can be incomplete, wrong or outdated. Personal-finance answers should show their data basis, assumptions, what to verify and data completeness. An accuracy percentage is not used for personal-finance guidance.</p></section>
  <section className={card}><h2 className="font-black">Personal data controls & isolation</h2><p className="mt-2 text-xs leading-6 text-secondary">Signed-in workspace records are stored in user-scoped rows protected by database access policies. AI context categories are opt-in. You can export or delete supported workspace data from Account.</p></section>
  <section className={card}><h2 className="font-black">AI evaluation methodology</h2><p className="mt-2 text-xs leading-6 text-secondary">The Evaluation Lab may calculate documented reliability metrics for benchmarked AI answers. Those evaluation metrics are separate from personal-finance “Data completeness,” which only describes how much user-recorded context was available.</p></section>
</>;

const About = () => <><Heading eyebrow="About" title="About ArthaMind AI × Artha Bench Pro" text="ArthaMind is the financial-intelligence reasoning layer; Artha Bench Pro is the workspace where people can inspect, learn, organize personal finance and test financial AI answers." /><section className={card}><h2 className="font-black">Who it is designed for</h2><p className="mt-2 text-xs leading-6 text-secondary">Students, builders and curious users who want to understand financial concepts and AI outputs with visible context, rather than receive a trading instruction.</p></section><section className={card}><h2 className="font-black">Building in public</h2><p className="mt-2 text-xs leading-6 text-secondary">The product is in beta. Existing modules include financial learning, market/economic research, crypto data, AI evaluation and personal-finance workspaces. Some source integrations and product flows are still being improved and are labelled when unavailable or experimental.</p></section></>;
const Methodology = () => <><Heading eyebrow="Methodology" title="How Artha Bench handles evidence and uncertainty" text="The product separates source status, benchmark reliability checks and personal-data completeness so that one label is not mistaken for another." /><div className="grid gap-4 md:grid-cols-2">{[['AI answer evaluation','Benchmark scenarios can score documented formula, consensus, evidence and safety dimensions where the evaluation engine has a defined ground truth.'],['Source & freshness','Market/provider labels should describe the actual source state such as connected, cached, stale or unavailable and include timestamps where available.'],['Data completeness','Low / Medium / High indicates personal-record coverage used for a response. It is not an accuracy score.'],['Limits','Generated explanations can be wrong or incomplete. Users should verify consequential facts with primary sources or qualified professionals.']].map(([title,text]) => <section key={title} className={card}><h2 className="font-black">{title}</h2><p className="mt-2 text-xs leading-6 text-secondary">{text}</p></section>)}</div></>;
const Roadmap = () => <><Heading eyebrow="Product roadmap" title="Now / Next / Later" text="A direction-of-travel view, not a promise of fixed delivery dates." /><div className="grid gap-4 md:grid-cols-3">{[['Now','Strengthen personal-finance navigation, reports, EMI planning, onboarding and trust controls.'],['Next','Improve source transparency, feedback workflows and authenticated context-history visibility.'],['Later','Expand verified public-data integrations and research workflows only where source quality and maintenance are sustainable.']].map(([title,text]) => <section key={title} className={card}><div className="text-[10px] font-black uppercase text-brand">{title}</div><p className="mt-3 text-xs leading-6 text-secondary">{text}</p></section>)}</div><p className="text-xs text-secondary">Feature request or issue? Use the Support page / public repository issue tracker.</p></>;
const Support = () => <><Heading eyebrow="Support" title="Support & contact" text="Use the public GitHub issue tracker for reproducible bugs, feature requests and documentation issues. Do not include private financial records, credentials or sensitive identity information." /><section className={card}><LifeBuoy className="h-5 w-5 text-brand" /><h2 className="mt-3 font-black">Report an issue</h2><a href="https://github.com/shreyashsinghegi2-oss/artha-bench-pro/issues" target="_blank" rel="noopener noreferrer" className="mt-3 inline-flex items-center gap-1 text-xs font-black text-interactive">Open GitHub issues <ExternalLink className="h-3.5 w-3.5" /></a><div className="mt-5 grid gap-3 sm:grid-cols-2">{[['How is my data handled?','Guest data stays local; supported signed-in workspace data is mirrored into user-scoped cloud rows.'],['Can I delete data?','Account includes export, financial-data deletion and account deletion controls.'],['Are AI answers guaranteed?','No. AI may be wrong, incomplete or outdated.'],['Is this a brokerage?','No. It does not execute trades or provide brokerage services.']].map(([q,a]) => <div key={q} className="rounded-xl border border-line bg-canvas p-3"><div className="text-xs font-black">{q}</div><p className="mt-1 text-[10px] leading-5 text-secondary">{a}</p></div>)}</div></section></>;
const Changelog = () => <><Heading eyebrow="What’s new" title="Changelog" text="Only changes represented by this current beta deployment are listed; no historical releases are invented." /><section className={card}><div className="text-[10px] font-black uppercase text-brand">29 August 2026 · Beta</div><h2 className="mt-2 font-black">Product-coherence upgrade</h2><ul className="mt-3 space-y-2 text-xs leading-5 text-secondary"><li>• Canonical finance navigation and direct URLs.</li><li>• Connected finance overview, reports and EMI planning improvements.</li><li>• First-time onboarding, Trust Centre and clearer data/context controls.</li><li>• Landing-page visual system and reduced-motion improvements.</li></ul><p className="mt-3 text-[10px] text-secondary">Experimental/beta features remain labelled in the product.</p></section></>;
const Access = () => <><Heading eyebrow="Early access / Beta" title="Access & beta scope" text="Artha Bench Pro is currently presented as an educational and research beta. This page describes access honestly instead of showing unimplemented pricing tiers." /><div className="grid gap-4 md:grid-cols-2"><section className={card}><CheckCircle2 className="h-5 w-5 text-success" /><h2 className="mt-3 font-black">Available now</h2><p className="mt-2 text-xs leading-6 text-secondary">Financial AI evaluation, learning, market/economic research, crypto views, personal finance records, reports, EMI tracking and account privacy controls where configured.</p></section><section className={card}><BookOpen className="h-5 w-5 text-warning" /><h2 className="mt-3 font-black">Beta boundaries</h2><p className="mt-2 text-xs leading-6 text-secondary">Some integrations may be unavailable, cached or experimental. The product is educational/research software and does not promise investment, tax, legal or lending outcomes.</p></section></div></>;
