import React from 'react';
import { Calculator, CheckCircle2, Info } from 'lucide-react';

type CalculatorTab = 'compound' | 'quick-ratio' | 'cagr' | 'break-even' | 'dti';

const money = (value: number) => new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD', maximumFractionDigits: 2 }).format(value);
const number = (value: number) => new Intl.NumberFormat('en-US', { maximumFractionDigits: 2 }).format(value);

export const CalculationResultPanel: React.FC<{ activeTab: CalculatorTab; result: Record<string, unknown> }> = ({ activeTab, result }) => {
  const definition = buildDefinition(activeTab, result);
  return (
    <section className="space-y-5 rounded-3xl border border-line bg-surface p-6 shadow-sm" aria-label="Deterministic calculation result">
      <div className="flex flex-col gap-3 border-b border-line pb-4 sm:flex-row sm:items-center sm:justify-between">
        <div><h3 className="flex items-center gap-2 text-sm font-black text-ink"><CheckCircle2 className="h-4 w-4 text-success" /> Deterministic Engine Result</h3><p className="mt-1 text-[10px] text-secondary">Calculated by the existing Decimal.js finance engine, not generated by an AI model.</p></div>
        <span className="inline-flex items-center gap-1.5 self-start rounded-full border border-success-fill/25 bg-success-soft px-3 py-1 text-[10px] font-black uppercase tracking-wider text-success"><Calculator className="h-3.5 w-3.5" /> Verified calculation</span>
      </div>

      <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">
        {definition.metrics.map((metric) => <Metric key={metric.label} label={metric.label} value={metric.value} emphasize={metric.emphasize} />)}
      </div>

      <div className="grid gap-4 lg:grid-cols-[0.8fr_1.2fr]">
        <div className="rounded-2xl border border-interactive/20 bg-interactive-soft/50 p-4"><div className="text-[9px] font-black uppercase tracking-wider text-interactive">Formula / method</div><div className="mt-2 font-mono text-xs font-bold leading-6 text-ink">{definition.formula}</div></div>
        <div className="rounded-2xl border border-line bg-canvas p-4"><div className="flex items-center gap-2 text-[10px] font-black uppercase tracking-wider text-secondary"><Info className="h-3.5 w-3.5" /> Interpretation</div><p className="mt-2 text-xs leading-6 text-ink">{definition.interpretation}</p></div>
      </div>

      <p className="text-[10px] leading-5 text-secondary">This calculator provides deterministic educational calculations from the values entered above. It does not account for lender fees, taxes, changing rates, market conditions, or individual financial circumstances unless those inputs are explicitly part of the calculator.</p>
    </section>
  );
};

function buildDefinition(activeTab: CalculatorTab, result: Record<string, unknown>) {
  const n = (key: string) => Number(result[key] ?? 0);
  if (activeTab === 'compound') {
    return {
      metrics: [
        { label: 'Final balance', value: money(n('finalBalance')), emphasize: true },
        { label: 'Total contributions', value: money(n('totalContributions')) },
        { label: 'Interest earned', value: money(n('totalInterestEarned')), emphasize: true },
        { label: 'Annual rate', value: `${number(n('annualRatePercent'))}%` },
      ],
      formula: 'A = P(1 + r/n)^(nt) + periodic contributions with matching compounding',
      interpretation: `Starting from ${money(n('principal'))}, the configured inputs produce a final balance of ${money(n('finalBalance'))}. Of that total, ${money(n('totalInterestEarned'))} is calculated interest above the recorded contributions.`,
    };
  }
  if (activeTab === 'quick-ratio') {
    return {
      metrics: [
        { label: 'Quick ratio', value: number(n('quickRatio')), emphasize: true },
        { label: 'Cash', value: money(n('cash')) },
        { label: 'Quick assets', value: money(n('cash') + n('marketableSecurities') + n('receivables')) },
        { label: 'Current liabilities', value: money(n('currentLiabilities')) },
      ],
      formula: 'Quick Ratio = (Cash + Marketable Securities + Receivables) / Current Liabilities',
      interpretation: String(result.assessment || 'The quick ratio compares readily available assets with current liabilities.'),
    };
  }
  if (activeTab === 'cagr') {
    return {
      metrics: [
        { label: 'CAGR', value: `${number(n('cagrPercent'))}%`, emphasize: true },
        { label: 'Initial value', value: money(n('initialValue')) },
        { label: 'Final value', value: money(n('finalValue')) },
        { label: 'Period', value: `${number(n('years'))} years` },
      ],
      formula: 'CAGR = (Final Value / Initial Value)^(1 / Years) − 1',
      interpretation: `The start and end values are equivalent to an annualized compound growth rate of ${number(n('cagrPercent'))}% over ${number(n('years'))} years. CAGR smooths the path and does not show year-to-year volatility.`,
    };
  }
  if (activeTab === 'break-even') {
    return {
      metrics: [
        { label: 'Break-even units', value: number(n('breakEvenUnits')), emphasize: true },
        { label: 'Break-even revenue', value: money(n('breakEvenRevenue')), emphasize: true },
        { label: 'Contribution margin', value: money(n('contributionMargin')) },
        { label: 'Fixed costs', value: money(n('fixedCosts')) },
      ],
      formula: 'Break-even Units = Fixed Costs / (Price per Unit − Variable Cost per Unit)',
      interpretation: `At the entered price and variable cost, the contribution margin is ${money(n('contributionMargin'))} per unit. The engine rounds required volume up to ${number(n('breakEvenUnits'))} units, corresponding to ${money(n('breakEvenRevenue'))} of revenue.`,
    };
  }
  return {
    metrics: [
      { label: 'Debt-to-income', value: `${number(n('dtiPercent'))}%`, emphasize: true },
      { label: 'Assessment', value: String(result.healthCategory || '—') },
      { label: 'Monthly gross income', value: money(n('monthlyGrossIncome')) },
      { label: 'Monthly debt payments', value: money(n('monthlyDebtPayments')) },
    ],
    formula: 'DTI = Monthly Debt Payments / Monthly Gross Income × 100',
    interpretation: `The entered monthly debt payments represent ${number(n('dtiPercent'))}% of gross monthly income. The deterministic engine classifies that ratio as “${String(result.healthCategory || 'not classified')}” under this calculator's educational thresholds.`,
  };
}

const Metric: React.FC<{ label: string; value: React.ReactNode; emphasize?: boolean }> = ({ label, value, emphasize }) => (
  <div className="rounded-2xl border border-line bg-canvas p-4"><div className="text-[9px] font-black uppercase tracking-wider text-secondary">{label}</div><div className={`mt-1 break-words text-lg font-black ${emphasize ? 'text-success' : 'text-ink'}`}>{value}</div></div>
);
