import React, { useEffect, useMemo, useRef, useState } from 'react';
import { ArrowRight, BookOpen, Calculator, CheckCircle2, Clock3, Compass, History, LockKeyhole, Search, Sparkles, Target, TrendingUp, X } from 'lucide-react';
import { type AppNavigationDestination } from '../navigationTypes';
import { contextGuidance, createArthaPilotHandoff, detectArthaPilotIntent, readArthaPilotContext, ARTHA_PILOT_RECENT_KEY, type ArthaPilotHandoff } from '../services/arthaPilotRouter';
import { loadAiDataContext } from '../services/aiDataContext';
interface ArthaPilotProps { open:boolean; onClose:()=>void; onNavigate:(destination:AppNavigationDestination)=>void; }
const ACTIONS=[['Plan my money','Build a budget, review income and expenses, or set a goal.','budgeting',Calculator],['Learn with me','Start a lesson, quiz, revision, or flashcard session.','tutor',BookOpen],['Verify this','Check an AI answer or claim with the evaluation workflow.','evaluation-lab',CheckCircle2],['See my future','Explore what-if outcomes with Ripple Twin or Decision Replay.','financial-twin',Target],['Explore markets','Open source-backed market, crypto, news, or economic data.','markets',TrendingUp],['Continue where I left off','Return to your latest workspace activity.','overview',Clock3]] as const;
const PROMPTS=['Make a budget from my monthly income','Explain SIP in Hindi','Calculate my EMI in INR','Quiz me on budgeting','Explain why NIFTY moved today','Check this financial answer','What should I complete first?','Show what changes if I save ₹5,000 every month'];
const destinationLabels:Record<string,string>={budgeting:'Budgeting',tutor:'Financial Tutor','evaluation-lab':'Evaluation Lab','financial-twin':'Ripple Twin','decision-replay':'Decision Replay',markets:'Market Data',crypto:'Crypto',news:'Business News',economy:'Economic Data','emi-manager':'EMI Manager',overview:'Overview'};
function recentHandoffs():ArthaPilotHandoff[]{try{const raw=JSON.parse(localStorage.getItem(ARTHA_PILOT_RECENT_KEY)||'[]');return Array.isArray(raw)?raw.slice(0,6):[];}catch{return[];}}
function savedPlans():string[]{try{const raw=JSON.parse(localStorage.getItem('arthabench_artha_pilot_saved_plans_v1')||'[]');return Array.isArray(raw)?raw.slice(0,6):[];}catch{return[];}}
export const ArthaPilot:React.FC<ArthaPilotProps>=({open,onClose,onNavigate})=>{
 const[request,setRequest]=useState('');const[busy,setBusy]=useState(false);const[status,setStatus]=useState('');const[handoff,setHandoff]=useState<ArthaPilotHandoff|null>(null);const[recent,setRecent]=useState<ArthaPilotHandoff[]>([]);const[saved,setSaved]=useState<string[]>([]);const[showAdvanced,setShowAdvanced]=useState(false);const[showWhy,setShowWhy]=useState(false);const inputRef=useRef<HTMLInputElement>(null);const context=useMemo(()=>readArthaPilotContext(),[open]);const permissions=loadAiDataContext();
 useEffect(()=>{if(!open)return;setRecent(recentHandoffs());setSaved(savedPlans());window.setTimeout(()=>inputRef.current?.focus(),80);},[open]);
 useEffect(()=>{if(!open)return;const key=(event:KeyboardEvent)=>{if(event.key==='Escape')onClose();};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key);},[open,onClose]);
 if(!open)return null;
 const newSession=()=>{setRequest('');setStatus('');setHandoff(null);setBusy(false);setShowWhy(false);window.setTimeout(()=>inputRef.current?.focus(),30);};
 const savePlan=()=>{const text=request.trim();if(!text){setStatus('Enter a plan or request before saving it.');return;}const next=[text,...saved.filter(item=>item!==text)].slice(0,6);localStorage.setItem('arthabench_artha_pilot_saved_plans_v1',JSON.stringify(next));setSaved(next);setStatus('Saved this plan in ArthaPilot.');setShowAdvanced(true);};
 const openRoute=(destination:AppNavigationDestination,text:string)=>{setBusy(true);setStatus('Opening '+(destinationLabels[destination]||'workspace'));const created=createArthaPilotHandoff(text||`Open ${destinationLabels[destination]||destination}`);setHandoff(created);window.setTimeout(()=>{onNavigate(destination);onClose();setBusy(false);},280);};
 const submit=(text=request)=>{const trimmed=text.trim();if(!trimmed)return;const route=detectArthaPilotIntent(trimmed);const guidance=contextGuidance(route,context);if(!route.destination){setStatus(route.clarification||'Choose an available action.');return;}if(guidance&&route.intent==='future'&&!permissions.goals){setStatus(guidance);setShowAdvanced(true);return;}openRoute(route.destination,trimmed);};
 const recommendation=!permissions.expenses?'Add expenses first to make your money plan personal.':!permissions.learningProgress?'A short learning diagnostic can help choose your next lesson.':'Your next action can be chosen from the command centre.';
 return <div className="fixed inset-0 z-[120] flex bg-black/35 backdrop-blur-[2px]" role="dialog" aria-modal="true" aria-label="ArthaPilot command centre"><button type="button" aria-label="Close ArthaPilot" onClick={onClose} className="absolute inset-0 cursor-default"/><section className="relative ml-auto flex h-full w-full max-w-[920px] flex-col overflow-hidden border-l border-line bg-canvas shadow-2xl" aria-label="ArthaPilot workspace">
  <header className="flex items-center justify-between border-b border-line bg-surface px-5 py-4 sm:px-7"><div className="flex items-center gap-3"><div className="flex h-9 w-9 items-center justify-center rounded-xl bg-interactive-soft text-interactive"><Sparkles className="h-5 w-5"/></div><div><div className="text-sm font-black text-ink">✦ ArthaPilot</div><div className="text-[11px] text-secondary">Financial command centre</div></div></div><div className="flex items-center gap-2"><button type="button" onClick={newSession} className="hidden rounded-xl border border-line bg-surface px-3 py-2 text-xs font-bold text-secondary hover:text-ink sm:inline-flex">New session</button><button type="button" onClick={()=>setShowAdvanced(v=>!v)} className="hidden rounded-xl border border-line bg-surface px-3 py-2 text-xs font-bold text-secondary hover:text-ink sm:inline-flex" aria-expanded={showAdvanced}>Privacy & context</button><button type="button" onClick={onClose} className="rounded-xl border border-line bg-surface p-2 text-secondary hover:text-ink" aria-label="Close ArthaPilot"><X className="h-5 w-5"/></button></div></header>
  <div className="min-h-0 flex-1 overflow-y-auto px-5 py-7 sm:px-8">{handoff&&busy?<div className="mx-auto flex min-h-[60vh] max-w-xl flex-col items-center justify-center text-center"><div className="mb-5 flex h-14 w-14 items-center justify-center rounded-2xl bg-interactive-soft text-interactive"><Sparkles className="h-7 w-7 animate-pulse"/></div><h2 className="text-xl font-black text-ink">{status}</h2><p className="mt-2 text-sm text-secondary">Your request and context are being carried into the workspace.</p></div>:<>
   <div className="mx-auto max-w-3xl"><p className="mb-2 text-[11px] font-black uppercase tracking-[0.16em] text-interactive">One command, the right workspace</p><h1 className="text-3xl font-black tracking-tight text-ink sm:text-4xl">What would you like to understand, plan, learn, or verify?</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-secondary">ArthaPilot routes you to an existing ArthaBench Pro workflow. It does not replace the calculators, learning engine, market data, or evaluation tools.</p><div className="mt-6 rounded-2xl border border-line bg-surface p-2 shadow-sm"><div className="flex items-center gap-2"><Search className="ml-2 h-5 w-5 shrink-0 text-secondary"/><input ref={inputRef} value={request} onChange={e=>setRequest(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')submit();}} className="min-w-0 flex-1 bg-transparent px-1 py-3 text-sm text-ink outline-none placeholder:text-secondary" placeholder="Tell ArthaPilot what you need…" aria-label="ArthaPilot command"/><button type="button" onClick={()=>submit()} disabled={!request.trim()} className="inline-flex items-center gap-2 rounded-xl bg-interactive px-4 py-2.5 text-xs font-black text-white disabled:cursor-not-allowed disabled:opacity-40">Open <ArrowRight className="h-4 w-4"/></button></div></div>{status&&!busy&&<div className="mt-3 rounded-xl border border-warning-fill/30 bg-warning-fill/10 px-4 py-3 text-xs font-semibold text-warning" role="status">{status}</div>}<div className="mt-3 flex flex-wrap gap-2">{PROMPTS.map(prompt=><button key={prompt} type="button" onClick={()=>{setRequest(prompt);submit(prompt);}} className="rounded-full border border-line bg-surface px-3 py-2 text-xs font-semibold text-secondary transition hover:border-interactive/40 hover:bg-interactive-soft hover:text-interactive">{prompt}</button>)}</div></div>
   <div className="mx-auto mt-8 grid max-w-3xl gap-3 sm:grid-cols-2">{ACTIONS.map(([title,desc,dest,Icon])=><button key={title} type="button" onClick={()=>openRoute(dest,title)} className="group rounded-2xl border border-line bg-surface p-4 text-left shadow-sm transition hover:-translate-y-0.5 hover:border-interactive/40 hover:shadow-md focus-visible:outline focus-visible:outline-2 focus-visible:outline-interactive"><div className="flex items-start justify-between"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-subtle text-ink"><Icon className="h-5 w-5"/></span><ArrowRight className="h-4 w-4 text-secondary transition group-hover:translate-x-0.5 group-hover:text-interactive"/></div><div className="mt-4 text-sm font-black text-ink">{title}</div><div className="mt-1 text-xs leading-5 text-secondary">{desc}</div></button>)}</div>
   <div className="mx-auto mt-8 grid max-w-3xl gap-4 lg:grid-cols-[1.2fr_.8fr]"><div className="rounded-2xl border border-line bg-surface p-4"><div className="flex items-center gap-2 text-xs font-black text-ink"><Compass className="h-4 w-4 text-interactive"/>Context-aware next step</div><p className="mt-2 text-xs leading-5 text-secondary">{recommendation}</p><button type="button" onClick={()=>setShowWhy(v=>!v)} className="mt-3 text-xs font-bold text-interactive hover:underline" aria-expanded={showWhy}>Why this recommendation?</button>{showWhy&&<div className="mt-2 rounded-xl bg-subtle p-3 text-xs leading-5 text-secondary">This suggestion is based only on the permission state ArthaPilot can see. It does not assume missing transactions, goals, EMIs, or learning records.</div>}<div className="mt-3 flex flex-wrap gap-2 text-[10px] font-bold text-secondary"><span className="rounded-full bg-subtle px-2 py-1">Language: {context.language}</span><span className="rounded-full bg-subtle px-2 py-1">Country: {context.country}</span><span className="rounded-full bg-subtle px-2 py-1">Currency: {context.currency}</span><span className="rounded-full bg-subtle px-2 py-1">Level: {context.learnerLevel}</span><span className="rounded-full bg-subtle px-2 py-1">Detail: {context.detail}</span></div></div><div className="rounded-2xl border border-line bg-surface p-4"><div className="flex items-center gap-2 text-xs font-black text-ink"><LockKeyhole className="h-4 w-4 text-interactive"/>Personal data</div><p className="mt-2 text-xs leading-5 text-secondary">Personal records are used only for categories you explicitly enable.</p><div className="mt-3 grid grid-cols-2 gap-2 text-[10px] font-bold text-secondary">{[['Income',permissions.income],['Expenses',permissions.expenses],['Budgets',permissions.budgets],['EMIs',permissions.emis],['Goals',permissions.goals],['Learning',permissions.learningProgress]].map(([name,enabled])=><span key={String(name)} className={`rounded-lg border px-2 py-1.5 ${enabled?'border-success-fill/20 bg-success-fill/10 text-success':'border-line bg-subtle'}`}>{name}: {enabled?'On':'Off'}</span>)}</div></div></div>
   {showAdvanced&&<div className="mx-auto mt-4 max-w-3xl rounded-2xl border border-line bg-surface p-4"><div className="flex flex-wrap items-center justify-between gap-2"><div className="text-xs font-black text-ink">Privacy, recent actions & saved plans</div><button type="button" onClick={savePlan} className="rounded-lg border border-interactive/30 bg-interactive-soft px-2.5 py-1.5 text-[10px] font-black text-interactive">Save current plan</button></div><p className="mt-1 text-xs text-secondary">ArthaPilot never invents account records. Enable the relevant personal context in Account before asking it to use existing records.</p><div className="mt-4 flex items-center gap-2 text-xs font-black text-ink"><History className="h-4 w-4 text-interactive"/>Recent actions</div>{recent.length===0?<p className="mt-2 text-xs text-secondary">No ArthaPilot actions yet.</p>:<div className="mt-2 space-y-2">{recent.map((item,index)=><button key={`${item.createdAt}-${index}`} type="button" onClick={()=>submit(item.request)} className="flex w-full items-center justify-between rounded-xl border border-line px-3 py-2 text-left text-xs hover:border-interactive/30"><span className="truncate text-ink">{item.request}</span><span className="ml-3 shrink-0 text-secondary">{destinationLabels[item.destination]||item.destination}</span></button>)}</div>}<div className="mt-4 flex items-center gap-2 text-xs font-black text-ink"><Target className="h-4 w-4 text-interactive"/>Saved plans</div>{saved.length===0?<p className="mt-2 text-xs text-secondary">No saved plans yet.</p>:<div className="mt-2 space-y-2">{saved.map(item=><button key={item} type="button" onClick={()=>{setRequest(item);submit(item);}} className="block w-full truncate rounded-xl border border-line px-3 py-2 text-left text-xs text-ink hover:border-interactive/30">{item}</button>)}</div>}</div>}
  </>}</div><footer className="border-t border-line bg-surface px-5 py-3 text-[10px] text-secondary sm:px-7"><span className="font-bold text-ink">Truthful by design:</span> money calculations use deterministic engines; current market answers use source-backed data and timestamps; unsupported requests fall back instead of inventing records.</footer></section></div>;
};
