import React,{useMemo,useState}from'react';
import{AlertTriangle,BarChart3,Bell,CheckCircle2,Crown,DollarSign,ExternalLink,GraduationCap,Landmark,RefreshCw,Send,ShieldCheck,Sparkles,Star,Timer}from'lucide-react';
import{AppNavigationDestination}from'../../navigationTypes';
import{pathForDestination}from'../../appRoutes';
import{askMarketExplainer,type EvidenceReference,type MarketAssistantResponse}from'../../services/marketAssistantApi';
import{marketDataState}from'../../services/marketPro';
import type{NormalizedMarketQuote}from'../../types';

export const MARKET_PRO_DESTINATIONS:Array<{id:AppNavigationDestination;label:string;icon:React.ComponentType<{className?:string}>}>=[
 {id:'india-markets',label:'India',icon:Landmark},{id:'intraday-markets',label:'Intraday',icon:Timer},{id:'forex-markets',label:'Forex',icon:DollarSign},{id:'us-markets',label:'US',icon:BarChart3},{id:'market-watchlist',label:'Watchlist',icon:Star},{id:'market-alerts',label:'Alerts',icon:Bell},{id:'markets-learn',label:'Learn',icon:GraduationCap},{id:'go-pro',label:'ArthaMind Pro',icon:Crown},
];

export const MarketProNavigation:React.FC<{current:AppNavigationDestination;onNavigate:(destination:AppNavigationDestination)=>void}>=({current,onNavigate})=><nav aria-label="ArthaMind Pro market navigation" className="sticky top-[65px] z-30 border-b border-line bg-canvas/95 px-4 py-2 backdrop-blur sm:px-6"><div className="mx-auto flex max-w-[1600px] gap-1.5 overflow-x-auto scrollbar-thin">{MARKET_PRO_DESTINATIONS.map(({id,label,icon:Icon})=><a key={id} href={pathForDestination(id)} onClick={event=>{if(event.button!==0||event.metaKey||event.ctrlKey||event.shiftKey||event.altKey)return;event.preventDefault();onNavigate(id);}} aria-current={current===id?'page':undefined} className={`inline-flex shrink-0 items-center gap-2 rounded-xl border px-3 py-2 text-xs font-bold focus-visible:outline focus-visible:outline-2 focus-visible:outline-interactive ${current===id?'border-interactive/30 bg-interactive-soft text-interactive':'border-transparent text-secondary hover:border-line hover:bg-surface hover:text-ink'}`}><Icon className="h-3.5 w-3.5"/>{label}</a>)}</div></nav>;

export const MarketDataBadge:React.FC<{quote?:NormalizedMarketQuote|null;stateOverride?:ReturnType<typeof marketDataState>['state']}>=({quote,stateOverride})=>{const computed=marketDataState(quote);const state=stateOverride||computed.state;const label=stateOverride?stateLabel(state):computed.label;const cls=state==='live_verified'||state==='recently_refreshed'?'border-success-fill/25 bg-success-soft text-success':state==='delayed'||state==='end_of_day'||state==='cached'?'border-warning-fill/25 bg-warning-soft text-warning':state==='stale'?'border-danger/20 bg-danger-soft text-danger':'border-line bg-canvas text-secondary';return <span className={`inline-flex items-center gap-1 rounded-full border px-2.5 py-1 text-[9px] font-black ${cls}`}>{state==='live_verified'||state==='recently_refreshed'?<CheckCircle2 className="h-3 w-3"/>:state==='delayed'||state==='end_of_day'||state==='cached'||state==='stale'?<AlertTriangle className="h-3 w-3"/>:<ShieldCheck className="h-3 w-3"/>}{label}</span>;};

function stateLabel(state:string){return state==='live_verified'?'Live verified feed':state==='recently_refreshed'?'Recently refreshed':state==='delayed'?'Delayed quote':state==='end_of_day'?'End-of-day reference':state==='cached'?'Cached reference':state==='stale'?'Stale data':state==='demo'?'Demo data':'Unavailable';}

export const MarketPageHeader:React.FC<{eyebrow:string;title:string;description:string;children?:React.ReactNode}>=({eyebrow,title,description,children})=><section className="rounded-3xl border border-line bg-surface p-5 shadow-sm sm:p-7"><div className="flex flex-col gap-4 lg:flex-row lg:items-start lg:justify-between"><div><div className="text-[10px] font-black uppercase tracking-[.15em] text-interactive">{eyebrow}</div><h1 className="mt-2 text-3xl font-black text-ink sm:text-4xl">{title}</h1><p className="mt-2 max-w-4xl text-sm leading-6 text-secondary">{description}</p></div>{children}</div></section>;

export const MarketSourcePanel:React.FC<{quote?:NormalizedMarketQuote|null;extra?:string;stateOverride?:ReturnType<typeof marketDataState>['state'];reason?:string}>=({quote,extra,stateOverride,reason})=>{const computed=marketDataState(quote);const state=stateOverride||computed.state;return <div className="rounded-2xl border border-line bg-canvas p-3 text-[10px] leading-5 text-secondary"><div className="flex flex-wrap items-center gap-2"><ShieldCheck className="h-3.5 w-3.5 text-success"/><strong className="text-ink">Source & freshness</strong><MarketDataBadge quote={quote} stateOverride={stateOverride}/></div><div className="mt-2">Provider: {quote?.providerName||'No verified provider response'} · Symbol: {quote?.symbol||'Unavailable'} · Exchange: {quote?.exchange||'Provider-defined / unavailable'}</div><div>Quote timestamp: {quote?.providerTimestamp?formatTime(quote.providerTimestamp):'Unavailable'} · Retrieved: {quote?.retrievedAt?formatTime(quote.retrievedAt):'Unavailable'}</div><div>Data state: {stateLabel(state)}. {reason||extra||'Review the source timestamp before interpreting the value.'}</div></div>;};

function formatTime(value:string){const parsed=new Date(value);return Number.isNaN(parsed.getTime())?value:parsed.toLocaleString('en-IN');}

function deriveEvidence(visibleData:unknown,sourceLabels:string[]):EvidenceReference[]{
 const data=visibleData&&typeof visibleData==='object'?visibleData as Record<string,unknown>:{};
 const quote=data.quote&&typeof data.quote==='object'?data.quote as Record<string,unknown>:null;
 const evidence:EvidenceReference[]=[];
 if(quote&&typeof quote.providerName==='string'){
  const value=typeof quote.price==='number'&&Number.isFinite(quote.price)?`${typeof quote.currency==='string'?quote.currency:''} ${quote.price}`.trim():undefined;
  evidence.push({id:'visible-market-quote',label:'Visible market quote',sourceType:'market_quote',providerName:quote.providerName,timestamp:typeof quote.providerTimestamp==='string'?quote.providerTimestamp:undefined,retrievedAt:typeof quote.retrievedAt==='string'?quote.retrievedAt:undefined,freshnessState:typeof quote.freshness==='string'?quote.freshness:undefined,valueSummary:value});
 }
 const history=data.historySummary&&typeof data.historySummary==='object'?data.historySummary as Record<string,unknown>:data.chart&&typeof data.chart==='object'?data.chart as Record<string,unknown>:null;
 if(history){
  const observations=typeof history.observations==='number'?history.observations:typeof history.pointCount==='number'?history.pointCount:null;
  if(observations&&observations>0)evidence.push({id:'visible-market-history',label:'Visible chart/history summary',sourceType:'market_history',providerName:quote&&typeof quote.providerName==='string'?quote.providerName:sourceLabels[0],timestamp:quote&&typeof quote.providerTimestamp==='string'?quote.providerTimestamp:undefined,retrievedAt:quote&&typeof quote.retrievedAt==='string'?quote.retrievedAt:undefined,freshnessState:quote&&typeof quote.freshness==='string'?quote.freshness:undefined,valueSummary:`${observations} verified visible observation${observations===1?'':'s'}`});
 }
 if(!evidence.length&&sourceLabels.some(Boolean))evidence.push({id:'visible-provider-status',label:'Visible provider/data status',sourceType:'provider_status',providerName:sourceLabels.filter(Boolean).join(' · '),valueSummary:'No verified numeric market evidence was supplied for this request.'});
 return evidence;
}

function coverage(response:MarketAssistantResponse){if(!response.evidence.length)return'Unavailable';if(response.evidence.some(item=>!item.timestamp&&!item.retrievedAt))return'Partial';return response.status==='success'?'Complete':'Limited';}

const EvidenceCard:React.FC<{item:EvidenceReference}>=({item})=><article className="rounded-xl border border-line bg-canvas p-3"><div className="flex flex-wrap items-start justify-between gap-2"><div><div className="text-[10px] font-black text-ink">{item.label}</div><div className="mt-1 text-[9px] text-secondary">{item.providerName||'Provider unavailable'} · {item.freshnessState?stateLabel(item.freshnessState):'Freshness unavailable'}</div></div>{item.sourceUrl&&<a className="inline-flex items-center gap-1 text-[9px] font-black text-interactive" href={item.sourceUrl} target="_blank" rel="noreferrer">Source <ExternalLink className="h-3 w-3"/></a>}</div>{item.valueSummary&&<div className="mt-2 text-[10px] font-bold text-ink">{item.valueSummary}</div>}<div className="mt-2 text-[8px] leading-4 text-secondary">Source time: {item.timestamp?formatTime(item.timestamp):'Unavailable'} · Retrieved: {item.retrievedAt?formatTime(item.retrievedAt):'Unavailable'}</div></article>;

export const ArthaMindMarketExplainer:React.FC<{page:string;visibleData:unknown;sourceLabels:string[];suggestions:string[];evidence?:EvidenceReference[]}>=({page,visibleData,sourceLabels,suggestions,evidence})=>{
 const[question,setQuestion]=useState('');const[response,setResponse]=useState<MarketAssistantResponse|null>(null);const[busy,setBusy]=useState(false);const[error,setError]=useState<string|null>(null);
 const context=useMemo(()=>visibleData,[visibleData]);const verifiedEvidence=useMemo(()=>evidence||deriveEvidence(context,sourceLabels),[evidence,context,sourceLabels]);
 const ask=async(prompt?:string)=>{const q=(prompt??question).trim();if(!q||busy)return;setError(null);setQuestion('');setBusy(true);try{const next=await askMarketExplainer({question:q,page,visibleData:context,evidence:verifiedEvidence});setResponse(next);}catch{setError('ArthaMind Market Explainer is unavailable right now. Verified page data remains visible; no substitute explanation was generated.');}finally{setBusy(false);}};
 return <section className="overflow-hidden rounded-3xl border border-interactive/20 bg-surface shadow-sm"><div className="p-5 sm:p-6"><div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div className="flex items-start gap-3"><div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-interactive-soft text-interactive"><Sparkles className="h-5 w-5"/></div><div><div className="text-[10px] font-black uppercase tracking-[.14em] text-interactive">Evidence-grounded educational analysis</div><h2 className="mt-1 text-xl font-black text-ink">ArthaMind Market Explainer</h2><p className="mt-1 text-xs leading-5 text-secondary">Uses only page-visible provider data and evidence records. Missing evidence stays missing.</p></div></div>{response&&<span className="rounded-full border border-line bg-canvas px-3 py-1.5 text-[9px] font-black text-secondary">Evidence coverage: {coverage(response)}</span>}</div><div className="mt-4 flex flex-wrap gap-2">{suggestions.map(item=><button key={item} type="button" onClick={()=>void ask(item)} className="rounded-xl border border-line bg-canvas px-3 py-2 text-left text-[10px] font-bold text-secondary hover:border-interactive/30 hover:text-ink">{item}</button>)}</div>
 {response&&<div className="mt-5 space-y-4"><div className={`rounded-2xl border p-4 text-xs leading-6 ${response.status==='success'?'border-success-fill/20 bg-success-soft text-ink':response.status==='safety_redirect'?'border-warning-fill/25 bg-warning-soft text-warning':'border-line bg-canvas text-ink'}`}><div className="text-[9px] font-black uppercase tracking-wider">Status: {response.status.replaceAll('_',' ')}</div><p className="mt-2">{response.answer}</p></div>{response.sections.length>0&&<div className="grid gap-3 lg:grid-cols-2">{response.sections.map(section=><article key={section.title} className="rounded-2xl border border-line bg-canvas p-4"><h3 className="text-xs font-black text-ink">{section.title}</h3><p className="mt-2 whitespace-pre-wrap text-[10px] leading-5 text-secondary">{section.content}</p></article>)}</div>}<div><div className="text-[10px] font-black uppercase tracking-wider text-secondary">Evidence / references</div>{response.evidence.length?<div className="mt-2 grid gap-2 md:grid-cols-2">{response.evidence.map(item=><EvidenceCard key={item.id} item={item}/>)}</div>:<div className="mt-2 rounded-xl border border-dashed border-line p-4 text-[10px] text-secondary">No verified evidence is available for this request. ArthaMind cannot provide a data-grounded explanation until a supported source is available.</div>}</div>{response.limitations.length>0&&<div className="rounded-2xl border border-warning-fill/20 bg-warning-soft p-4"><div className="text-[10px] font-black text-warning">Limitations</div><ul className="mt-2 space-y-1 text-[10px] leading-5 text-secondary">{response.limitations.map(item=><li key={item}>• {item}</li>)}</ul></div>}<div className="text-[8px] text-secondary">Generated {formatTime(response.generatedAt)} · Request {response.requestId||'unavailable'}</div></div>}
 {error&&<div className="mt-4 rounded-xl bg-danger-soft p-3 text-xs text-danger">{error} <button type="button" className="ml-2 font-black underline" onClick={()=>void ask('Explain the visible market data and its limitations.')}>Retry</button></div>}<div className="mt-4 flex gap-2"><textarea rows={2} value={question} onChange={e=>setQuestion(e.target.value)} placeholder="Ask about the visible chart, source, timestamp, range or risk concept…" className="min-w-0 flex-1 resize-none rounded-xl border border-line bg-canvas px-3 py-2 text-xs text-ink outline-none focus:border-interactive focus:ring-2 focus:ring-interactive/15"/><button type="button" disabled={busy||!question.trim()} onClick={()=>void ask()} className="min-w-12 rounded-xl bg-brand px-3 text-white disabled:opacity-40" aria-label="Ask ArthaMind Market Explainer">{busy?<RefreshCw className="mx-auto h-4 w-4 animate-spin"/>:<Send className="mx-auto h-4 w-4"/>}</button></div><p className="mt-3 text-[9px] leading-4 text-secondary">Educational analysis only — not personalised investment, trading, tax, legal, or financial advice.</p></div></section>;
};
