import React,{useEffect,useMemo,useState}from'react';
import{AlertTriangle,RefreshCw,Search,Star}from'lucide-react';
import{INDIA_MARKET_UNIVERSE}from'../../data/indiaMarketUniverse';
import{fetchIndiaMarketStatus,type IndiaMarketStatus}from'../../services/indiaMarketApi';
import{fetchMarketHistory,fetchTickerQuote}from'../../services/learningApi';
import{FOREX_PAIRS,hasGenuineOhlc,historyStats,loadFxFavourites,looksIntraday,marketDataState,saveFxFavourites}from'../../services/marketPro';
import type{MarketHistoryPoint,NormalizedMarketQuote}from'../../types';
import{MarketPerformanceChart}from'../dashboard/DashboardCharts';
import{ArthaMindMarketExplainer,MarketDataBadge,MarketPageHeader,MarketSourcePanel}from'./MarketProShell';

const button='rounded-xl border border-line bg-canvas px-3 py-2 text-xs font-bold text-ink transition hover:border-interactive/35 disabled:cursor-not-allowed disabled:opacity-40';
const input='w-full rounded-xl border border-line-strong bg-canvas px-3 py-2.5 text-xs text-ink outline-none focus:border-interactive focus:ring-2 focus:ring-interactive/15';
const formatMoney=(value:number,currency:string)=>{try{return new Intl.NumberFormat(currency==='INR'?'en-IN':'en-US',{style:'currency',currency,maximumFractionDigits:currency==='JPY'?3:2}).format(value);}catch{return `${currency} ${value.toFixed(4)}`;}};
const formatRate=(value:number)=>value.toLocaleString(undefined,{maximumFractionDigits:6});
const movement=(value:number|null|undefined)=>value==null?'Unavailable':`${value>=0?'+':''}${value.toFixed(2)}%`;
const normalized=(value:string)=>value.toLowerCase().replace(/[^a-z0-9]+/g,'');

export const IntradayMarketLabView:React.FC=()=>{
 const choices=useMemo(()=>INDIA_MARKET_UNIVERSE.slice(0,18),[]);
 const[assetId,setAssetId]=useState(choices.find(item=>item.id==='reliance')?.id||choices[0]?.id||'reliance');
 const asset=choices.find(item=>item.id===assetId)||choices[0];
 const[status,setStatus]=useState<IndiaMarketStatus|null>(null);const[quote,setQuote]=useState<NormalizedMarketQuote|null>(null);const[history,setHistory]=useState<MarketHistoryPoint[]>([]);const[loading,setLoading]=useState(false);const[error,setError]=useState<string|null>(null);const[lastRefresh,setLastRefresh]=useState<string|null>(null);
 const load=async()=>{setLoading(true);setError(null);try{const nextStatus=await fetchIndiaMarketStatus();setStatus(nextStatus);if(!nextStatus.intradayConfigured||!nextStatus.intradayLicensed){setQuote(null);setHistory([]);setError(nextStatus.intradayLicensed?'No verified intraday provider is configured for this market.':'No verified intraday market-data entitlement is configured for this asset.');return;}const[q,h]=await Promise.allSettled([fetchTickerQuote(asset.providerSymbol),fetchMarketHistory(asset.providerSymbol,'1d')]);const nextQuote=q.status==='fulfilled'?q.value:null;const nextHistory=h.status==='fulfilled'?h.value.points:[];const providerMatches=Boolean(nextQuote&&normalized(nextStatus.intradayProvider)&&normalized(nextQuote.providerName).includes(normalized(nextStatus.intradayProvider)));if(!providerMatches){setQuote(nextQuote);setHistory([]);setError('The returned market data does not match the configured licensed intraday provider, so intraday controls remain disabled.');return;}setQuote(nextQuote);setHistory(nextHistory);setLastRefresh(new Date().toISOString());}catch{setQuote(null);setHistory([]);setError('Intraday market data could not be refreshed right now.');}finally{setLoading(false);}};
 useEffect(()=>{void load();},[assetId]);
 const genuineOhlc=hasGenuineOhlc(history);const timestamped=looksIntraday(history);const intradayReady=Boolean(status?.intradayConfigured&&status?.intradayLicensed&&quote&&timestamped&&genuineOhlc);const stats=historyStats(history);
 const limitation=!status?.intradayConfigured?'No verified intraday provider is configured for this market.':!status?.intradayLicensed?'No verified intraday market-data entitlement is configured for this asset.':!timestamped?'Intraday history is unavailable from the current provider.':!genuineOhlc?'True intraday OHLC is unavailable, so no candle or technical-indicator view is shown.':null;
 return <div className="mx-auto max-w-[1600px] space-y-6 px-4 py-7 sm:px-6"><MarketPageHeader eyebrow="Educational market observation · no trade signals" title="Intraday Market Lab" description="Intraday controls enable only after both licensed provider entitlement and actual timestamped OHLC data are verified. No synthetic candles, VWAP, RSI, moving averages or trade signals are generated."><button className={button} disabled={loading} onClick={()=>void load()}><RefreshCw className={`mr-2 inline h-4 w-4 ${loading?'animate-spin':''}`}/>Refresh provider status</button></MarketPageHeader>
 <section className="grid gap-4 xl:grid-cols-[340px_1fr]"><div className="rounded-3xl border border-line bg-surface p-5"><label className="text-[9px] font-black uppercase text-secondary">Tracked Indian asset</label><select className={`${input} mt-2`} value={assetId} onChange={e=>setAssetId(e.target.value)}>{choices.map(item=><option key={item.id} value={item.id}>{item.displayName} · {item.providerSymbol}</option>)}</select><div className="mt-4 grid gap-2"><StatusLine label="Intraday provider" value={status?.intradayProvider||'Checking…'}/><StatusLine label="Configured" value={status?status.intradayConfigured?'Yes':'No':'Checking…'}/><StatusLine label="Licensed entitlement" value={status?status.intradayLicensed?'Yes':'No':'Checking…'}/><StatusLine label="Data source match" value={quote&&status?normalized(quote.providerName).includes(normalized(status.intradayProvider))?'Yes':'No':'Unavailable'}/></div><div className="mt-4 flex flex-wrap gap-2">{['1m','5m','15m','30m','1h'].map(interval=><button key={interval} type="button" disabled={!intradayReady} className={`${button} ${intradayReady&&interval==='5m'?'border-interactive/30 bg-interactive-soft text-interactive':''}`}>{interval}</button>)}</div><p className="mt-3 text-[10px] leading-5 text-secondary">{intradayReady?'Verified timestamped OHLC exists. This build exposes the returned reference interval only; it does not fabricate unsupported resolutions.':limitation||'Intraday data is not verified.'}</p>{quote&&<div className="mt-4"><MarketSourcePanel quote={quote} extra="The quote itself can be a valid public-market reference even when intraday entitlement is not established."/></div>}</div>
 <div className="rounded-3xl border border-line bg-surface p-5 sm:p-6"><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="text-[10px] font-black uppercase text-secondary">Verified intraday chart</div><h2 className="mt-1 text-xl font-black text-ink">{asset?.displayName||assetId}</h2></div><MarketDataBadge quote={quote}/></div><div className="mt-4 h-[360px]">{loading?<div className="flex h-full items-center justify-center text-xs text-secondary"><RefreshCw className="mr-2 h-4 w-4 animate-spin"/>Checking provider and entitlement…</div>:intradayReady?<MarketPerformanceChart data={history} currency={quote?.currency||'INR'} rangeReturn={stats?.returnPercent??null}/>:<div className="flex h-full items-center justify-center px-6 text-center text-xs text-secondary">{error||limitation||'Intraday history is unavailable from the current provider.'}</div>}</div>{intradayReady&&stats&&<div className="mt-4 grid gap-2 sm:grid-cols-4"><Metric label="Visible high" value={formatMoney(stats.high,quote?.currency||'INR')}/><Metric label="Visible low" value={formatMoney(stats.low,quote?.currency||'INR')}/><Metric label="Visible return" value={stats.returnPercent==null?'Unavailable':movement(stats.returnPercent)}/><Metric label="Observations" value={String(stats.observations)}/></div>}<p className="mt-3 text-[9px] text-secondary">{lastRefresh?`Last successful refresh ${new Date(lastRefresh).toLocaleString('en-IN')}. `:''}Simulation only — no broker order is created.</p></div></section>
 <ArthaMindMarketExplainer page="Intraday Market Lab" visibleData={{asset:{id:asset?.id,name:asset?.displayName,symbol:asset?.providerSymbol},quote,historySummary:intradayReady?stats:null,intradayReady,providerStatus:status?{provider:status.intradayProvider,configured:status.intradayConfigured,licensed:status.intradayLicensed}:null}} sourceLabels={[quote?.providerName||status?.intradayProvider||'No verified provider response',marketDataState(quote).label]} suggestions={['Explain why the intraday controls are enabled or disabled.','Explain the visible OHLC range without predicting the next move.','What do the provider and entitlement states mean?','What data limitations should I notice?']}/></div>;
};

export const ForexIntelligenceView:React.FC=()=>{
 const[query,setQuery]=useState('');const[selected,setSelected]=useState(FOREX_PAIRS[0]);const[quote,setQuote]=useState<NormalizedMarketQuote|null>(null);const[history,setHistory]=useState<MarketHistoryPoint[]>([]);const[loading,setLoading]=useState(false);const[error,setError]=useState<string|null>(null);const[favourites,setFavourites]=useState<string[]>(loadFxFavourites);const[amount,setAmount]=useState('1000');const[lastSuccess,setLastSuccess]=useState<string|null>(null);
 const filtered=FOREX_PAIRS.filter(pair=>!query.trim()||[pair.pair,pair.base,pair.quote,pair.baseName,pair.quoteName].some(value=>value.toLowerCase().includes(query.toLowerCase())));
 const load=async()=>{setLoading(true);setError(null);const[q,h]=await Promise.allSettled([fetchTickerQuote(selected.providerSymbol),fetchMarketHistory(selected.providerSymbol,'1m')]);const nextQuote=q.status==='fulfilled'?q.value:null;setQuote(nextQuote);setHistory(h.status==='fulfilled'?h.value.points:[]);if(nextQuote)setLastSuccess(new Date().toISOString());else setError('Current FX quote unavailable');setLoading(false);};useEffect(()=>{void load();},[selected.providerSymbol]);
 const stats=historyStats(history);const dataState=marketDataState(quote);const severeStale=!quote||dataState.state==='stale'||dataState.state==='unavailable'||dataState.state==='demo';const amountNumber=Number(amount);const converted=!severeStale&&Number.isFinite(amountNumber)&&amountNumber>0&&quote?amountNumber*quote.price:null;const visible={pair:selected.pair,providerSymbol:selected.providerSymbol,quote,severeStale,historySummary:stats,bid:null,ask:null,spread:null,converterInput:Number.isFinite(amountNumber)?amountNumber:null,referenceConversion:converted};
 const toggleFavourite=()=>{const next=favourites.includes(selected.pair)?favourites.filter(item=>item!==selected.pair):[...favourites,selected.pair];setFavourites(next);saveFxFavourites(next);};
 return <div className="mx-auto max-w-[1600px] space-y-6 px-4 py-7 sm:px-6"><MarketPageHeader eyebrow="Currency research · provider timestamps required" title="Forex Intelligence" description="Educational FX reference data only. Stale references are never promoted as current conversion rates, and bid/ask/spread stay unavailable unless the provider supplies those fields."><button className={button} disabled={loading} onClick={()=>void load()}><RefreshCw className={`mr-2 inline h-4 w-4 ${loading?'animate-spin':''}`}/>Refresh pair</button></MarketPageHeader>
 <section className="grid gap-4 xl:grid-cols-[360px_1fr]"><div className="rounded-3xl border border-line bg-surface p-5"><div className="relative"><Search className="absolute left-3 top-3 h-4 w-4 text-secondary"/><input className={`${input} pl-9`} placeholder="Search pair, base or quote currency" value={query} onChange={e=>setQuery(e.target.value)}/></div><div className="mt-3 max-h-[360px] space-y-2 overflow-y-auto">{filtered.map(pair=><button key={pair.id} onClick={()=>setSelected(pair)} className={`w-full rounded-xl border p-3 text-left ${selected.id===pair.id?'border-interactive/30 bg-interactive-soft':'border-line bg-canvas'}`}><div className="flex items-center justify-between"><span className="text-xs font-black text-ink">{pair.pair}</span>{favourites.includes(pair.pair)&&<Star className="h-3.5 w-3.5 fill-current text-warning"/>}</div><div className="mt-1 text-[9px] text-secondary">{pair.baseName} / {pair.quoteName}</div></button>)}</div><button className={`${button} mt-3 w-full`} onClick={toggleFavourite}><Star className={`mr-2 inline h-3.5 w-3.5 ${favourites.includes(selected.pair)?'fill-current text-warning':''}`}/>{favourites.includes(selected.pair)?'Remove favourite':'Add favourite'}</button></div>
 <div className="space-y-4"><div className="rounded-3xl border border-line bg-surface p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="text-[10px] font-black uppercase text-secondary">FX quote</div><h2 className="mt-1 text-2xl font-black text-ink">{selected.pair}</h2>{quote&&!severeStale&&<div className="mt-2 text-3xl font-black text-ink">{formatRate(quote.price)}</div>}{quote&&severeStale&&<div className="mt-3 rounded-xl border border-warning-fill/25 bg-warning-soft p-3"><div className="text-xs font-black text-warning">Current FX quote unavailable</div><div className="mt-1 text-[10px] text-secondary">Last provider reference — {formatRate(quote.price)} · stale; not suitable for current decisions.</div></div>}{!quote&&!loading&&<div className="mt-3 text-sm font-black text-secondary">Current FX quote unavailable</div>}</div><MarketDataBadge quote={quote}/></div><div className="mt-4 grid gap-2 sm:grid-cols-2 lg:grid-cols-4"><Metric label="Daily change" value={severeStale?'Not current':movement(quote?.changePercent)}/><Metric label="Bid" value="Unavailable from current provider response"/><Metric label="Ask" value="Unavailable from current provider response"/><Metric label="Spread" value="Not calculated without bid + ask"/></div><div className="mt-4"><MarketSourcePanel quote={quote} extra={severeStale?'This reference is stale/unavailable and is not suitable as a current FX rate.':'Reference FX data only. Provider market hours, time-zone and delay behavior can differ by pair.'}/></div>{lastSuccess&&<div className="mt-2 text-[9px] text-secondary">Last successful refresh: {new Date(lastSuccess).toLocaleString('en-IN')}</div>}{error&&<div className="mt-2 text-[10px] text-danger">{error}</div>}</div>
 <div className="rounded-3xl border border-line bg-surface p-5"><div className="h-[320px]">{loading?<div className="flex h-full items-center justify-center text-xs text-secondary">Loading provider history…</div>:history.length?<MarketPerformanceChart data={history} currency={quote?.currency||selected.quote} rangeReturn={stats?.returnPercent??null}/>:<div className="flex h-full items-center justify-center text-xs text-secondary">Chart history unavailable from the current provider.</div>}</div>{stats&&<div className="mt-3 grid gap-2 sm:grid-cols-4"><Metric label="Period high" value={formatRate(stats.high)}/><Metric label="Period low" value={formatRate(stats.low)}/><Metric label="Period return" value={stats.returnPercent==null?'Unavailable':movement(stats.returnPercent)}/><Metric label="Observations" value={String(stats.observations)}/></div>}</div></div></section>
 <section className="grid gap-4 lg:grid-cols-2"><div className="rounded-3xl border border-line bg-surface p-5"><h2 className="text-lg font-black text-ink">FX reference converter</h2><p className="mt-1 text-xs text-secondary">Conversion is enabled only while the displayed provider reference is not stale, unavailable or demo data.</p><div className="mt-4 flex gap-2"><input className={input} type="number" min="0" value={amount} disabled={severeStale} onChange={e=>setAmount(e.target.value)}/><div className="flex min-w-[180px] items-center rounded-xl border border-line bg-canvas px-3 text-xs font-black text-ink">{converted==null?'Unavailable':`${converted.toLocaleString(undefined,{maximumFractionDigits:2})} ${selected.quote}`}</div></div>{severeStale?<p className="mt-3 flex items-start gap-2 text-[10px] leading-5 text-warning"><AlertTriangle className="mt-0.5 h-4 w-4 shrink-0"/>Converter disabled because the current FX rate is stale or unavailable. Refresh a verified provider reference before using the educational conversion.</p>:<p className="mt-3 text-[9px] text-secondary">Reference conversion, not a guaranteed bank, card, remittance or trade execution rate.</p>}</div><div className="rounded-3xl border border-line bg-surface p-5"><h2 className="text-lg font-black text-ink">FX learning cards</h2><div className="mt-3 grid grid-cols-2 gap-2">{['How exchange rates work','Bid, ask, and spread','Why FX moves','Central-bank rates and currencies','Currency risk for overseas education','Market hours and liquidity'].map(item=><div key={item} className="rounded-xl border border-line bg-canvas p-3 text-[10px] font-bold text-ink">{item}</div>)}</div></div></section>
 <ArthaMindMarketExplainer page="Forex Intelligence" visibleData={visible} sourceLabels={[quote?.providerName||'No provider response',dataState.label]} suggestions={['Explain the visible FX reference and freshness state.','What do bid, ask and spread mean, and what is missing here?','Why is the converter enabled or disabled?','Explain this range without predicting its next move.']}/></div>;
};

const Metric=({label,value}:{label:string;value:string})=><div className="rounded-xl border border-line bg-canvas p-3"><div className="text-[9px] font-black uppercase text-secondary">{label}</div><div className="mt-1 text-sm font-black text-ink">{value}</div></div>;
const StatusLine=({label,value}:{label:string;value:string})=><div className="flex items-center justify-between gap-3 rounded-xl border border-line bg-canvas px-3 py-2"><span className="text-[9px] font-bold text-secondary">{label}</span><span className="text-[9px] font-black text-ink">{value}</span></div>;
