import React,{useEffect,useMemo,useState}from'react';
import{ArrowLeft,ArrowRight,BookOpen,Calculator,CheckCircle2,RefreshCw,Search,ShieldCheck}from'lucide-react';
import{useAuth}from'../../auth/AuthContext';
import{MARKET_LEARNING_COURSES,findMarketLearningLesson,type MarketLearningCourse,type MarketLearningLesson,type MarketLearningLevel}from'../../data/marketLearningContent';
import type{EvidenceReference}from'../../services/marketAssistantApi';
import{ArthaMindMarketExplainer,MarketPageHeader}from'./MarketProShell';

const input='w-full rounded-xl border border-line-strong bg-canvas px-3 py-2.5 text-xs text-ink outline-none focus:border-interactive focus:ring-2 focus:ring-interactive/15';
const button='inline-flex items-center justify-center gap-2 rounded-xl border border-line bg-canvas px-3 py-2 text-xs font-black text-ink transition hover:border-interactive/30 disabled:cursor-not-allowed disabled:opacity-40';

type ProgressMap=Record<string,{completedLessons:string[];lastLesson:string|null;updatedAt:string}>;
const progressKey=(userId?:string)=>`arthabench_market_learning_progress_v2:${userId||'guest-local-demo'}`;
function readProgress(userId?:string):ProgressMap{if(typeof window==='undefined')return{};try{return JSON.parse(window.localStorage.getItem(progressKey(userId))||'{}') as ProgressMap;}catch{return{};}}
function writeProgress(userId:string|undefined,value:ProgressMap){if(typeof window!=='undefined')window.localStorage.setItem(progressKey(userId),JSON.stringify(value));}

function currentLessonPath(){if(typeof window==='undefined')return null;const match=window.location.pathname.match(/^\/finance\/markets\/learn\/([^/]+)\/([^/]+)\/?$/);return match?{courseSlug:decodeURIComponent(match[1]),lessonSlug:decodeURIComponent(match[2])}:null;}
function pushLesson(courseSlug:string,lessonSlug:string){window.history.pushState({},'',`/finance/markets/learn/${encodeURIComponent(courseSlug)}/${encodeURIComponent(lessonSlug)}`);window.dispatchEvent(new PopStateEvent('popstate'));window.scrollTo({top:0,behavior:'auto'});}
function pushLearningHome(){window.history.pushState({},'','/finance/markets/learn');window.dispatchEvent(new PopStateEvent('popstate'));window.scrollTo({top:0,behavior:'auto'});}

export const MarketsLearningLabView:React.FC=()=>{
 const auth=useAuth();const[userPath,setUserPath]=useState(currentLessonPath);const[progress,setProgress]=useState<ProgressMap>(()=>readProgress(auth.user?.id));
 useEffect(()=>{setProgress(readProgress(auth.user?.id));},[auth.user?.id]);
 useEffect(()=>{const sync=()=>setUserPath(currentLessonPath());window.addEventListener('popstate',sync);return()=>window.removeEventListener('popstate',sync);},[]);
 if(userPath){const found=findMarketLearningLesson(userPath.courseSlug,userPath.lessonSlug);if(found.course&&found.lesson)return <LessonDetail course={found.course} lesson={found.lesson} progress={progress} setProgress={setProgress} userId={auth.user?.id}/>;return <div className="mx-auto max-w-[1000px] px-4 py-12"><button className={button} onClick={pushLearningHome}><ArrowLeft className="h-4 w-4"/>Back to learning</button><div className="mt-6 rounded-3xl border border-dashed border-line p-10 text-center"><h1 className="text-xl font-black text-ink">Lesson not found</h1><p className="mt-2 text-xs text-secondary">This learning route does not match the current curriculum.</p></div></div>;}
 return <LearningHome progress={progress} userId={auth.user?.id}/>;
};

const LearningHome:React.FC<{progress:ProgressMap;userId?:string}>=({progress,userId})=>{
 const[query,setQuery]=useState('');const[level,setLevel]=useState<'all'|MarketLearningLevel>('all');
 const filtered=MARKET_LEARNING_COURSES.filter(course=>(level==='all'||course.level===level)&&(!query.trim()||`${course.title} ${course.description} ${course.level}`.toLowerCase().includes(query.trim().toLowerCase())));
 const completed=Object.values(progress).reduce((sum,row)=>sum+row.completedLessons.length,0);const total=MARKET_LEARNING_COURSES.reduce((sum,course)=>sum+course.lessons.length,0);
 return <div className="mx-auto max-w-[1500px] space-y-6 px-4 py-7 sm:px-6"><MarketPageHeader eyebrow="Markets education · deterministic progress" title="Markets Learning Lab" description="Structured lessons, knowledge checks, calculators and evidence-grounded tutoring. Learning progress is stored locally in this browser in the current build; it is not presented as cloud-synced unless a real persistence backend confirms it."/>
 <section className="grid gap-3 sm:grid-cols-3"><Metric label="Tracks" value={String(MARKET_LEARNING_COURSES.length)}/><Metric label="Lessons completed" value={`${completed}/${total}`}/><Metric label="Persistence" value={userId?'Signed-in browser-local progress':'Guest local-demo progress'}/></section>
 <section className="rounded-3xl border border-line bg-surface p-5"><div className="grid gap-3 sm:grid-cols-[1fr_220px]"><label className="relative"><Search className="absolute left-3 top-3 h-4 w-4 text-secondary"/><span className="sr-only">Search learning tracks</span><input className={`${input} pl-9`} value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search tracks, levels or concepts"/></label><select className={input} value={level} onChange={e=>setLevel(e.target.value as 'all'|MarketLearningLevel)}><option value="all">All levels</option><option>Beginner</option><option>Intermediate</option><option>Advanced</option></select></div></section>
 {filtered.length?<section className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{filtered.map(course=><CourseCard key={course.slug} course={course} progress={progress[course.slug]}/>)}</section>:<section className="rounded-3xl border border-dashed border-line p-10 text-center"><BookOpen className="mx-auto h-8 w-8 text-secondary"/><h2 className="mt-3 text-sm font-black text-ink">No learning track matches these filters.</h2><p className="mt-2 text-xs text-secondary">Clear search or level filters to continue.</p></section>}
 <LearningSimulators/>
 <section className="rounded-2xl border border-line bg-canvas p-4 text-[10px] leading-5 text-secondary"><ShieldCheck className="mr-2 inline h-4 w-4 text-success"/>All calculators in this learning area are deterministic educational examples. They show inputs, logic, and limitations and do not create broker orders, loan approvals, tax filings, or personalised investment recommendations.</section></div>;
};

const CourseCard=({course,progress}:{course:MarketLearningCourse;progress?:ProgressMap[string]})=>{const completed=progress?.completedLessons.length||0;const firstIncomplete=course.lessons.find(item=>!progress?.completedLessons.includes(item.slug))||course.lessons[0];const percent=Math.round(completed/course.lessons.length*100);return <article className="rounded-2xl border border-line bg-surface p-5"><div className="flex items-start justify-between gap-3"><BookOpen className="h-5 w-5 text-interactive"/><span className="rounded-full border border-line bg-canvas px-2.5 py-1 text-[8px] font-black text-secondary">{course.level}</span></div><h2 className="mt-4 text-base font-black text-ink">{course.title}</h2><p className="mt-2 text-[10px] leading-5 text-secondary">{course.description}</p><div className="mt-3 flex flex-wrap gap-2 text-[9px] text-secondary"><span>{course.durationMinutes} min</span><span>·</span><span>{course.lessons.length} lessons</span><span>·</span><span>{percent}% complete</span></div><div className="mt-3 h-1.5 overflow-hidden rounded-full bg-line"><div className="h-full bg-interactive" style={{width:`${percent}%`}}/></div><button type="button" className={`${button} mt-4 w-full`} onClick={()=>pushLesson(course.slug,firstIncomplete.slug)}>{completed?<>Continue learning <ArrowRight className="h-4 w-4"/></>:<>Start learning <ArrowRight className="h-4 w-4"/></>}</button></article>;};

const LessonDetail:React.FC<{course:MarketLearningCourse;lesson:MarketLearningLesson;progress:ProgressMap;setProgress:React.Dispatch<React.SetStateAction<ProgressMap>>;userId?:string}>=({course,lesson,progress,setProgress,userId})=>{
 const lessonIndex=course.lessons.findIndex(item=>item.slug===lesson.slug);const previous=course.lessons[lessonIndex-1]||null;const next=course.lessons[lessonIndex+1]||null;const completed=progress[course.slug]?.completedLessons.includes(lesson.slug)||false;
 const[selected,setSelected]=useState<number|null>(null);const[submitted,setSubmitted]=useState(false);const[quizMessage,setQuizMessage]=useState('');
 useEffect(()=>{setSelected(null);setSubmitted(false);setQuizMessage('');},[lesson.slug]);
 const submitQuiz=()=>{if(selected==null)return;setSubmitted(true);setQuizMessage(selected===lesson.quiz.correctIndex?'Correct. '+lesson.quiz.explanation:'Not quite. '+lesson.quiz.explanation);};
 const markComplete=()=>{const row=progress[course.slug]||{completedLessons:[],lastLesson:null,updatedAt:new Date().toISOString()};const completedLessons=row.completedLessons.includes(lesson.slug)?row.completedLessons:[...row.completedLessons,lesson.slug];const nextProgress={...progress,[course.slug]:{completedLessons,lastLesson:lesson.slug,updatedAt:new Date().toISOString()}};setProgress(nextProgress);writeProgress(userId,nextProgress);};
 const evidence:EvidenceReference[]=[{id:'lesson-content',label:`Learning content: ${course.title} / ${lesson.title}`,sourceType:'learning_content',valueSummary:`Objective: ${lesson.objective}`}];
 return <div className="mx-auto max-w-[1100px] space-y-6 px-4 py-7 sm:px-6"><div className="flex flex-wrap gap-2"><button className={button} onClick={pushLearningHome}><ArrowLeft className="h-4 w-4"/>Learning home</button><span className="rounded-xl border border-line bg-canvas px-3 py-2 text-[10px] font-bold text-secondary">{course.title} · Lesson {lessonIndex+1}/{course.lessons.length}</span></div>
 <section className="rounded-3xl border border-line bg-surface p-6 sm:p-8"><div className="text-[10px] font-black uppercase tracking-wider text-interactive">{course.level} · {course.durationMinutes} min track</div><h1 className="mt-2 text-3xl font-black text-ink">{lesson.title}</h1><div className="mt-5 rounded-2xl border border-interactive/20 bg-interactive-soft p-4"><div className="text-[9px] font-black uppercase text-interactive">Learning objective</div><p className="mt-2 text-sm leading-6 text-ink">{lesson.objective}</p></div></section>
 {lesson.sections.map(section=><section key={section.title} className="rounded-2xl border border-line bg-surface p-5"><h2 className="text-lg font-black text-ink">{section.title}</h2><p className="mt-3 text-sm leading-7 text-secondary">{section.content}</p></section>)}
 <section className="grid gap-4 lg:grid-cols-2"><div className="rounded-2xl border border-line bg-surface p-5"><h2 className="text-lg font-black text-ink">Glossary</h2><div className="mt-3 space-y-3">{lesson.glossary.map(item=><div key={item.term}><div className="text-xs font-black text-ink">{item.term}</div><div className="mt-1 text-[10px] leading-5 text-secondary">{item.meaning}</div></div>)}</div></div><div className="rounded-2xl border border-line bg-surface p-5"><h2 className="text-lg font-black text-ink">{lesson.example.title}</h2><div className="mt-3 text-[10px] leading-5 text-secondary"><strong className="text-ink">Inputs:</strong><ul className="mt-1">{lesson.example.inputs.map(item=><li key={item}>• {item}</li>)}</ul><p className="mt-2"><strong className="text-ink">Logic:</strong> {lesson.example.logic}</p><p className="mt-2"><strong className="text-ink">Result:</strong> {lesson.example.result}</p><p className="mt-2"><strong className="text-ink">Limitation:</strong> {lesson.example.limitation}</p></div></div></section>
 {lesson.sources?.length?<section className="rounded-2xl border border-line bg-canvas p-4"><div className="text-[10px] font-black text-ink">Source links</div><div className="mt-2 flex flex-wrap gap-2">{lesson.sources.map(source=><a key={source.href} href={source.href} target="_blank" rel="noreferrer" className="text-[10px] font-bold text-interactive underline">{source.label}</a>)}</div></section>:null}
 <section className="rounded-3xl border border-line bg-surface p-5 sm:p-6"><div className="text-[10px] font-black uppercase text-interactive">Knowledge check</div><h2 className="mt-2 text-lg font-black text-ink">{lesson.quiz.question}</h2><div className="mt-4 space-y-2">{lesson.quiz.options.map((option,index)=><label key={option} className={`flex cursor-pointer items-start gap-3 rounded-xl border p-3 ${selected===index?'border-interactive/40 bg-interactive-soft':'border-line bg-canvas'}`}><input type="radio" name={`quiz-${lesson.slug}`} checked={selected===index} disabled={submitted} onChange={()=>setSelected(index)} className="mt-0.5"/><span className="text-xs text-ink">{option}</span></label>)}</div><div className="mt-4 flex flex-wrap gap-2"><button className={button} disabled={selected==null||submitted} onClick={submitQuiz}>Submit answer</button>{submitted&&<button className={button} onClick={()=>{setSelected(null);setSubmitted(false);setQuizMessage('');}}><RefreshCw className="h-4 w-4"/>Retry</button>}</div>{submitted&&<div className={`mt-4 rounded-xl border p-3 text-xs leading-5 ${selected===lesson.quiz.correctIndex?'border-success-fill/20 bg-success-soft text-success':'border-warning-fill/20 bg-warning-soft text-warning'}`}>{quizMessage}</div>}</section>
 <section className="rounded-2xl border border-line bg-canvas p-4"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><div className="text-xs font-black text-ink">Lesson progress</div><p className="mt-1 text-[9px] text-secondary">{userId?'Signed-in progress is stored locally in this browser in the current build.':'Guest progress is a local-only demo on this browser.'} No cloud-sync claim is made.</p></div><button className={`${button} ${completed?'border-success-fill/25 bg-success-soft text-success':''}`} onClick={markComplete}>{completed?<><CheckCircle2 className="h-4 w-4"/>Completed</>:<><CheckCircle2 className="h-4 w-4"/>Mark complete</>}</button></div></section>
 <ArthaMindMarketExplainer page={`Markets Learning Lab · ${course.title} · ${lesson.title}`} visibleData={{course:course.title,lesson:lesson.title,objective:lesson.objective,sections:lesson.sections,glossary:lesson.glossary,example:lesson.example}} sourceLabels={['Artha Bench original learning content']} evidence={evidence} suggestions={['Explain this lesson in simpler language.','Quiz me conceptually without giving trade advice.','What is the biggest limitation of the example?','Give me a neutral research checklist based on this lesson.']}/>
 <div className="flex items-center justify-between gap-3"><button className={button} disabled={!previous} onClick={()=>previous&&pushLesson(course.slug,previous.slug)}><ArrowLeft className="h-4 w-4"/>Previous lesson</button>{next?<button className={button} onClick={()=>pushLesson(course.slug,next.slug)}>Next lesson <ArrowRight className="h-4 w-4"/></button>:<button className={button} onClick={pushLearningHome}>Back to all tracks <ArrowRight className="h-4 w-4"/></button>}</div></div>;
};

const LearningSimulators:React.FC=()=>{
 const[income,setIncome]=useState('50000');const[expenses,setExpenses]=useState('40000');const[principal,setPrincipal]=useState('500000');const[annualRate,setAnnualRate]=useState('10');const[months,setMonths]=useState('60');const[inflation,setInflation]=useState('5');const[years,setYears]=useState('3');const[fxAmount,setFxAmount]=useState('1000');const[fxRate,setFxRate]=useState('83');
 const surplus=Number(income)-Number(expenses);const p=Number(principal),monthlyRate=Number(annualRate)/1200,n=Number(months);const emi=p>0&&monthlyRate>0&&n>0?p*monthlyRate*Math.pow(1+monthlyRate,n)/(Math.pow(1+monthlyRate,n)-1):null;const inflationFactor=Number(inflation)>=0&&Number(years)>=0?Math.pow(1+Number(inflation)/100,Number(years)):null;const futureCost=inflationFactor?100000*inflationFactor:null;const conversion=Number(fxAmount)>0&&Number(fxRate)>0?Number(fxAmount)*Number(fxRate):null;
 return <section className="rounded-3xl border border-line bg-surface p-5 sm:p-6"><div className="flex items-center gap-2"><Calculator className="h-5 w-5 text-interactive"/><h2 className="text-xl font-black text-ink">Deterministic learning simulators</h2></div><p className="mt-2 text-xs text-secondary">Edit inputs to observe arithmetic relationships. Inputs are assumptions, not personalised recommendations or provider quotes.</p><div className="mt-5 grid gap-4 lg:grid-cols-2">
 <Simulator title="Budget simulator" inputs={<><NumberField label="Monthly income" value={income} onChange={setIncome}/><NumberField label="Monthly expenses" value={expenses} onChange={setExpenses}/></>} logic="Surplus = income − expenses." result={Number.isFinite(surplus)?`Result: ${surplus>=0?'surplus':'deficit'} ${Math.abs(surplus).toLocaleString('en-IN')}.`:'Enter valid numbers.'} limitation="Does not prescribe a budget allocation or emergency-fund target."/>
 <Simulator title="EMI affordability simulator" inputs={<><NumberField label="Principal" value={principal} onChange={setPrincipal}/><NumberField label="Annual rate %" value={annualRate} onChange={setAnnualRate}/><NumberField label="Months" value={months} onChange={setMonths}/></>} logic="EMI = P × r(1+r)^n ÷ ((1+r)^n − 1), with r as monthly decimal rate." result={emi?`Illustrative EMI: ${emi.toLocaleString('en-IN',{maximumFractionDigits:2})}.`:'Enter positive principal, rate and months.'} limitation="This is not lender approval, an offer, or an affordability recommendation."/>
 <Simulator title="Inflation scenario" inputs={<><NumberField label="Annual inflation assumption %" value={inflation} onChange={setInflation}/><NumberField label="Years" value={years} onChange={setYears}/></>} logic="Future illustrative cost = current cost × (1 + inflation rate)^years, using a ₹100,000 example baseline." result={futureCost?`₹100,000 illustrative cost becomes ${futureCost.toLocaleString('en-IN',{maximumFractionDigits:2})}.`:'Enter valid non-negative assumptions.'} limitation="Inflation is an assumption here, not a forecast of actual future prices."/>
 <Simulator title="FX conversion scenario" inputs={<><NumberField label="Base amount" value={fxAmount} onChange={setFxAmount}/><NumberField label="Assumed FX rate" value={fxRate} onChange={setFxRate}/></>} logic="Reference conversion = base amount × explicitly entered assumed rate." result={conversion?`Illustrative converted amount: ${conversion.toLocaleString(undefined,{maximumFractionDigits:2})}.`:'Enter positive values.'} limitation="The entered FX rate is a learning assumption, not a live/provider-backed exchange or remittance rate."/>
 </div></section>;
};

const NumberField=({label,value,onChange}:{label:string;value:string;onChange:(value:string)=>void})=><label className="block"><span className="text-[8px] font-black uppercase text-secondary">{label}</span><input type="number" className={`${input} mt-1`} value={value} onChange={e=>onChange(e.target.value)}/></label>;
const Simulator=({title,inputs,logic,result,limitation}:{title:string;inputs:React.ReactNode;logic:string;result:string;limitation:string})=><article className="rounded-2xl border border-line bg-canvas p-4"><h3 className="text-sm font-black text-ink">{title}</h3><div className="mt-3 grid gap-2 sm:grid-cols-2">{inputs}</div><div className="mt-3 text-[10px] leading-5 text-secondary"><p><strong className="text-ink">Logic:</strong> {logic}</p><p className="mt-1"><strong className="text-ink">Output:</strong> {result}</p><p className="mt-1"><strong className="text-ink">Limitation:</strong> {limitation}</p></div></article>;
const Metric=({label,value}:{label:string;value:string})=><div className="rounded-xl border border-line bg-surface p-4"><div className="text-[8px] font-black uppercase tracking-wider text-secondary">{label}</div><div className="mt-1 text-sm font-black text-ink">{value}</div></div>;
