import React,{useMemo,useState}from'react';
import{BarChart3,Bell,Crown,DollarSign,GraduationCap,Landmark,RefreshCw,Send,ShieldCheck,Sparkles,Star,Timer}from'lucide-react';
import{AppNavigationDestination}from'../../navigationTypes';
import{pathForDestination}from'../../appRoutes';
import{askReliableTutor}from'../../services/reliableTutor';
import{buildMarketExplainerPrompt,isUnsafeTradingAdviceRequest,marketDataState,MARKET_SAFE_REDIRECT}from'../../services/marketPro';
import type{NormalizedMarketQuote}from'../../types';

export const MARKET_PRO_DESTINATIONS:Array<{id:AppNavigationDestination;label:string;icon:React.ComponentType<{className?:string}>}>=[
 {id:'india-markets',label:'India',icon:Landmark},{id:'intraday-markets',label:'Intraday',icon:Timer},{id:'forex-markets',label:'Forex',icon:DollarSign},{id:'us-markets',label:'US',icon:BarChart3},{id:'market-watchlist',label:'Watchlist',icon:Star},{id:'market-alerts',label:'Alerts',icon:Bell},{id:'markets-learn',label:'Learn',icon:GraduationCap},{id:'go-pro',label:'ArthaMind Pro',icon:Crown},
];

export const MarketProNavigation:React.FC<{current:AppNavigationDestination;onNavigate:(destination:AppNavigationDestination)=>void}>=({current,onNavigate})=><nav aria-label="ArthaMind Pro market navigation" className="sticky top-[65px] z-30 border-b border-line bg-canvas/95 px-4 py-2 backdrop-blur sm:px-6"><div className="mx-auto flex max-w-[1600px] gap-1.5 overflow-x-auto scrollbar-thin">{MARKET_PRO_DESTINATIONS.map(({id,label,icon:Icon})=><a key={id} href={pathForDestination(id)} onClick={event=>{if(event.button!==0||event.metaKey||event.ctrlKey||event.shiftKey||event.altKey)return;event.preventDefault();onNavigate(id);}} aria-current={current===id?'page':undefined} className={`inline-flex shrink-0 items-center gap-2 rounded-xl border px-3 py-2 text-xs font-bold focus-visible:outline focus-visible:outline-2 focus-visible:outline-interactive ${current===id?'border-interactive/30 bg-interactive-soft text-interactive':'border-transparent text-secondary hover:border-line hover:bg-surface hover:text-ink'}`}><Icon className="h-3.5 w-3.5"/>{label}</a>)}</div></nav>;

export const MarketDataBadge:React.FC<{quote?:NormalizedMarketQuote|null}>=({quote})=>{const state=marketDataState(quote);const cls=state.state==='live_verified'||state.state==='recently_refreshed'?'border-success-fill/25 bg-success-soft text-success':state.state==='delayed'||state.state==='end_of_day'||state.state==='cached'?'border-warning-fill/25 bg-warning-soft text-warning':state.state==='stale'?'border-danger/20 bg-danger-soft text-danger':'border-line bg-canvas text-secondary';return <span className={`inline-flex rounded-full border px-2.5 py-1 text-[9px] font-black ${cls}`}>{state.label}</span>;};

export const MarketPageHeader:React.FC<{eyebrow:string;title:string;description:string;children?:React.ReactNode}>=({eyebrow,title,description,children})=><section className="rounded-3xl border border-line bg-surface p-5 shadow-sm sm:p-7"><div className="flex flex-col gap-4 lg:flex-row lg:items-start lg:justify-between"><div><div className="text-[10px] font-black uppercase tracking-[.15em] text-interactive">{eyebrow}</div><h1 className="mt-2 text-3xl font-black text-ink sm:text-4xl">{title}</h1><p className="mt-2 max-w-4xl text-sm leading-6 text-secondary">{description}</p></div>{children}</div></section>;

export const MarketSourcePanel:React.FC<{quote?:NormalizedMarketQuote|null;extra?:string}>=({quote,extra})=>{const state=marketDataState(quote);return <div className="rounded-2xl border border-line bg-canvas p-3 text-[10px] leading-5 text-secondary"><div className="flex flex-wrap items-center gap-2"><ShieldCheck className="h-3.5 w-3.5 text-success"/><strong className="text-ink">Source & freshness</strong><MarketDataBadge quote={quote}/></div><div className="mt-2">Provider: {quote?.providerName||'No verified provider response'} · Symbol: {quote?.symbol||'Unavailable'} · Exchange: {quote?.exchange||'Provider-defined / unavailable'}</div><div>Quote timestamp: {quote?.providerTimestamp?new Date(quote.providerTimestamp).toLocaleString('en-IN'):'Unavailable'} · Retrieved: {quote?.retrievedAt?new Date(quote.retrievedAt).toLocaleString('en-IN'):'Unavailable'}</div><div>Data state: {state.label}. {extra||'Review the source timestamp before interpreting the value.'}</div></div>;};

export const ArthaMindMarketExplainer:React.FC<{page:string;visibleData:unknown;sourceLabels:string[];suggestions:string[]}>=({page,visibleData,sourceLabels,suggestions})=>{
 const[question,setQuestion]=useState('');const[answer,setAnswer]=useState('');const[busy,setBusy]=useState(false);const[error,setError]=useState<string|null>(null);const[fallbackMode,setFallbackMode]=useState(false);
 const context=useMemo(()=>visibleData,[visibleData]);
 const ask=async(prompt?:string)=>{const q=(prompt??question).trim();if(!q||busy)return;setError(null);setQuestion('');if(isUnsafeTradingAdviceRequest(q)){setFallbackMode(false);setAnswer(MARKET_SAFE_REDIRECT);return;}setBusy(true);try{const response=await askReliableTutor(buildMarketExplainerPrompt({question:q,page,visibleData:context,sourceLabels}),{visibleData:context,context:{country:'Global',currency:'USD',language:'english',level:'advanced',mode:'explain',detail:'detailed',useOfficialSources:false}});setFallbackMode(response.fallbackMode);setAnswer(response.answer);}catch{setFallbackMode(true);setError('ArthaMind could not complete the request. Retry after refreshing the page data.');}finally{setBusy(false);}};
 return <section className="rounded-3xl border border-interactive/20 bg-surface p-5 shadow-sm sm:p-6"><div className="flex items-start gap-3"><div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-interactive-soft text-interactive"><Sparkles className="h-5 w-5"/></div><div><div className="flex flex-wrap items-center gap-2"><div className="text-[10px] font-black uppercase tracking-[.14em] text-interactive">Evidence-linked AI education</div>{fallbackMode&&<span className="rounded-full border border-warning-fill/25 bg-warning-soft px-2 py-0.5 text-[8px] font-black uppercase text-warning">Grounded fallback</span>}</div><h2 className="mt-1 text-xl font-black text-ink">ArthaMind Market Explainer</h2><p className="mt-1 text-xs leading-5 text-secondary">Uses only the visible, provider-backed snapshot supplied by this page. If the external AI provider is unavailable, the assistant stays responsive in grounded fallback mode and does not invent market facts.</p></div></div><div className="mt-4 flex flex-wrap gap-2">{suggestions.map(item=><button key={item} type="button" onClick={()=>void ask(item)} className="rounded-xl border border-line bg-canvas px-3 py-2 text-left text-[10px] font-bold text-secondary hover:border-interactive/30 hover:text-ink">{item}</button>)}</div>{answer&&<div className="mt-4 whitespace-pre-wrap rounded-2xl border border-line bg-canvas p-4 text-xs leading-6 text-ink"><div className="mb-2 text-[9px] font-black uppercase tracking-wider text-interactive">ArthaMind explanation</div>{answer}<div className="mt-3 border-t border-line pt-3 text-[9px] text-secondary">Sources in this page context: {sourceLabels.join(' · ')||'No source labels available'}.</div></div>}{error&&<div className="mt-4 rounded-xl bg-danger-soft p-3 text-xs text-danger">{error}</div>}<div className="mt-4 flex gap-2"><textarea rows={2} value={question} onChange={e=>setQuestion(e.target.value)} onKeyDown={e=>{if((e.ctrlKey||e.metaKey)&&e.key==='Enter')void ask();}} placeholder="Ask about the visible chart, source, timestamp, range or risk concept…" className="min-w-0 flex-1 resize-none rounded-xl border border-line bg-canvas px-3 py-2 text-xs text-ink outline-none focus:border-interactive focus:ring-2 focus:ring-interactive/15"/><button type="button" disabled={busy||!question.trim()} onClick={()=>void ask()} className="min-w-12 rounded-xl bg-brand px-3 text-white disabled:opacity-40" aria-label="Ask ArthaMind Market Explainer">{busy?<RefreshCw className="mx-auto h-4 w-4 animate-spin"/>:<Send className="mx-auto h-4 w-4"/>}</button></div><p className="mt-3 text-[9px] leading-4 text-secondary">Educational analysis only — not personalised investment, trading, tax, legal, or financial advice.</p></section>;
};
