import React, { useEffect, useState } from 'react';
import { ArrowDown, ArrowRight, ArrowUp, Building2 } from 'lucide-react';
import { AppNavigationDestination } from '../../navigationTypes';
import { INDIA_MARKET_UNIVERSE } from '../../data/indiaMarketUniverse';
import { fetchMarketOverview } from '../../services/learningApi';
import { NormalizedMarketQuote } from '../../types';

type Props = { onNavigate: (destination: AppNavigationDestination) => void };
const preview = INDIA_MARKET_UNIVERSE.slice(0, 8);

export const IndiaMarketExplorerPreview: React.FC<Props> = ({ onNavigate }) => {
  const [quotes, setQuotes] = useState<Record<string, NormalizedMarketQuote>>({});
  useEffect(() => { let active=true; fetchMarketOverview(preview.map((item)=>item.providerSymbol)).then((rows)=>{if(active)setQuotes(Object.fromEntries(rows.map((row)=>[row.symbol,row])));}).catch(()=>{}); return()=>{active=false;}; }, []);
  return <section className="mx-auto max-w-[1700px] px-4 pt-7 sm:px-6"><div className="rounded-3xl border border-line bg-surface p-5 shadow-sm sm:p-6"><div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div><div className="flex items-center gap-2 text-[10px] font-black uppercase tracking-[.14em] text-interactive"><Building2 className="h-4 w-4" /> India Market Explorer</div><h2 className="mt-2 text-xl font-black text-ink">Top Indian stocks preview</h2><p className="mt-1 text-[10px] leading-5 text-secondary">A concise provider-backed preview. The full searchable directory contains {INDIA_MARKET_UNIVERSE.length} configured company identities and loads quotes only when requested.</p></div><button type="button" onClick={()=>onNavigate('india-markets')} className="inline-flex items-center gap-2 rounded-xl border border-interactive/30 bg-interactive-soft px-4 py-2.5 text-xs font-black text-interactive">Explore Indian markets <ArrowRight className="h-3.5 w-3.5" /></button></div><div className="mt-5 grid gap-2 sm:grid-cols-2 lg:grid-cols-4">{preview.map((company)=>{const quote=quotes[company.providerSymbol];const move=quote?.changePercent??null;return <button key={company.id} type="button" onClick={()=>onNavigate('india-markets')} className="rounded-2xl border border-line bg-canvas p-3 text-left hover:border-interactive/30"><div className="flex items-start justify-between gap-2"><div><div className="text-[10px] font-black text-ink">{company.displayName}</div><div className="mt-0.5 text-[8px] text-secondary">{company.providerSymbol}</div></div>{move!=null&&<span className={`inline-flex items-center gap-0.5 text-[9px] font-black ${move>=0?'text-success':'text-danger'}`}>{move>=0?<ArrowUp className="h-3 w-3"/>:<ArrowDown className="h-3 w-3"/>}{move>=0?'+':''}{move.toFixed(2)}%</span>}</div><div className="mt-2 text-xs font-black text-ink">{quote?new Intl.NumberFormat('en-IN',{style:'currency',currency:quote.currency||'INR',maximumFractionDigits:2}).format(quote.price):'Quote unavailable'}</div><div className="mt-1 text-[8px] text-secondary">{quote?`${quote.providerName} · ${quote.freshness.replaceAll('_',' ')} · ${quote.providerTimestamp||quote.retrievedAt}`:'Current provider did not return a verified quote.'}</div></button>;})}</div></div></section>;
};
