import React from 'react';
import {Calculator,CheckCircle2,ShieldAlert,Database,Lightbulb} from 'lucide-react';
import {StructuredFinancialAnswer} from '../../types';
import {RichFinancialText} from './RichFinancialText';
import {ListenBar} from '../voice/ListenBar';

export const StructuredFinancialAnswerView:React.FC<{answer:StructuredFinancialAnswer;disclaimer?:string;compact?:boolean}>=({answer,disclaimer='Educational material only. Verify consequential financial, tax, legal or investment decisions with an appropriate official source.',compact=false})=>{
 const clean=(v:string)=>v.replace(/\\\[|\\\]|```/g,'').replace(/^\s*#+\s*/gm,'').replace(/\\#/g,'#').replace(/\\text\{([^}]*)\}/g,'$1').trim();
 const direct=clean(answer.directAnswer||'');
 const formula=clean(answer.formula?.expression||'');
 return <article className={`w-full overflow-hidden rounded-2xl border border-line bg-surface text-ink shadow-sm ${compact?'text-xs':'text-sm'}`}>
  <header className="border-b border-line px-4 py-4"><div className="flex items-start justify-between gap-3"><div><div className="text-[9px] font-extrabold uppercase tracking-[.18em] text-interactive">ArthaBench learning</div><h3 className="mt-1 text-lg font-extrabold leading-snug">{clean(answer.title)}</h3></div><span className="inline-flex items-center gap-1 rounded-full bg-success-soft px-2 py-1 text-[9px] font-bold text-success"><CheckCircle2 className="h-3 w-3"/>Validated response</span></div></header>
  <div className="space-y-4 p-4">
   {direct&&<section className="rounded-xl border border-interactive/20 bg-interactive-soft/60 p-4"><div className="mb-2 flex items-center gap-2 text-[10px] font-extrabold uppercase tracking-wider text-interactive"><Lightbulb className="h-3.5 w-3.5"/>Explanation</div><RichFinancialText value={direct}/></section>}
   {answer.steps?.length>0&&<section><div className="mb-2 text-[10px] font-extrabold uppercase tracking-wider text-secondary">Build the idea</div><div className="space-y-2">{answer.steps.map((s,i)=><div key={i} className="flex gap-3 rounded-xl border border-line bg-subtle p-3"><span className="flex h-6 w-6 shrink-0 items-center justify-center rounded-full bg-interactive text-[10px] font-bold text-white">{i+1}</span><div><div className="font-bold">{clean(s.title)}</div><RichFinancialText value={clean(s.explanation)} className="mt-1 text-secondary"/></div></div>)}</div></section>}
   {formula&&formula!=='A formula is shown only when it is relevant to the question.'&&<section className="rounded-xl border border-line bg-canvas p-3"><div className="mb-2 flex items-center gap-2 text-[10px] font-extrabold uppercase tracking-wider text-secondary"><Calculator className="h-3.5 w-3.5"/>Formula</div><div className="rounded-lg bg-surface p-3 font-mono text-xs font-semibold text-interactive"><RichFinancialText value={formula}/></div>{answer.formula.variables?.length>0&&<div className="mt-2 grid gap-2 sm:grid-cols-2">{answer.formula.variables.map((v,i)=><div key={i} className="rounded-lg border border-line p-2"><b className="font-mono text-interactive">{clean(v.symbol)}</b><div className="text-[10px] text-secondary">{clean(v.meaning)}</div></div>)}</div>}</section>}
   {answer.example?.result&&<section className="rounded-xl border border-success/20 bg-success-soft p-3"><div className="text-[10px] font-extrabold uppercase tracking-wider text-success">Result</div><div className="mt-1 font-bold"><RichFinancialText value={clean(answer.example.result)}/></div>{answer.example.calculation?.length>0&&<ul className="mt-2 space-y-1 text-xs text-secondary">{answer.example.calculation.map((x,i)=><li key={i}>• <RichFinancialText value={clean(x)}/></li>)}</ul>}</section>}
   {answer.keyTakeaways?.length>0&&<section className="rounded-xl border border-interactive/20 p-3"><div className="text-[10px] font-extrabold uppercase tracking-wider text-interactive">Key takeaway</div>{answer.keyTakeaways.map((x,i)=><div key={i} className="mt-1"><RichFinancialText value={clean(x)}/></div>)}</section>}
   {answer.sources?.length>0&&<section className="rounded-xl border border-line p-3"><div className="mb-2 flex items-center gap-2 text-[10px] font-extrabold uppercase tracking-wider text-secondary"><Database className="h-3.5 w-3.5"/>Sources</div><div className="flex flex-wrap gap-2">{answer.sources.map((s,i)=><span key={i} className="rounded-lg border border-line bg-subtle px-2 py-1 text-[10px] text-secondary"><b className="text-ink">{clean(s.name)}</b>{s.dataDate?` · ${s.dataDate}`:''}{s.freshness?` · ${s.freshness}`:''}</span>)}</div></section>}
   {answer.risks?.length>0&&<section className="rounded-xl border border-warning/20 bg-warning-soft p-3"><div className="mb-1 flex items-center gap-2 text-[10px] font-extrabold uppercase tracking-wider"><ShieldAlert className="h-3.5 w-3.5"/>Worth knowing</div>{answer.risks.map((x,i)=><div key={i} className="text-xs text-secondary">{clean(x)}</div>)}</section>}
   <ListenBar compact={compact} text={[direct,...(answer.keyTakeaways??[]).map(clean),...(answer.risks??[]).slice(0,2).map(clean)].filter(Boolean).join('\n')}/>
   <div className="border-t border-line pt-3 text-[10px] text-secondary">{disclaimer}</div>
  </div>
 </article>;
};
